#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("x_address0", 10, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("x_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("x_we0", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("x_d0", 32, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("x_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("x_address1", 10, hls_out, 0, "ap_memory", "MemPortADDR2", 1),
	Port_Property("x_ce1", 1, hls_out, 0, "ap_memory", "MemPortCE2", 1),
	Port_Property("x_we1", 1, hls_out, 0, "ap_memory", "MemPortWE2", 1),
	Port_Property("x_d1", 32, hls_out, 0, "ap_memory", "MemPortDIN2", 1),
	Port_Property("x_q1", 32, hls_in, 0, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("z_address0", 10, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("z_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("z_we0", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("z_d0", 32, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("z_address1", 10, hls_out, 1, "ap_memory", "MemPortADDR2", 1),
	Port_Property("z_ce1", 1, hls_out, 1, "ap_memory", "MemPortCE2", 1),
	Port_Property("z_we1", 1, hls_out, 1, "ap_memory", "MemPortWE2", 1),
	Port_Property("z_d1", 32, hls_out, 1, "ap_memory", "MemPortDIN2", 1),
	Port_Property("k_address0", 10, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("k_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("k_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("k_d0", 32, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("k_address1", 10, hls_out, 2, "ap_memory", "MemPortADDR2", 1),
	Port_Property("k_ce1", 1, hls_out, 2, "ap_memory", "MemPortCE2", 1),
	Port_Property("k_we1", 1, hls_out, 2, "ap_memory", "MemPortWE2", 1),
	Port_Property("k_d1", 32, hls_out, 2, "ap_memory", "MemPortDIN2", 1),
};
const char* HLS_Design_Meta::dut_name = "key_schedule";
