// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fwht16.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fwht16::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fwht16::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<19> fwht16::ap_ST_fsm_state1 = "1";
const sc_lv<19> fwht16::ap_ST_fsm_state2 = "10";
const sc_lv<19> fwht16::ap_ST_fsm_state3 = "100";
const sc_lv<19> fwht16::ap_ST_fsm_state4 = "1000";
const sc_lv<19> fwht16::ap_ST_fsm_state5 = "10000";
const sc_lv<19> fwht16::ap_ST_fsm_state6 = "100000";
const sc_lv<19> fwht16::ap_ST_fsm_state7 = "1000000";
const sc_lv<19> fwht16::ap_ST_fsm_state8 = "10000000";
const sc_lv<19> fwht16::ap_ST_fsm_state9 = "100000000";
const sc_lv<19> fwht16::ap_ST_fsm_state10 = "1000000000";
const sc_lv<19> fwht16::ap_ST_fsm_state11 = "10000000000";
const sc_lv<19> fwht16::ap_ST_fsm_state12 = "100000000000";
const sc_lv<19> fwht16::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<19> fwht16::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<19> fwht16::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<19> fwht16::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<19> fwht16::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<19> fwht16::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<19> fwht16::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<32> fwht16::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> fwht16::ap_const_lv32_1 = "1";
const sc_lv<1> fwht16::ap_const_lv1_0 = "0";
const sc_lv<32> fwht16::ap_const_lv32_2 = "10";
const sc_lv<32> fwht16::ap_const_lv32_3 = "11";
const sc_lv<32> fwht16::ap_const_lv32_4 = "100";
const sc_lv<32> fwht16::ap_const_lv32_5 = "101";
const sc_lv<32> fwht16::ap_const_lv32_6 = "110";
const sc_lv<32> fwht16::ap_const_lv32_8 = "1000";
const sc_lv<32> fwht16::ap_const_lv32_A = "1010";
const sc_lv<32> fwht16::ap_const_lv32_B = "1011";
const sc_lv<32> fwht16::ap_const_lv32_C = "1100";
const sc_lv<32> fwht16::ap_const_lv32_D = "1101";
const sc_lv<32> fwht16::ap_const_lv32_E = "1110";
const sc_lv<32> fwht16::ap_const_lv32_F = "1111";
const sc_lv<32> fwht16::ap_const_lv32_11 = "10001";
const sc_lv<35> fwht16::ap_const_lv35_0 = "00000000000000000000000000000000000";
const sc_lv<32> fwht16::ap_const_lv32_9 = "1001";
const sc_lv<7> fwht16::ap_const_lv7_0 = "0000000";
const sc_lv<4> fwht16::ap_const_lv4_0 = "0000";
const sc_lv<32> fwht16::ap_const_lv32_12 = "10010";
const sc_lv<1> fwht16::ap_const_lv1_1 = "1";
const sc_lv<32> fwht16::ap_const_lv32_7 = "111";
const sc_lv<32> fwht16::ap_const_lv32_10 = "10000";
const sc_lv<4> fwht16::ap_const_lv4_8 = "1000";
const sc_lv<4> fwht16::ap_const_lv4_1 = "1";
const sc_lv<8> fwht16::ap_const_lv8_1 = "1";
const sc_lv<7> fwht16::ap_const_lv7_8 = "1000";
const sc_lv<8> fwht16::ap_const_lv8_2 = "10";
const sc_lv<8> fwht16::ap_const_lv8_3 = "11";
const sc_lv<8> fwht16::ap_const_lv8_4 = "100";
const sc_lv<8> fwht16::ap_const_lv8_5 = "101";
const sc_lv<8> fwht16::ap_const_lv8_6 = "110";
const sc_lv<8> fwht16::ap_const_lv8_7 = "111";
const sc_lv<6> fwht16::ap_const_lv6_1 = "1";
const sc_lv<6> fwht16::ap_const_lv6_2 = "10";
const sc_lv<6> fwht16::ap_const_lv6_3 = "11";
const sc_lv<6> fwht16::ap_const_lv6_4 = "100";
const sc_lv<6> fwht16::ap_const_lv6_5 = "101";
const sc_lv<6> fwht16::ap_const_lv6_6 = "110";
const sc_lv<6> fwht16::ap_const_lv6_7 = "111";
const sc_lv<2> fwht16::ap_const_lv2_2 = "10";
const sc_lv<6> fwht16::ap_const_lv6_28 = "101000";
const bool fwht16::ap_const_boolean_1 = true;

fwht16::fwht16(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln25_1_fu_382_p2);
    sensitive << ( out_0_rec_reg_298 );

    SC_METHOD(thread_add_ln25_fu_377_p2);
    sensitive << ( sext_ln25_reg_852 );
    sensitive << ( tmp_0_rec_reg_287 );

    SC_METHOD(thread_add_ln27_1_fu_448_p2);
    sensitive << ( block_load_reg_911 );
    sensitive << ( block_load_1_reg_917 );

    SC_METHOD(thread_add_ln27_fu_362_p2);
    sensitive << ( empty_2_fu_358_p1 );

    SC_METHOD(thread_add_ln30_1_fu_398_p2);
    sensitive << ( empty_2_reg_875 );

    SC_METHOD(thread_add_ln30_2_fu_456_p2);
    sensitive << ( block_load_2_reg_933 );
    sensitive << ( block_load_3_reg_939 );

    SC_METHOD(thread_add_ln30_fu_388_p2);
    sensitive << ( empty_2_reg_875 );

    SC_METHOD(thread_add_ln33_1_fu_418_p2);
    sensitive << ( empty_2_reg_875 );

    SC_METHOD(thread_add_ln33_2_fu_464_p2);
    sensitive << ( block_load_4_reg_955 );
    sensitive << ( block_load_5_reg_961 );

    SC_METHOD(thread_add_ln33_fu_408_p2);
    sensitive << ( empty_2_reg_875 );

    SC_METHOD(thread_add_ln36_1_fu_438_p2);
    sensitive << ( empty_2_reg_875 );

    SC_METHOD(thread_add_ln36_2_fu_472_p2);
    sensitive << ( block_load_6_reg_977 );
    sensitive << ( block_load_7_reg_983 );

    SC_METHOD(thread_add_ln36_fu_428_p2);
    sensitive << ( empty_2_reg_875 );

    SC_METHOD(thread_add_ln40_fu_480_p2);
    sensitive << ( add_ln27_1_fu_448_p2 );
    sensitive << ( add_ln30_2_fu_456_p2 );

    SC_METHOD(thread_add_ln43_fu_562_p2);
    sensitive << ( sub_ln28_reg_989 );
    sensitive << ( sub_ln31_reg_995 );

    SC_METHOD(thread_add_ln45_fu_492_p2);
    sensitive << ( add_ln33_2_fu_464_p2 );
    sensitive << ( add_ln36_2_fu_472_p2 );

    SC_METHOD(thread_add_ln48_fu_570_p2);
    sensitive << ( sub_ln34_reg_1001 );
    sensitive << ( sub_ln37_reg_1007 );

    SC_METHOD(thread_add_ln51_fu_504_p2);
    sensitive << ( add_ln40_fu_480_p2 );
    sensitive << ( add_ln45_fu_492_p2 );

    SC_METHOD(thread_add_ln54_fu_543_p2);
    sensitive << ( sub_ln41_reg_1013 );
    sensitive << ( sub_ln46_reg_1019 );

    SC_METHOD(thread_add_ln55_fu_574_p2);
    sensitive << ( sub_ln42_fu_558_p2 );
    sensitive << ( sub_ln47_fu_566_p2 );

    SC_METHOD(thread_add_ln58_fu_623_p2);
    sensitive << ( add_ln43_reg_1025 );
    sensitive << ( add_ln48_reg_1031 );

    SC_METHOD(thread_add_ln65_fu_730_p2);
    sensitive << ( output_block_load_reg_1067 );
    sensitive << ( output_block_load_1_reg_1073 );

    SC_METHOD(thread_add_ln68_fu_738_p2);
    sensitive << ( output_block_load_2_reg_1095 );
    sensitive << ( output_block_load_3_reg_1101 );

    SC_METHOD(thread_add_ln71_1_fu_746_p2);
    sensitive << ( output_block_load_4_reg_1117 );
    sensitive << ( output_block_load_5_reg_1123 );

    SC_METHOD(thread_add_ln71_fu_704_p2);
    sensitive << ( out_1_rec_cast2_reg_1037 );

    SC_METHOD(thread_add_ln74_fu_754_p2);
    sensitive << ( output_block_load_6_reg_1139 );
    sensitive << ( output_block_load_7_reg_1145 );

    SC_METHOD(thread_add_ln78_fu_762_p2);
    sensitive << ( add_ln68_fu_738_p2 );
    sensitive << ( add_ln65_fu_730_p2 );

    SC_METHOD(thread_add_ln81_fu_816_p2);
    sensitive << ( sub_ln66_reg_1151 );
    sensitive << ( sub_ln69_reg_1157 );

    SC_METHOD(thread_add_ln83_fu_774_p2);
    sensitive << ( add_ln74_fu_754_p2 );
    sensitive << ( add_ln71_1_fu_746_p2 );

    SC_METHOD(thread_add_ln86_fu_824_p2);
    sensitive << ( sub_ln72_reg_1163 );
    sensitive << ( sub_ln75_reg_1169 );

    SC_METHOD(thread_add_ln89_fu_786_p2);
    sensitive << ( add_ln83_fu_774_p2 );
    sensitive << ( add_ln78_fu_762_p2 );

    SC_METHOD(thread_add_ln92_fu_806_p2);
    sensitive << ( sub_ln79_fu_768_p2 );
    sensitive << ( sub_ln84_fu_780_p2 );

    SC_METHOD(thread_add_ln93_fu_828_p2);
    sensitive << ( sub_ln85_fu_820_p2 );
    sensitive << ( sub_ln80_fu_812_p2 );

    SC_METHOD(thread_add_ln96_fu_847_p2);
    sensitive << ( add_ln81_reg_1185 );
    sensitive << ( add_ln86_reg_1191 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln63_fu_647_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln63_fu_647_p2 );

    SC_METHOD(thread_block_r_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_0_rec_cast_fu_336_p1 );
    sensitive << ( zext_ln30_fu_393_p1 );
    sensitive << ( zext_ln33_fu_413_p1 );
    sensitive << ( zext_ln36_fu_433_p1 );

    SC_METHOD(thread_block_r_address1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln27_fu_368_p1 );
    sensitive << ( zext_ln30_1_fu_403_p1 );
    sensitive << ( zext_ln33_1_fu_423_p1 );
    sensitive << ( zext_ln36_1_fu_443_p1 );

    SC_METHOD(thread_block_r_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_block_r_ce1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_empty_2_fu_358_p1);
    sensitive << ( tmp_0_rec_reg_287 );

    SC_METHOD(thread_empty_3_fu_373_p1);
    sensitive << ( out_0_rec_reg_298 );

    SC_METHOD(thread_i_1_fu_653_p2);
    sensitive << ( out_1_rec_reg_320 );

    SC_METHOD(thread_i_fu_352_p2);
    sensitive << ( i_0_reg_309 );

    SC_METHOD(thread_icmp_ln25_fu_346_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_309 );

    SC_METHOD(thread_icmp_ln63_fu_647_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( out_1_rec_reg_320 );

    SC_METHOD(thread_or_ln1_fu_691_p3);
    sensitive << ( out_1_rec_reg_320 );

    SC_METHOD(thread_or_ln52_fu_518_p2);
    sensitive << ( empty_3_reg_890 );

    SC_METHOD(thread_or_ln53_fu_533_p2);
    sensitive << ( empty_3_reg_890 );

    SC_METHOD(thread_or_ln54_fu_548_p2);
    sensitive << ( empty_3_reg_890 );

    SC_METHOD(thread_or_ln55_fu_581_p2);
    sensitive << ( empty_3_reg_890 );

    SC_METHOD(thread_or_ln56_fu_598_p2);
    sensitive << ( empty_3_reg_890 );

    SC_METHOD(thread_or_ln57_fu_613_p2);
    sensitive << ( empty_3_reg_890 );

    SC_METHOD(thread_or_ln58_fu_628_p2);
    sensitive << ( empty_3_reg_890 );

    SC_METHOD(thread_or_ln_fu_670_p3);
    sensitive << ( out_1_rec_reg_320 );

    SC_METHOD(thread_out_0_rec_cast_fu_341_p1);
    sensitive << ( out_0_rec_reg_298 );

    SC_METHOD(thread_out_1_rec_cast2_fu_638_p1);
    sensitive << ( out_1_rec_reg_320 );

    SC_METHOD(thread_out_1_rec_cast_fu_642_p1);
    sensitive << ( out_1_rec_reg_320 );

    SC_METHOD(thread_output_block_address0);
    sensitive << ( output_block_addr_reg_857 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( output_block_addr_1_reg_1042 );
    sensitive << ( output_block_addr_9_reg_1061 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( output_block_addr_12_reg_1107 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( output_block_addr_14_reg_1129 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( zext_ln53_fu_538_p1 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln55_fu_586_p1 );
    sensitive << ( zext_ln57_fu_618_p1 );
    sensitive << ( out_1_rec_cast_fu_642_p1 );
    sensitive << ( zext_ln68_fu_678_p1 );
    sensitive << ( zext_ln71_fu_699_p1 );
    sensitive << ( zext_ln74_fu_717_p1 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_output_block_address1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( output_block_addr_10_reg_1084 );
    sensitive << ( output_block_addr_11_reg_1090 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( output_block_addr_13_reg_1112 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( output_block_addr_15_reg_1134 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( zext_ln52_fu_523_p1 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln54_fu_553_p1 );
    sensitive << ( zext_ln56_fu_603_p1 );
    sensitive << ( zext_ln58_fu_633_p1 );
    sensitive << ( zext_ln65_fu_665_p1 );
    sensitive << ( zext_ln68_1_fu_686_p1 );
    sensitive << ( zext_ln71_1_fu_709_p1 );
    sensitive << ( zext_ln74_1_fu_725_p1 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_output_block_ce0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_output_block_ce1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_output_block_d0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( add_ln89_reg_1175 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( add_ln51_fu_504_p2 );
    sensitive << ( sub_ln53_fu_528_p2 );
    sensitive << ( add_ln55_fu_574_p2 );
    sensitive << ( sub_ln57_fu_608_p2 );
    sensitive << ( sub_ln90_fu_792_p2 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( add_ln93_fu_828_p2 );
    sensitive << ( sub_ln95_fu_842_p2 );

    SC_METHOD(thread_output_block_d1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( add_ln92_reg_1180 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( sub_ln52_fu_511_p2 );
    sensitive << ( add_ln54_fu_543_p2 );
    sensitive << ( sub_ln56_fu_591_p2 );
    sensitive << ( add_ln58_fu_623_p2 );
    sensitive << ( sub_ln91_fu_799_p2 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( sub_ln94_fu_835_p2 );
    sensitive << ( add_ln96_fu_847_p2 );

    SC_METHOD(thread_output_block_we0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_output_block_we1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_sext_ln25_fu_332_p1);
    sensitive << ( stride );

    SC_METHOD(thread_sext_ln68_fu_683_p1);
    sensitive << ( xor_ln65_reg_1055 );

    SC_METHOD(thread_sext_ln74_1_fu_722_p1);
    sensitive << ( xor_ln65_reg_1055 );

    SC_METHOD(thread_sext_ln74_fu_714_p1);
    sensitive << ( or_ln_reg_1079 );

    SC_METHOD(thread_sub_ln28_fu_452_p2);
    sensitive << ( block_load_reg_911 );
    sensitive << ( block_load_1_reg_917 );

    SC_METHOD(thread_sub_ln31_fu_460_p2);
    sensitive << ( block_load_2_reg_933 );
    sensitive << ( block_load_3_reg_939 );

    SC_METHOD(thread_sub_ln34_fu_468_p2);
    sensitive << ( block_load_4_reg_955 );
    sensitive << ( block_load_5_reg_961 );

    SC_METHOD(thread_sub_ln37_fu_476_p2);
    sensitive << ( block_load_6_reg_977 );
    sensitive << ( block_load_7_reg_983 );

    SC_METHOD(thread_sub_ln41_fu_486_p2);
    sensitive << ( add_ln27_1_fu_448_p2 );
    sensitive << ( add_ln30_2_fu_456_p2 );

    SC_METHOD(thread_sub_ln42_fu_558_p2);
    sensitive << ( sub_ln28_reg_989 );
    sensitive << ( sub_ln31_reg_995 );

    SC_METHOD(thread_sub_ln46_fu_498_p2);
    sensitive << ( add_ln33_2_fu_464_p2 );
    sensitive << ( add_ln36_2_fu_472_p2 );

    SC_METHOD(thread_sub_ln47_fu_566_p2);
    sensitive << ( sub_ln34_reg_1001 );
    sensitive << ( sub_ln37_reg_1007 );

    SC_METHOD(thread_sub_ln52_fu_511_p2);
    sensitive << ( add_ln40_fu_480_p2 );
    sensitive << ( add_ln45_fu_492_p2 );

    SC_METHOD(thread_sub_ln53_fu_528_p2);
    sensitive << ( sub_ln41_reg_1013 );
    sensitive << ( sub_ln46_reg_1019 );

    SC_METHOD(thread_sub_ln56_fu_591_p2);
    sensitive << ( sub_ln42_fu_558_p2 );
    sensitive << ( sub_ln47_fu_566_p2 );

    SC_METHOD(thread_sub_ln57_fu_608_p2);
    sensitive << ( add_ln43_reg_1025 );
    sensitive << ( add_ln48_reg_1031 );

    SC_METHOD(thread_sub_ln66_fu_734_p2);
    sensitive << ( output_block_load_reg_1067 );
    sensitive << ( output_block_load_1_reg_1073 );

    SC_METHOD(thread_sub_ln69_fu_742_p2);
    sensitive << ( output_block_load_2_reg_1095 );
    sensitive << ( output_block_load_3_reg_1101 );

    SC_METHOD(thread_sub_ln72_fu_750_p2);
    sensitive << ( output_block_load_4_reg_1117 );
    sensitive << ( output_block_load_5_reg_1123 );

    SC_METHOD(thread_sub_ln75_fu_758_p2);
    sensitive << ( output_block_load_6_reg_1139 );
    sensitive << ( output_block_load_7_reg_1145 );

    SC_METHOD(thread_sub_ln79_fu_768_p2);
    sensitive << ( add_ln68_fu_738_p2 );
    sensitive << ( add_ln65_fu_730_p2 );

    SC_METHOD(thread_sub_ln80_fu_812_p2);
    sensitive << ( sub_ln66_reg_1151 );
    sensitive << ( sub_ln69_reg_1157 );

    SC_METHOD(thread_sub_ln84_fu_780_p2);
    sensitive << ( add_ln74_fu_754_p2 );
    sensitive << ( add_ln71_1_fu_746_p2 );

    SC_METHOD(thread_sub_ln85_fu_820_p2);
    sensitive << ( sub_ln72_reg_1163 );
    sensitive << ( sub_ln75_reg_1169 );

    SC_METHOD(thread_sub_ln90_fu_792_p2);
    sensitive << ( add_ln83_fu_774_p2 );
    sensitive << ( add_ln78_fu_762_p2 );

    SC_METHOD(thread_sub_ln91_fu_799_p2);
    sensitive << ( sub_ln79_fu_768_p2 );
    sensitive << ( sub_ln84_fu_780_p2 );

    SC_METHOD(thread_sub_ln94_fu_835_p2);
    sensitive << ( sub_ln85_fu_820_p2 );
    sensitive << ( sub_ln80_fu_812_p2 );

    SC_METHOD(thread_sub_ln95_fu_842_p2);
    sensitive << ( add_ln81_reg_1185 );
    sensitive << ( add_ln86_reg_1191 );

    SC_METHOD(thread_tmp_0_rec_cast_fu_336_p1);
    sensitive << ( tmp_0_rec_reg_287 );

    SC_METHOD(thread_xor_ln65_fu_659_p2);
    sensitive << ( out_1_rec_reg_320 );

    SC_METHOD(thread_zext_ln27_fu_368_p1);
    sensitive << ( add_ln27_fu_362_p2 );

    SC_METHOD(thread_zext_ln30_1_fu_403_p1);
    sensitive << ( add_ln30_1_fu_398_p2 );

    SC_METHOD(thread_zext_ln30_fu_393_p1);
    sensitive << ( add_ln30_fu_388_p2 );

    SC_METHOD(thread_zext_ln33_1_fu_423_p1);
    sensitive << ( add_ln33_1_fu_418_p2 );

    SC_METHOD(thread_zext_ln33_fu_413_p1);
    sensitive << ( add_ln33_fu_408_p2 );

    SC_METHOD(thread_zext_ln36_1_fu_443_p1);
    sensitive << ( add_ln36_1_fu_438_p2 );

    SC_METHOD(thread_zext_ln36_fu_433_p1);
    sensitive << ( add_ln36_fu_428_p2 );

    SC_METHOD(thread_zext_ln52_fu_523_p1);
    sensitive << ( or_ln52_fu_518_p2 );

    SC_METHOD(thread_zext_ln53_fu_538_p1);
    sensitive << ( or_ln53_fu_533_p2 );

    SC_METHOD(thread_zext_ln54_fu_553_p1);
    sensitive << ( or_ln54_fu_548_p2 );

    SC_METHOD(thread_zext_ln55_fu_586_p1);
    sensitive << ( or_ln55_fu_581_p2 );

    SC_METHOD(thread_zext_ln56_fu_603_p1);
    sensitive << ( or_ln56_fu_598_p2 );

    SC_METHOD(thread_zext_ln57_fu_618_p1);
    sensitive << ( or_ln57_fu_613_p2 );

    SC_METHOD(thread_zext_ln58_fu_633_p1);
    sensitive << ( or_ln58_fu_628_p2 );

    SC_METHOD(thread_zext_ln65_fu_665_p1);
    sensitive << ( xor_ln65_fu_659_p2 );

    SC_METHOD(thread_zext_ln68_1_fu_686_p1);
    sensitive << ( sext_ln68_fu_683_p1 );

    SC_METHOD(thread_zext_ln68_fu_678_p1);
    sensitive << ( or_ln_fu_670_p3 );

    SC_METHOD(thread_zext_ln71_1_fu_709_p1);
    sensitive << ( add_ln71_fu_704_p2 );

    SC_METHOD(thread_zext_ln71_fu_699_p1);
    sensitive << ( or_ln1_fu_691_p3 );

    SC_METHOD(thread_zext_ln74_1_fu_725_p1);
    sensitive << ( sext_ln74_1_fu_722_p1 );

    SC_METHOD(thread_zext_ln74_fu_717_p1);
    sensitive << ( sext_ln74_fu_714_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln25_fu_346_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln63_fu_647_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "0000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fwht16_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, block_r_address0, "(port)block_r_address0");
    sc_trace(mVcdFile, block_r_ce0, "(port)block_r_ce0");
    sc_trace(mVcdFile, block_r_q0, "(port)block_r_q0");
    sc_trace(mVcdFile, block_r_address1, "(port)block_r_address1");
    sc_trace(mVcdFile, block_r_ce1, "(port)block_r_ce1");
    sc_trace(mVcdFile, block_r_q1, "(port)block_r_q1");
    sc_trace(mVcdFile, output_block_address0, "(port)output_block_address0");
    sc_trace(mVcdFile, output_block_ce0, "(port)output_block_ce0");
    sc_trace(mVcdFile, output_block_we0, "(port)output_block_we0");
    sc_trace(mVcdFile, output_block_d0, "(port)output_block_d0");
    sc_trace(mVcdFile, output_block_q0, "(port)output_block_q0");
    sc_trace(mVcdFile, output_block_address1, "(port)output_block_address1");
    sc_trace(mVcdFile, output_block_ce1, "(port)output_block_ce1");
    sc_trace(mVcdFile, output_block_we1, "(port)output_block_we1");
    sc_trace(mVcdFile, output_block_d1, "(port)output_block_d1");
    sc_trace(mVcdFile, output_block_q1, "(port)output_block_q1");
    sc_trace(mVcdFile, stride, "(port)stride");
    sc_trace(mVcdFile, intra, "(port)intra");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, sext_ln25_fu_332_p1, "sext_ln25_fu_332_p1");
    sc_trace(mVcdFile, sext_ln25_reg_852, "sext_ln25_reg_852");
    sc_trace(mVcdFile, output_block_addr_reg_857, "output_block_addr_reg_857");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_fu_352_p2, "i_fu_352_p2");
    sc_trace(mVcdFile, i_reg_870, "i_reg_870");
    sc_trace(mVcdFile, empty_2_fu_358_p1, "empty_2_fu_358_p1");
    sc_trace(mVcdFile, empty_2_reg_875, "empty_2_reg_875");
    sc_trace(mVcdFile, icmp_ln25_fu_346_p2, "icmp_ln25_fu_346_p2");
    sc_trace(mVcdFile, empty_3_fu_373_p1, "empty_3_fu_373_p1");
    sc_trace(mVcdFile, empty_3_reg_890, "empty_3_reg_890");
    sc_trace(mVcdFile, add_ln25_fu_377_p2, "add_ln25_fu_377_p2");
    sc_trace(mVcdFile, add_ln25_reg_901, "add_ln25_reg_901");
    sc_trace(mVcdFile, add_ln25_1_fu_382_p2, "add_ln25_1_fu_382_p2");
    sc_trace(mVcdFile, add_ln25_1_reg_906, "add_ln25_1_reg_906");
    sc_trace(mVcdFile, block_load_reg_911, "block_load_reg_911");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, block_load_1_reg_917, "block_load_1_reg_917");
    sc_trace(mVcdFile, block_load_2_reg_933, "block_load_2_reg_933");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, block_load_3_reg_939, "block_load_3_reg_939");
    sc_trace(mVcdFile, block_load_4_reg_955, "block_load_4_reg_955");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, block_load_5_reg_961, "block_load_5_reg_961");
    sc_trace(mVcdFile, block_load_6_reg_977, "block_load_6_reg_977");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, block_load_7_reg_983, "block_load_7_reg_983");
    sc_trace(mVcdFile, sub_ln28_fu_452_p2, "sub_ln28_fu_452_p2");
    sc_trace(mVcdFile, sub_ln28_reg_989, "sub_ln28_reg_989");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, sub_ln31_fu_460_p2, "sub_ln31_fu_460_p2");
    sc_trace(mVcdFile, sub_ln31_reg_995, "sub_ln31_reg_995");
    sc_trace(mVcdFile, sub_ln34_fu_468_p2, "sub_ln34_fu_468_p2");
    sc_trace(mVcdFile, sub_ln34_reg_1001, "sub_ln34_reg_1001");
    sc_trace(mVcdFile, sub_ln37_fu_476_p2, "sub_ln37_fu_476_p2");
    sc_trace(mVcdFile, sub_ln37_reg_1007, "sub_ln37_reg_1007");
    sc_trace(mVcdFile, sub_ln41_fu_486_p2, "sub_ln41_fu_486_p2");
    sc_trace(mVcdFile, sub_ln41_reg_1013, "sub_ln41_reg_1013");
    sc_trace(mVcdFile, sub_ln46_fu_498_p2, "sub_ln46_fu_498_p2");
    sc_trace(mVcdFile, sub_ln46_reg_1019, "sub_ln46_reg_1019");
    sc_trace(mVcdFile, add_ln43_fu_562_p2, "add_ln43_fu_562_p2");
    sc_trace(mVcdFile, add_ln43_reg_1025, "add_ln43_reg_1025");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, add_ln48_fu_570_p2, "add_ln48_fu_570_p2");
    sc_trace(mVcdFile, add_ln48_reg_1031, "add_ln48_reg_1031");
    sc_trace(mVcdFile, out_1_rec_cast2_fu_638_p1, "out_1_rec_cast2_fu_638_p1");
    sc_trace(mVcdFile, out_1_rec_cast2_reg_1037, "out_1_rec_cast2_reg_1037");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, output_block_addr_1_reg_1042, "output_block_addr_1_reg_1042");
    sc_trace(mVcdFile, i_1_fu_653_p2, "i_1_fu_653_p2");
    sc_trace(mVcdFile, i_1_reg_1050, "i_1_reg_1050");
    sc_trace(mVcdFile, xor_ln65_fu_659_p2, "xor_ln65_fu_659_p2");
    sc_trace(mVcdFile, xor_ln65_reg_1055, "xor_ln65_reg_1055");
    sc_trace(mVcdFile, icmp_ln63_fu_647_p2, "icmp_ln63_fu_647_p2");
    sc_trace(mVcdFile, output_block_addr_9_reg_1061, "output_block_addr_9_reg_1061");
    sc_trace(mVcdFile, output_block_load_reg_1067, "output_block_load_reg_1067");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, output_block_load_1_reg_1073, "output_block_load_1_reg_1073");
    sc_trace(mVcdFile, or_ln_fu_670_p3, "or_ln_fu_670_p3");
    sc_trace(mVcdFile, or_ln_reg_1079, "or_ln_reg_1079");
    sc_trace(mVcdFile, output_block_addr_10_reg_1084, "output_block_addr_10_reg_1084");
    sc_trace(mVcdFile, output_block_addr_11_reg_1090, "output_block_addr_11_reg_1090");
    sc_trace(mVcdFile, output_block_load_2_reg_1095, "output_block_load_2_reg_1095");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, output_block_load_3_reg_1101, "output_block_load_3_reg_1101");
    sc_trace(mVcdFile, output_block_addr_12_reg_1107, "output_block_addr_12_reg_1107");
    sc_trace(mVcdFile, output_block_addr_13_reg_1112, "output_block_addr_13_reg_1112");
    sc_trace(mVcdFile, output_block_load_4_reg_1117, "output_block_load_4_reg_1117");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, output_block_load_5_reg_1123, "output_block_load_5_reg_1123");
    sc_trace(mVcdFile, output_block_addr_14_reg_1129, "output_block_addr_14_reg_1129");
    sc_trace(mVcdFile, output_block_addr_15_reg_1134, "output_block_addr_15_reg_1134");
    sc_trace(mVcdFile, output_block_load_6_reg_1139, "output_block_load_6_reg_1139");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, output_block_load_7_reg_1145, "output_block_load_7_reg_1145");
    sc_trace(mVcdFile, sub_ln66_fu_734_p2, "sub_ln66_fu_734_p2");
    sc_trace(mVcdFile, sub_ln66_reg_1151, "sub_ln66_reg_1151");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, sub_ln69_fu_742_p2, "sub_ln69_fu_742_p2");
    sc_trace(mVcdFile, sub_ln69_reg_1157, "sub_ln69_reg_1157");
    sc_trace(mVcdFile, sub_ln72_fu_750_p2, "sub_ln72_fu_750_p2");
    sc_trace(mVcdFile, sub_ln72_reg_1163, "sub_ln72_reg_1163");
    sc_trace(mVcdFile, sub_ln75_fu_758_p2, "sub_ln75_fu_758_p2");
    sc_trace(mVcdFile, sub_ln75_reg_1169, "sub_ln75_reg_1169");
    sc_trace(mVcdFile, add_ln89_fu_786_p2, "add_ln89_fu_786_p2");
    sc_trace(mVcdFile, add_ln89_reg_1175, "add_ln89_reg_1175");
    sc_trace(mVcdFile, add_ln92_fu_806_p2, "add_ln92_fu_806_p2");
    sc_trace(mVcdFile, add_ln92_reg_1180, "add_ln92_reg_1180");
    sc_trace(mVcdFile, add_ln81_fu_816_p2, "add_ln81_fu_816_p2");
    sc_trace(mVcdFile, add_ln81_reg_1185, "add_ln81_reg_1185");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, add_ln86_fu_824_p2, "add_ln86_fu_824_p2");
    sc_trace(mVcdFile, add_ln86_reg_1191, "add_ln86_reg_1191");
    sc_trace(mVcdFile, tmp_0_rec_reg_287, "tmp_0_rec_reg_287");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, out_0_rec_reg_298, "out_0_rec_reg_298");
    sc_trace(mVcdFile, i_0_reg_309, "i_0_reg_309");
    sc_trace(mVcdFile, out_1_rec_reg_320, "out_1_rec_reg_320");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, out_0_rec_cast_fu_341_p1, "out_0_rec_cast_fu_341_p1");
    sc_trace(mVcdFile, tmp_0_rec_cast_fu_336_p1, "tmp_0_rec_cast_fu_336_p1");
    sc_trace(mVcdFile, zext_ln27_fu_368_p1, "zext_ln27_fu_368_p1");
    sc_trace(mVcdFile, zext_ln30_fu_393_p1, "zext_ln30_fu_393_p1");
    sc_trace(mVcdFile, zext_ln30_1_fu_403_p1, "zext_ln30_1_fu_403_p1");
    sc_trace(mVcdFile, zext_ln33_fu_413_p1, "zext_ln33_fu_413_p1");
    sc_trace(mVcdFile, zext_ln33_1_fu_423_p1, "zext_ln33_1_fu_423_p1");
    sc_trace(mVcdFile, zext_ln36_fu_433_p1, "zext_ln36_fu_433_p1");
    sc_trace(mVcdFile, zext_ln36_1_fu_443_p1, "zext_ln36_1_fu_443_p1");
    sc_trace(mVcdFile, zext_ln52_fu_523_p1, "zext_ln52_fu_523_p1");
    sc_trace(mVcdFile, zext_ln53_fu_538_p1, "zext_ln53_fu_538_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, zext_ln54_fu_553_p1, "zext_ln54_fu_553_p1");
    sc_trace(mVcdFile, zext_ln55_fu_586_p1, "zext_ln55_fu_586_p1");
    sc_trace(mVcdFile, zext_ln56_fu_603_p1, "zext_ln56_fu_603_p1");
    sc_trace(mVcdFile, zext_ln57_fu_618_p1, "zext_ln57_fu_618_p1");
    sc_trace(mVcdFile, zext_ln58_fu_633_p1, "zext_ln58_fu_633_p1");
    sc_trace(mVcdFile, out_1_rec_cast_fu_642_p1, "out_1_rec_cast_fu_642_p1");
    sc_trace(mVcdFile, zext_ln65_fu_665_p1, "zext_ln65_fu_665_p1");
    sc_trace(mVcdFile, zext_ln68_fu_678_p1, "zext_ln68_fu_678_p1");
    sc_trace(mVcdFile, zext_ln68_1_fu_686_p1, "zext_ln68_1_fu_686_p1");
    sc_trace(mVcdFile, zext_ln71_fu_699_p1, "zext_ln71_fu_699_p1");
    sc_trace(mVcdFile, zext_ln71_1_fu_709_p1, "zext_ln71_1_fu_709_p1");
    sc_trace(mVcdFile, zext_ln74_fu_717_p1, "zext_ln74_fu_717_p1");
    sc_trace(mVcdFile, zext_ln74_1_fu_725_p1, "zext_ln74_1_fu_725_p1");
    sc_trace(mVcdFile, add_ln51_fu_504_p2, "add_ln51_fu_504_p2");
    sc_trace(mVcdFile, sub_ln52_fu_511_p2, "sub_ln52_fu_511_p2");
    sc_trace(mVcdFile, sub_ln53_fu_528_p2, "sub_ln53_fu_528_p2");
    sc_trace(mVcdFile, add_ln54_fu_543_p2, "add_ln54_fu_543_p2");
    sc_trace(mVcdFile, add_ln55_fu_574_p2, "add_ln55_fu_574_p2");
    sc_trace(mVcdFile, sub_ln56_fu_591_p2, "sub_ln56_fu_591_p2");
    sc_trace(mVcdFile, sub_ln57_fu_608_p2, "sub_ln57_fu_608_p2");
    sc_trace(mVcdFile, add_ln58_fu_623_p2, "add_ln58_fu_623_p2");
    sc_trace(mVcdFile, sub_ln90_fu_792_p2, "sub_ln90_fu_792_p2");
    sc_trace(mVcdFile, sub_ln91_fu_799_p2, "sub_ln91_fu_799_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, add_ln93_fu_828_p2, "add_ln93_fu_828_p2");
    sc_trace(mVcdFile, sub_ln94_fu_835_p2, "sub_ln94_fu_835_p2");
    sc_trace(mVcdFile, sub_ln95_fu_842_p2, "sub_ln95_fu_842_p2");
    sc_trace(mVcdFile, add_ln96_fu_847_p2, "add_ln96_fu_847_p2");
    sc_trace(mVcdFile, add_ln27_fu_362_p2, "add_ln27_fu_362_p2");
    sc_trace(mVcdFile, add_ln30_fu_388_p2, "add_ln30_fu_388_p2");
    sc_trace(mVcdFile, add_ln30_1_fu_398_p2, "add_ln30_1_fu_398_p2");
    sc_trace(mVcdFile, add_ln33_fu_408_p2, "add_ln33_fu_408_p2");
    sc_trace(mVcdFile, add_ln33_1_fu_418_p2, "add_ln33_1_fu_418_p2");
    sc_trace(mVcdFile, add_ln36_fu_428_p2, "add_ln36_fu_428_p2");
    sc_trace(mVcdFile, add_ln36_1_fu_438_p2, "add_ln36_1_fu_438_p2");
    sc_trace(mVcdFile, add_ln27_1_fu_448_p2, "add_ln27_1_fu_448_p2");
    sc_trace(mVcdFile, add_ln30_2_fu_456_p2, "add_ln30_2_fu_456_p2");
    sc_trace(mVcdFile, add_ln33_2_fu_464_p2, "add_ln33_2_fu_464_p2");
    sc_trace(mVcdFile, add_ln36_2_fu_472_p2, "add_ln36_2_fu_472_p2");
    sc_trace(mVcdFile, add_ln40_fu_480_p2, "add_ln40_fu_480_p2");
    sc_trace(mVcdFile, add_ln45_fu_492_p2, "add_ln45_fu_492_p2");
    sc_trace(mVcdFile, or_ln52_fu_518_p2, "or_ln52_fu_518_p2");
    sc_trace(mVcdFile, or_ln53_fu_533_p2, "or_ln53_fu_533_p2");
    sc_trace(mVcdFile, or_ln54_fu_548_p2, "or_ln54_fu_548_p2");
    sc_trace(mVcdFile, sub_ln42_fu_558_p2, "sub_ln42_fu_558_p2");
    sc_trace(mVcdFile, sub_ln47_fu_566_p2, "sub_ln47_fu_566_p2");
    sc_trace(mVcdFile, or_ln55_fu_581_p2, "or_ln55_fu_581_p2");
    sc_trace(mVcdFile, or_ln56_fu_598_p2, "or_ln56_fu_598_p2");
    sc_trace(mVcdFile, or_ln57_fu_613_p2, "or_ln57_fu_613_p2");
    sc_trace(mVcdFile, or_ln58_fu_628_p2, "or_ln58_fu_628_p2");
    sc_trace(mVcdFile, sext_ln68_fu_683_p1, "sext_ln68_fu_683_p1");
    sc_trace(mVcdFile, or_ln1_fu_691_p3, "or_ln1_fu_691_p3");
    sc_trace(mVcdFile, add_ln71_fu_704_p2, "add_ln71_fu_704_p2");
    sc_trace(mVcdFile, sext_ln74_fu_714_p1, "sext_ln74_fu_714_p1");
    sc_trace(mVcdFile, sext_ln74_1_fu_722_p1, "sext_ln74_1_fu_722_p1");
    sc_trace(mVcdFile, add_ln68_fu_738_p2, "add_ln68_fu_738_p2");
    sc_trace(mVcdFile, add_ln65_fu_730_p2, "add_ln65_fu_730_p2");
    sc_trace(mVcdFile, add_ln74_fu_754_p2, "add_ln74_fu_754_p2");
    sc_trace(mVcdFile, add_ln71_1_fu_746_p2, "add_ln71_1_fu_746_p2");
    sc_trace(mVcdFile, add_ln83_fu_774_p2, "add_ln83_fu_774_p2");
    sc_trace(mVcdFile, add_ln78_fu_762_p2, "add_ln78_fu_762_p2");
    sc_trace(mVcdFile, sub_ln79_fu_768_p2, "sub_ln79_fu_768_p2");
    sc_trace(mVcdFile, sub_ln84_fu_780_p2, "sub_ln84_fu_780_p2");
    sc_trace(mVcdFile, sub_ln85_fu_820_p2, "sub_ln85_fu_820_p2");
    sc_trace(mVcdFile, sub_ln80_fu_812_p2, "sub_ln80_fu_812_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("fwht16.hdltvin.dat");
    mHdltvoutHandle.open("fwht16.hdltvout.dat");
}

fwht16::~fwht16() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void fwht16::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        i_0_reg_309 = i_reg_870.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_309 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        out_0_rec_reg_298 = add_ln25_1_reg_906.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        out_0_rec_reg_298 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln25_fu_346_p2.read(), ap_const_lv1_1))) {
        out_1_rec_reg_320 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        out_1_rec_reg_320 = i_1_reg_1050.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        tmp_0_rec_reg_287 = add_ln25_reg_901.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        tmp_0_rec_reg_287 = ap_const_lv35_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln25_fu_346_p2.read(), ap_const_lv1_0))) {
        add_ln25_1_reg_906 = add_ln25_1_fu_382_p2.read();
        add_ln25_reg_901 = add_ln25_fu_377_p2.read();
        empty_2_reg_875 = empty_2_fu_358_p1.read();
        empty_3_reg_890 = empty_3_fu_373_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        add_ln43_reg_1025 = add_ln43_fu_562_p2.read();
        add_ln48_reg_1031 = add_ln48_fu_570_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        add_ln81_reg_1185 = add_ln81_fu_816_p2.read();
        add_ln86_reg_1191 = add_ln86_fu_824_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        add_ln89_reg_1175 = add_ln89_fu_786_p2.read();
        add_ln92_reg_1180 = add_ln92_fu_806_p2.read();
        sub_ln66_reg_1151 = sub_ln66_fu_734_p2.read();
        sub_ln69_reg_1157 = sub_ln69_fu_742_p2.read();
        sub_ln72_reg_1163 = sub_ln72_fu_750_p2.read();
        sub_ln75_reg_1169 = sub_ln75_fu_758_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        block_load_1_reg_917 = block_r_q1.read();
        block_load_reg_911 = block_r_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        block_load_2_reg_933 = block_r_q0.read();
        block_load_3_reg_939 = block_r_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        block_load_4_reg_955 = block_r_q0.read();
        block_load_5_reg_961 = block_r_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        block_load_6_reg_977 = block_r_q0.read();
        block_load_7_reg_983 = block_r_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        i_1_reg_1050 = i_1_fu_653_p2.read();
        out_1_rec_cast2_reg_1037 = out_1_rec_cast2_fu_638_p1.read();
        output_block_addr_1_reg_1042 =  (sc_lv<7>) (out_1_rec_cast_fu_642_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_870 = i_fu_352_p2.read();
        output_block_addr_reg_857 =  (sc_lv<7>) (out_0_rec_cast_fu_341_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        or_ln_reg_1079 = or_ln_fu_670_p3.read();
        output_block_addr_10_reg_1084 =  (sc_lv<7>) (zext_ln68_fu_678_p1.read());
        output_block_addr_11_reg_1090 =  (sc_lv<7>) (zext_ln68_1_fu_686_p1.read());
        output_block_load_1_reg_1073 = output_block_q1.read();
        output_block_load_reg_1067 = output_block_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        output_block_addr_12_reg_1107 =  (sc_lv<7>) (zext_ln71_fu_699_p1.read());
        output_block_addr_13_reg_1112 =  (sc_lv<7>) (zext_ln71_1_fu_709_p1.read());
        output_block_load_2_reg_1095 = output_block_q0.read();
        output_block_load_3_reg_1101 = output_block_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        output_block_addr_14_reg_1129 =  (sc_lv<7>) (zext_ln74_fu_717_p1.read());
        output_block_addr_15_reg_1134 =  (sc_lv<7>) (zext_ln74_1_fu_725_p1.read());
        output_block_load_4_reg_1117 = output_block_q0.read();
        output_block_load_5_reg_1123 = output_block_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln63_fu_647_p2.read()))) {
        output_block_addr_9_reg_1061 =  (sc_lv<7>) (zext_ln65_fu_665_p1.read());
        xor_ln65_reg_1055 = xor_ln65_fu_659_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        output_block_load_6_reg_1139 = output_block_q0.read();
        output_block_load_7_reg_1145 = output_block_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        sext_ln25_reg_852 = sext_ln25_fu_332_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        sub_ln28_reg_989 = sub_ln28_fu_452_p2.read();
        sub_ln31_reg_995 = sub_ln31_fu_460_p2.read();
        sub_ln34_reg_1001 = sub_ln34_fu_468_p2.read();
        sub_ln37_reg_1007 = sub_ln37_fu_476_p2.read();
        sub_ln41_reg_1013 = sub_ln41_fu_486_p2.read();
        sub_ln46_reg_1019 = sub_ln46_fu_498_p2.read();
    }
}

void fwht16::thread_add_ln25_1_fu_382_p2() {
    add_ln25_1_fu_382_p2 = (!ap_const_lv7_8.is_01() || !out_0_rec_reg_298.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_8) + sc_biguint<7>(out_0_rec_reg_298.read()));
}

void fwht16::thread_add_ln25_fu_377_p2() {
    add_ln25_fu_377_p2 = (!tmp_0_rec_reg_287.read().is_01() || !sext_ln25_reg_852.read().is_01())? sc_lv<35>(): (sc_bigint<35>(tmp_0_rec_reg_287.read()) + sc_bigint<35>(sext_ln25_reg_852.read()));
}

void fwht16::thread_add_ln27_1_fu_448_p2() {
    add_ln27_1_fu_448_p2 = (!block_load_reg_911.read().is_01() || !block_load_1_reg_917.read().is_01())? sc_lv<32>(): (sc_biguint<32>(block_load_reg_911.read()) + sc_biguint<32>(block_load_1_reg_917.read()));
}

void fwht16::thread_add_ln27_fu_362_p2() {
    add_ln27_fu_362_p2 = (!ap_const_lv8_1.is_01() || !empty_2_fu_358_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_1) + sc_biguint<8>(empty_2_fu_358_p1.read()));
}

void fwht16::thread_add_ln30_1_fu_398_p2() {
    add_ln30_1_fu_398_p2 = (!ap_const_lv8_3.is_01() || !empty_2_reg_875.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_3) + sc_biguint<8>(empty_2_reg_875.read()));
}

void fwht16::thread_add_ln30_2_fu_456_p2() {
    add_ln30_2_fu_456_p2 = (!block_load_2_reg_933.read().is_01() || !block_load_3_reg_939.read().is_01())? sc_lv<32>(): (sc_biguint<32>(block_load_2_reg_933.read()) + sc_biguint<32>(block_load_3_reg_939.read()));
}

void fwht16::thread_add_ln30_fu_388_p2() {
    add_ln30_fu_388_p2 = (!ap_const_lv8_2.is_01() || !empty_2_reg_875.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_2) + sc_biguint<8>(empty_2_reg_875.read()));
}

void fwht16::thread_add_ln33_1_fu_418_p2() {
    add_ln33_1_fu_418_p2 = (!ap_const_lv8_5.is_01() || !empty_2_reg_875.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_5) + sc_biguint<8>(empty_2_reg_875.read()));
}

void fwht16::thread_add_ln33_2_fu_464_p2() {
    add_ln33_2_fu_464_p2 = (!block_load_4_reg_955.read().is_01() || !block_load_5_reg_961.read().is_01())? sc_lv<32>(): (sc_biguint<32>(block_load_4_reg_955.read()) + sc_biguint<32>(block_load_5_reg_961.read()));
}

void fwht16::thread_add_ln33_fu_408_p2() {
    add_ln33_fu_408_p2 = (!ap_const_lv8_4.is_01() || !empty_2_reg_875.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_4) + sc_biguint<8>(empty_2_reg_875.read()));
}

void fwht16::thread_add_ln36_1_fu_438_p2() {
    add_ln36_1_fu_438_p2 = (!ap_const_lv8_7.is_01() || !empty_2_reg_875.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_7) + sc_biguint<8>(empty_2_reg_875.read()));
}

void fwht16::thread_add_ln36_2_fu_472_p2() {
    add_ln36_2_fu_472_p2 = (!block_load_6_reg_977.read().is_01() || !block_load_7_reg_983.read().is_01())? sc_lv<32>(): (sc_biguint<32>(block_load_6_reg_977.read()) + sc_biguint<32>(block_load_7_reg_983.read()));
}

void fwht16::thread_add_ln36_fu_428_p2() {
    add_ln36_fu_428_p2 = (!ap_const_lv8_6.is_01() || !empty_2_reg_875.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_6) + sc_biguint<8>(empty_2_reg_875.read()));
}

void fwht16::thread_add_ln40_fu_480_p2() {
    add_ln40_fu_480_p2 = (!add_ln27_1_fu_448_p2.read().is_01() || !add_ln30_2_fu_456_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln27_1_fu_448_p2.read()) + sc_biguint<32>(add_ln30_2_fu_456_p2.read()));
}

void fwht16::thread_add_ln43_fu_562_p2() {
    add_ln43_fu_562_p2 = (!sub_ln28_reg_989.read().is_01() || !sub_ln31_reg_995.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln28_reg_989.read()) + sc_biguint<32>(sub_ln31_reg_995.read()));
}

void fwht16::thread_add_ln45_fu_492_p2() {
    add_ln45_fu_492_p2 = (!add_ln33_2_fu_464_p2.read().is_01() || !add_ln36_2_fu_472_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln33_2_fu_464_p2.read()) + sc_biguint<32>(add_ln36_2_fu_472_p2.read()));
}

void fwht16::thread_add_ln48_fu_570_p2() {
    add_ln48_fu_570_p2 = (!sub_ln34_reg_1001.read().is_01() || !sub_ln37_reg_1007.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln34_reg_1001.read()) + sc_biguint<32>(sub_ln37_reg_1007.read()));
}

void fwht16::thread_add_ln51_fu_504_p2() {
    add_ln51_fu_504_p2 = (!add_ln40_fu_480_p2.read().is_01() || !add_ln45_fu_492_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln40_fu_480_p2.read()) + sc_biguint<32>(add_ln45_fu_492_p2.read()));
}

void fwht16::thread_add_ln54_fu_543_p2() {
    add_ln54_fu_543_p2 = (!sub_ln41_reg_1013.read().is_01() || !sub_ln46_reg_1019.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln41_reg_1013.read()) + sc_biguint<32>(sub_ln46_reg_1019.read()));
}

void fwht16::thread_add_ln55_fu_574_p2() {
    add_ln55_fu_574_p2 = (!sub_ln42_fu_558_p2.read().is_01() || !sub_ln47_fu_566_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln42_fu_558_p2.read()) + sc_biguint<32>(sub_ln47_fu_566_p2.read()));
}

void fwht16::thread_add_ln58_fu_623_p2() {
    add_ln58_fu_623_p2 = (!add_ln43_reg_1025.read().is_01() || !add_ln48_reg_1031.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln43_reg_1025.read()) + sc_biguint<32>(add_ln48_reg_1031.read()));
}

void fwht16::thread_add_ln65_fu_730_p2() {
    add_ln65_fu_730_p2 = (!output_block_load_1_reg_1073.read().is_01() || !output_block_load_reg_1067.read().is_01())? sc_lv<32>(): (sc_biguint<32>(output_block_load_1_reg_1073.read()) + sc_biguint<32>(output_block_load_reg_1067.read()));
}

void fwht16::thread_add_ln68_fu_738_p2() {
    add_ln68_fu_738_p2 = (!output_block_load_3_reg_1101.read().is_01() || !output_block_load_2_reg_1095.read().is_01())? sc_lv<32>(): (sc_biguint<32>(output_block_load_3_reg_1101.read()) + sc_biguint<32>(output_block_load_2_reg_1095.read()));
}

void fwht16::thread_add_ln71_1_fu_746_p2() {
    add_ln71_1_fu_746_p2 = (!output_block_load_5_reg_1123.read().is_01() || !output_block_load_4_reg_1117.read().is_01())? sc_lv<32>(): (sc_biguint<32>(output_block_load_5_reg_1123.read()) + sc_biguint<32>(output_block_load_4_reg_1117.read()));
}

void fwht16::thread_add_ln71_fu_704_p2() {
    add_ln71_fu_704_p2 = (!out_1_rec_cast2_reg_1037.read().is_01() || !ap_const_lv6_28.is_01())? sc_lv<6>(): (sc_biguint<6>(out_1_rec_cast2_reg_1037.read()) + sc_bigint<6>(ap_const_lv6_28));
}

void fwht16::thread_add_ln74_fu_754_p2() {
    add_ln74_fu_754_p2 = (!output_block_load_7_reg_1145.read().is_01() || !output_block_load_6_reg_1139.read().is_01())? sc_lv<32>(): (sc_biguint<32>(output_block_load_7_reg_1145.read()) + sc_biguint<32>(output_block_load_6_reg_1139.read()));
}

void fwht16::thread_add_ln78_fu_762_p2() {
    add_ln78_fu_762_p2 = (!add_ln68_fu_738_p2.read().is_01() || !add_ln65_fu_730_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln68_fu_738_p2.read()) + sc_biguint<32>(add_ln65_fu_730_p2.read()));
}

void fwht16::thread_add_ln81_fu_816_p2() {
    add_ln81_fu_816_p2 = (!sub_ln69_reg_1157.read().is_01() || !sub_ln66_reg_1151.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln69_reg_1157.read()) + sc_biguint<32>(sub_ln66_reg_1151.read()));
}

void fwht16::thread_add_ln83_fu_774_p2() {
    add_ln83_fu_774_p2 = (!add_ln74_fu_754_p2.read().is_01() || !add_ln71_1_fu_746_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln74_fu_754_p2.read()) + sc_biguint<32>(add_ln71_1_fu_746_p2.read()));
}

void fwht16::thread_add_ln86_fu_824_p2() {
    add_ln86_fu_824_p2 = (!sub_ln75_reg_1169.read().is_01() || !sub_ln72_reg_1163.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln75_reg_1169.read()) + sc_biguint<32>(sub_ln72_reg_1163.read()));
}

void fwht16::thread_add_ln89_fu_786_p2() {
    add_ln89_fu_786_p2 = (!add_ln83_fu_774_p2.read().is_01() || !add_ln78_fu_762_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln83_fu_774_p2.read()) + sc_biguint<32>(add_ln78_fu_762_p2.read()));
}

void fwht16::thread_add_ln92_fu_806_p2() {
    add_ln92_fu_806_p2 = (!sub_ln84_fu_780_p2.read().is_01() || !sub_ln79_fu_768_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln84_fu_780_p2.read()) + sc_biguint<32>(sub_ln79_fu_768_p2.read()));
}

void fwht16::thread_add_ln93_fu_828_p2() {
    add_ln93_fu_828_p2 = (!sub_ln85_fu_820_p2.read().is_01() || !sub_ln80_fu_812_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln85_fu_820_p2.read()) + sc_biguint<32>(sub_ln80_fu_812_p2.read()));
}

void fwht16::thread_add_ln96_fu_847_p2() {
    add_ln96_fu_847_p2 = (!add_ln86_reg_1191.read().is_01() || !add_ln81_reg_1185.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln86_reg_1191.read()) + sc_biguint<32>(add_ln81_reg_1185.read()));
}

void fwht16::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void fwht16::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void fwht16::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void fwht16::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void fwht16::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void fwht16::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void fwht16::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void fwht16::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void fwht16::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void fwht16::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void fwht16::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void fwht16::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void fwht16::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void fwht16::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void fwht16::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void fwht16::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void fwht16::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void fwht16::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void fwht16::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void fwht16::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(icmp_ln63_fu_647_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void fwht16::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void fwht16::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(icmp_ln63_fu_647_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void fwht16::thread_block_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        block_r_address0 =  (sc_lv<7>) (zext_ln36_fu_433_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        block_r_address0 =  (sc_lv<7>) (zext_ln33_fu_413_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        block_r_address0 =  (sc_lv<7>) (zext_ln30_fu_393_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        block_r_address0 =  (sc_lv<7>) (tmp_0_rec_cast_fu_336_p1.read());
    } else {
        block_r_address0 = "XXXXXXX";
    }
}

void fwht16::thread_block_r_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        block_r_address1 =  (sc_lv<7>) (zext_ln36_1_fu_443_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        block_r_address1 =  (sc_lv<7>) (zext_ln33_1_fu_423_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        block_r_address1 =  (sc_lv<7>) (zext_ln30_1_fu_403_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        block_r_address1 =  (sc_lv<7>) (zext_ln27_fu_368_p1.read());
    } else {
        block_r_address1 = "XXXXXXX";
    }
}

void fwht16::thread_block_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        block_r_ce0 = ap_const_logic_1;
    } else {
        block_r_ce0 = ap_const_logic_0;
    }
}

void fwht16::thread_block_r_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        block_r_ce1 = ap_const_logic_1;
    } else {
        block_r_ce1 = ap_const_logic_0;
    }
}

void fwht16::thread_empty_2_fu_358_p1() {
    empty_2_fu_358_p1 = tmp_0_rec_reg_287.read().range(8-1, 0);
}

void fwht16::thread_empty_3_fu_373_p1() {
    empty_3_fu_373_p1 = out_0_rec_reg_298.read().range(6-1, 0);
}

void fwht16::thread_i_1_fu_653_p2() {
    i_1_fu_653_p2 = (!out_1_rec_reg_320.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(out_1_rec_reg_320.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void fwht16::thread_i_fu_352_p2() {
    i_fu_352_p2 = (!i_0_reg_309.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_reg_309.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void fwht16::thread_icmp_ln25_fu_346_p2() {
    icmp_ln25_fu_346_p2 = (!i_0_reg_309.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_309.read() == ap_const_lv4_8);
}

void fwht16::thread_icmp_ln63_fu_647_p2() {
    icmp_ln63_fu_647_p2 = (!out_1_rec_reg_320.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(out_1_rec_reg_320.read() == ap_const_lv4_8);
}

void fwht16::thread_or_ln1_fu_691_p3() {
    or_ln1_fu_691_p3 = esl_concat<2,4>(ap_const_lv2_2, out_1_rec_reg_320.read());
}

void fwht16::thread_or_ln52_fu_518_p2() {
    or_ln52_fu_518_p2 = (empty_3_reg_890.read() | ap_const_lv6_1);
}

void fwht16::thread_or_ln53_fu_533_p2() {
    or_ln53_fu_533_p2 = (empty_3_reg_890.read() | ap_const_lv6_2);
}

void fwht16::thread_or_ln54_fu_548_p2() {
    or_ln54_fu_548_p2 = (empty_3_reg_890.read() | ap_const_lv6_3);
}

void fwht16::thread_or_ln55_fu_581_p2() {
    or_ln55_fu_581_p2 = (empty_3_reg_890.read() | ap_const_lv6_4);
}

void fwht16::thread_or_ln56_fu_598_p2() {
    or_ln56_fu_598_p2 = (empty_3_reg_890.read() | ap_const_lv6_5);
}

void fwht16::thread_or_ln57_fu_613_p2() {
    or_ln57_fu_613_p2 = (empty_3_reg_890.read() | ap_const_lv6_6);
}

void fwht16::thread_or_ln58_fu_628_p2() {
    or_ln58_fu_628_p2 = (empty_3_reg_890.read() | ap_const_lv6_7);
}

void fwht16::thread_or_ln_fu_670_p3() {
    or_ln_fu_670_p3 = esl_concat<1,4>(ap_const_lv1_1, out_1_rec_reg_320.read());
}

void fwht16::thread_out_0_rec_cast_fu_341_p1() {
    out_0_rec_cast_fu_341_p1 = esl_zext<64,7>(out_0_rec_reg_298.read());
}

void fwht16::thread_out_1_rec_cast2_fu_638_p1() {
    out_1_rec_cast2_fu_638_p1 = esl_zext<6,4>(out_1_rec_reg_320.read());
}

void fwht16::thread_out_1_rec_cast_fu_642_p1() {
    out_1_rec_cast_fu_642_p1 = esl_zext<64,4>(out_1_rec_reg_320.read());
}

void fwht16::thread_output_block_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        output_block_address0 = output_block_addr_14_reg_1129.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        output_block_address0 = output_block_addr_12_reg_1107.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        output_block_address0 = output_block_addr_1_reg_1042.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        output_block_address0 = output_block_addr_9_reg_1061.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        output_block_address0 =  (sc_lv<7>) (zext_ln74_fu_717_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        output_block_address0 =  (sc_lv<7>) (zext_ln71_fu_699_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        output_block_address0 =  (sc_lv<7>) (zext_ln68_fu_678_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        output_block_address0 =  (sc_lv<7>) (out_1_rec_cast_fu_642_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        output_block_address0 =  (sc_lv<7>) (zext_ln57_fu_618_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        output_block_address0 =  (sc_lv<7>) (zext_ln55_fu_586_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_block_address0 =  (sc_lv<7>) (zext_ln53_fu_538_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_block_address0 = output_block_addr_reg_857.read();
    } else {
        output_block_address0 = "XXXXXXX";
    }
}

void fwht16::thread_output_block_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        output_block_address1 = output_block_addr_15_reg_1134.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        output_block_address1 = output_block_addr_13_reg_1112.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        output_block_address1 = output_block_addr_11_reg_1090.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        output_block_address1 = output_block_addr_10_reg_1084.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        output_block_address1 =  (sc_lv<7>) (zext_ln74_1_fu_725_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        output_block_address1 =  (sc_lv<7>) (zext_ln71_1_fu_709_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        output_block_address1 =  (sc_lv<7>) (zext_ln68_1_fu_686_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        output_block_address1 =  (sc_lv<7>) (zext_ln65_fu_665_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        output_block_address1 =  (sc_lv<7>) (zext_ln58_fu_633_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        output_block_address1 =  (sc_lv<7>) (zext_ln56_fu_603_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_block_address1 =  (sc_lv<7>) (zext_ln54_fu_553_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_block_address1 =  (sc_lv<7>) (zext_ln52_fu_523_p1.read());
    } else {
        output_block_address1 = "XXXXXXX";
    }
}

void fwht16::thread_output_block_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        output_block_ce0 = ap_const_logic_1;
    } else {
        output_block_ce0 = ap_const_logic_0;
    }
}

void fwht16::thread_output_block_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        output_block_ce1 = ap_const_logic_1;
    } else {
        output_block_ce1 = ap_const_logic_0;
    }
}

void fwht16::thread_output_block_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        output_block_d0 = sub_ln95_fu_842_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        output_block_d0 = add_ln93_fu_828_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        output_block_d0 = add_ln89_reg_1175.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        output_block_d0 = sub_ln90_fu_792_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        output_block_d0 = sub_ln57_fu_608_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        output_block_d0 = add_ln55_fu_574_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_block_d0 = sub_ln53_fu_528_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_block_d0 = add_ln51_fu_504_p2.read();
    } else {
        output_block_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fwht16::thread_output_block_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        output_block_d1 = add_ln96_fu_847_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        output_block_d1 = sub_ln94_fu_835_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        output_block_d1 = add_ln92_reg_1180.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        output_block_d1 = sub_ln91_fu_799_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        output_block_d1 = add_ln58_fu_623_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        output_block_d1 = sub_ln56_fu_591_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_block_d1 = add_ln54_fu_543_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_block_d1 = sub_ln52_fu_511_p2.read();
    } else {
        output_block_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fwht16::thread_output_block_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        output_block_we0 = ap_const_logic_1;
    } else {
        output_block_we0 = ap_const_logic_0;
    }
}

void fwht16::thread_output_block_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        output_block_we1 = ap_const_logic_1;
    } else {
        output_block_we1 = ap_const_logic_0;
    }
}

void fwht16::thread_sext_ln25_fu_332_p1() {
    sext_ln25_fu_332_p1 = esl_sext<35,32>(stride.read());
}

void fwht16::thread_sext_ln68_fu_683_p1() {
    sext_ln68_fu_683_p1 = esl_sext<5,4>(xor_ln65_reg_1055.read());
}

void fwht16::thread_sext_ln74_1_fu_722_p1() {
    sext_ln74_1_fu_722_p1 = esl_sext<6,4>(xor_ln65_reg_1055.read());
}

void fwht16::thread_sext_ln74_fu_714_p1() {
    sext_ln74_fu_714_p1 = esl_sext<6,5>(or_ln_reg_1079.read());
}

void fwht16::thread_sub_ln28_fu_452_p2() {
    sub_ln28_fu_452_p2 = (!block_load_reg_911.read().is_01() || !block_load_1_reg_917.read().is_01())? sc_lv<32>(): (sc_biguint<32>(block_load_reg_911.read()) - sc_biguint<32>(block_load_1_reg_917.read()));
}

void fwht16::thread_sub_ln31_fu_460_p2() {
    sub_ln31_fu_460_p2 = (!block_load_2_reg_933.read().is_01() || !block_load_3_reg_939.read().is_01())? sc_lv<32>(): (sc_biguint<32>(block_load_2_reg_933.read()) - sc_biguint<32>(block_load_3_reg_939.read()));
}

void fwht16::thread_sub_ln34_fu_468_p2() {
    sub_ln34_fu_468_p2 = (!block_load_4_reg_955.read().is_01() || !block_load_5_reg_961.read().is_01())? sc_lv<32>(): (sc_biguint<32>(block_load_4_reg_955.read()) - sc_biguint<32>(block_load_5_reg_961.read()));
}

void fwht16::thread_sub_ln37_fu_476_p2() {
    sub_ln37_fu_476_p2 = (!block_load_6_reg_977.read().is_01() || !block_load_7_reg_983.read().is_01())? sc_lv<32>(): (sc_biguint<32>(block_load_6_reg_977.read()) - sc_biguint<32>(block_load_7_reg_983.read()));
}

void fwht16::thread_sub_ln41_fu_486_p2() {
    sub_ln41_fu_486_p2 = (!add_ln27_1_fu_448_p2.read().is_01() || !add_ln30_2_fu_456_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln27_1_fu_448_p2.read()) - sc_biguint<32>(add_ln30_2_fu_456_p2.read()));
}

void fwht16::thread_sub_ln42_fu_558_p2() {
    sub_ln42_fu_558_p2 = (!sub_ln28_reg_989.read().is_01() || !sub_ln31_reg_995.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln28_reg_989.read()) - sc_biguint<32>(sub_ln31_reg_995.read()));
}

void fwht16::thread_sub_ln46_fu_498_p2() {
    sub_ln46_fu_498_p2 = (!add_ln33_2_fu_464_p2.read().is_01() || !add_ln36_2_fu_472_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln33_2_fu_464_p2.read()) - sc_biguint<32>(add_ln36_2_fu_472_p2.read()));
}

void fwht16::thread_sub_ln47_fu_566_p2() {
    sub_ln47_fu_566_p2 = (!sub_ln34_reg_1001.read().is_01() || !sub_ln37_reg_1007.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln34_reg_1001.read()) - sc_biguint<32>(sub_ln37_reg_1007.read()));
}

void fwht16::thread_sub_ln52_fu_511_p2() {
    sub_ln52_fu_511_p2 = (!add_ln40_fu_480_p2.read().is_01() || !add_ln45_fu_492_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln40_fu_480_p2.read()) - sc_biguint<32>(add_ln45_fu_492_p2.read()));
}

void fwht16::thread_sub_ln53_fu_528_p2() {
    sub_ln53_fu_528_p2 = (!sub_ln41_reg_1013.read().is_01() || !sub_ln46_reg_1019.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln41_reg_1013.read()) - sc_biguint<32>(sub_ln46_reg_1019.read()));
}

void fwht16::thread_sub_ln56_fu_591_p2() {
    sub_ln56_fu_591_p2 = (!sub_ln42_fu_558_p2.read().is_01() || !sub_ln47_fu_566_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln42_fu_558_p2.read()) - sc_biguint<32>(sub_ln47_fu_566_p2.read()));
}

void fwht16::thread_sub_ln57_fu_608_p2() {
    sub_ln57_fu_608_p2 = (!add_ln43_reg_1025.read().is_01() || !add_ln48_reg_1031.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln43_reg_1025.read()) - sc_biguint<32>(add_ln48_reg_1031.read()));
}

void fwht16::thread_sub_ln66_fu_734_p2() {
    sub_ln66_fu_734_p2 = (!output_block_load_reg_1067.read().is_01() || !output_block_load_1_reg_1073.read().is_01())? sc_lv<32>(): (sc_biguint<32>(output_block_load_reg_1067.read()) - sc_biguint<32>(output_block_load_1_reg_1073.read()));
}

void fwht16::thread_sub_ln69_fu_742_p2() {
    sub_ln69_fu_742_p2 = (!output_block_load_2_reg_1095.read().is_01() || !output_block_load_3_reg_1101.read().is_01())? sc_lv<32>(): (sc_biguint<32>(output_block_load_2_reg_1095.read()) - sc_biguint<32>(output_block_load_3_reg_1101.read()));
}

void fwht16::thread_sub_ln72_fu_750_p2() {
    sub_ln72_fu_750_p2 = (!output_block_load_4_reg_1117.read().is_01() || !output_block_load_5_reg_1123.read().is_01())? sc_lv<32>(): (sc_biguint<32>(output_block_load_4_reg_1117.read()) - sc_biguint<32>(output_block_load_5_reg_1123.read()));
}

void fwht16::thread_sub_ln75_fu_758_p2() {
    sub_ln75_fu_758_p2 = (!output_block_load_6_reg_1139.read().is_01() || !output_block_load_7_reg_1145.read().is_01())? sc_lv<32>(): (sc_biguint<32>(output_block_load_6_reg_1139.read()) - sc_biguint<32>(output_block_load_7_reg_1145.read()));
}

void fwht16::thread_sub_ln79_fu_768_p2() {
    sub_ln79_fu_768_p2 = (!add_ln65_fu_730_p2.read().is_01() || !add_ln68_fu_738_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln65_fu_730_p2.read()) - sc_biguint<32>(add_ln68_fu_738_p2.read()));
}

void fwht16::thread_sub_ln80_fu_812_p2() {
    sub_ln80_fu_812_p2 = (!sub_ln66_reg_1151.read().is_01() || !sub_ln69_reg_1157.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln66_reg_1151.read()) - sc_biguint<32>(sub_ln69_reg_1157.read()));
}

void fwht16::thread_sub_ln84_fu_780_p2() {
    sub_ln84_fu_780_p2 = (!add_ln71_1_fu_746_p2.read().is_01() || !add_ln74_fu_754_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln71_1_fu_746_p2.read()) - sc_biguint<32>(add_ln74_fu_754_p2.read()));
}

void fwht16::thread_sub_ln85_fu_820_p2() {
    sub_ln85_fu_820_p2 = (!sub_ln72_reg_1163.read().is_01() || !sub_ln75_reg_1169.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln72_reg_1163.read()) - sc_biguint<32>(sub_ln75_reg_1169.read()));
}

void fwht16::thread_sub_ln90_fu_792_p2() {
    sub_ln90_fu_792_p2 = (!add_ln78_fu_762_p2.read().is_01() || !add_ln83_fu_774_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln78_fu_762_p2.read()) - sc_biguint<32>(add_ln83_fu_774_p2.read()));
}

void fwht16::thread_sub_ln91_fu_799_p2() {
    sub_ln91_fu_799_p2 = (!sub_ln79_fu_768_p2.read().is_01() || !sub_ln84_fu_780_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln79_fu_768_p2.read()) - sc_biguint<32>(sub_ln84_fu_780_p2.read()));
}

void fwht16::thread_sub_ln94_fu_835_p2() {
    sub_ln94_fu_835_p2 = (!sub_ln80_fu_812_p2.read().is_01() || !sub_ln85_fu_820_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln80_fu_812_p2.read()) - sc_biguint<32>(sub_ln85_fu_820_p2.read()));
}

void fwht16::thread_sub_ln95_fu_842_p2() {
    sub_ln95_fu_842_p2 = (!add_ln81_reg_1185.read().is_01() || !add_ln86_reg_1191.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln81_reg_1185.read()) - sc_biguint<32>(add_ln86_reg_1191.read()));
}

void fwht16::thread_tmp_0_rec_cast_fu_336_p1() {
    tmp_0_rec_cast_fu_336_p1 = esl_sext<64,35>(tmp_0_rec_reg_287.read());
}

void fwht16::thread_xor_ln65_fu_659_p2() {
    xor_ln65_fu_659_p2 = (out_1_rec_reg_320.read() ^ ap_const_lv4_8);
}

void fwht16::thread_zext_ln27_fu_368_p1() {
    zext_ln27_fu_368_p1 = esl_zext<64,8>(add_ln27_fu_362_p2.read());
}

void fwht16::thread_zext_ln30_1_fu_403_p1() {
    zext_ln30_1_fu_403_p1 = esl_zext<64,8>(add_ln30_1_fu_398_p2.read());
}

void fwht16::thread_zext_ln30_fu_393_p1() {
    zext_ln30_fu_393_p1 = esl_zext<64,8>(add_ln30_fu_388_p2.read());
}

void fwht16::thread_zext_ln33_1_fu_423_p1() {
    zext_ln33_1_fu_423_p1 = esl_zext<64,8>(add_ln33_1_fu_418_p2.read());
}

void fwht16::thread_zext_ln33_fu_413_p1() {
    zext_ln33_fu_413_p1 = esl_zext<64,8>(add_ln33_fu_408_p2.read());
}

void fwht16::thread_zext_ln36_1_fu_443_p1() {
    zext_ln36_1_fu_443_p1 = esl_zext<64,8>(add_ln36_1_fu_438_p2.read());
}

void fwht16::thread_zext_ln36_fu_433_p1() {
    zext_ln36_fu_433_p1 = esl_zext<64,8>(add_ln36_fu_428_p2.read());
}

void fwht16::thread_zext_ln52_fu_523_p1() {
    zext_ln52_fu_523_p1 = esl_zext<64,6>(or_ln52_fu_518_p2.read());
}

void fwht16::thread_zext_ln53_fu_538_p1() {
    zext_ln53_fu_538_p1 = esl_zext<64,6>(or_ln53_fu_533_p2.read());
}

void fwht16::thread_zext_ln54_fu_553_p1() {
    zext_ln54_fu_553_p1 = esl_zext<64,6>(or_ln54_fu_548_p2.read());
}

void fwht16::thread_zext_ln55_fu_586_p1() {
    zext_ln55_fu_586_p1 = esl_zext<64,6>(or_ln55_fu_581_p2.read());
}

void fwht16::thread_zext_ln56_fu_603_p1() {
    zext_ln56_fu_603_p1 = esl_zext<64,6>(or_ln56_fu_598_p2.read());
}

void fwht16::thread_zext_ln57_fu_618_p1() {
    zext_ln57_fu_618_p1 = esl_zext<64,6>(or_ln57_fu_613_p2.read());
}

void fwht16::thread_zext_ln58_fu_633_p1() {
    zext_ln58_fu_633_p1 = esl_zext<64,6>(or_ln58_fu_628_p2.read());
}

void fwht16::thread_zext_ln65_fu_665_p1() {
    zext_ln65_fu_665_p1 = esl_zext<64,4>(xor_ln65_fu_659_p2.read());
}

void fwht16::thread_zext_ln68_1_fu_686_p1() {
    zext_ln68_1_fu_686_p1 = esl_zext<64,5>(sext_ln68_fu_683_p1.read());
}

void fwht16::thread_zext_ln68_fu_678_p1() {
    zext_ln68_fu_678_p1 = esl_zext<64,5>(or_ln_fu_670_p3.read());
}

void fwht16::thread_zext_ln71_1_fu_709_p1() {
    zext_ln71_1_fu_709_p1 = esl_zext<64,6>(add_ln71_fu_704_p2.read());
}

void fwht16::thread_zext_ln71_fu_699_p1() {
    zext_ln71_fu_699_p1 = esl_zext<64,6>(or_ln1_fu_691_p3.read());
}

void fwht16::thread_zext_ln74_1_fu_725_p1() {
    zext_ln74_1_fu_725_p1 = esl_zext<64,6>(sext_ln74_1_fu_722_p1.read());
}

void fwht16::thread_zext_ln74_fu_717_p1() {
    zext_ln74_fu_717_p1 = esl_zext<64,6>(sext_ln74_fu_714_p1.read());
}

void fwht16::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln25_fu_346_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(icmp_ln63_fu_647_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<19>) ("XXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void fwht16::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"block_r_address0\" :  \"" << block_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"block_r_ce0\" :  \"" << block_r_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"block_r_q0\" :  \"" << block_r_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"block_r_address1\" :  \"" << block_r_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"block_r_ce1\" :  \"" << block_r_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"block_r_q1\" :  \"" << block_r_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_block_address0\" :  \"" << output_block_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_block_ce0\" :  \"" << output_block_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_block_we0\" :  \"" << output_block_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_block_d0\" :  \"" << output_block_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_block_q0\" :  \"" << output_block_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_block_address1\" :  \"" << output_block_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_block_ce1\" :  \"" << output_block_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_block_we1\" :  \"" << output_block_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_block_d1\" :  \"" << output_block_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_block_q1\" :  \"" << output_block_q1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"stride\" :  \"" << stride.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"intra\" :  \"" << intra.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

