package require -exact qsys 15.0
set_module_property NAME v4l2_detect_cvt_internal
set_module_property VERSION 1.0
set_module_property INTERNAL true
set_module_property GROUP HLS
set_module_property DISPLAY_NAME v4l2_detect_cvt_internal
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property SUPPORTED_DEVICE_FAMILIES {"Arria 10"}
set_module_assignment hls.cosim.name {_Z15v4l2_detect_cvtjjjjibP15v4l2_dv_timings}
set_module_assignment hls.compressed.name {v4l2_detect_cvt}

#### Synthesis fileset
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL v4l2_detect_cvt_internal
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file "dspba_library_ver.sv" SYSTEM_VERILOG PATH "linux64/lib/dspba/Libraries/sv/base/dspba_library_ver.sv"
add_fileset_file "acl_data_fifo.v" SYSTEM_VERILOG PATH "ip/acl_data_fifo.v"
add_fileset_file "acl_fifo.v" SYSTEM_VERILOG PATH "ip/acl_fifo.v"
add_fileset_file "acl_altera_syncram_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_altera_syncram_wrapped.sv"
add_fileset_file "acl_scfifo_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_scfifo_wrapped.sv"
add_fileset_file "acl_ecc_decoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_decoder.sv"
add_fileset_file "acl_ecc_encoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_encoder.sv"
add_fileset_file "acl_ecc.svh" SYSTEM_VERILOG PATH "ip/acl_ecc.svh"
add_fileset_file "acl_ll_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_fifo.v"
add_fileset_file "acl_ll_ram_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_ram_fifo.v"
add_fileset_file "acl_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_valid_fifo_counter.v"
add_fileset_file "acl_dspba_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_dspba_valid_fifo_counter.v"
add_fileset_file "acl_staging_reg.v" SYSTEM_VERILOG PATH "ip/acl_staging_reg.v"
add_fileset_file "hld_fifo.sv" SYSTEM_VERILOG PATH "ip/hld_fifo.sv"
add_fileset_file "acl_mid_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_mid_speed_fifo.sv"
add_fileset_file "acl_latency_one_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_one_ram_fifo.sv"
add_fileset_file "acl_latency_zero_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_zero_ram_fifo.sv"
add_fileset_file "hld_fifo_zero_width.sv" SYSTEM_VERILOG PATH "ip/hld_fifo_zero_width.sv"
add_fileset_file "acl_high_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_high_speed_fifo.sv"
add_fileset_file "acl_low_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_low_latency_fifo.sv"
add_fileset_file "acl_zero_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_zero_latency_fifo.sv"
add_fileset_file "acl_fanout_pipeline.sv" SYSTEM_VERILOG PATH "ip/acl_fanout_pipeline.sv"
add_fileset_file "acl_std_synchronizer_nocut.v" SYSTEM_VERILOG PATH "ip/acl_std_synchronizer_nocut.v"
add_fileset_file "acl_tessellated_incr_decr_threshold.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_threshold.sv"
add_fileset_file "acl_tessellated_incr_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_lookahead.sv"
add_fileset_file "acl_reset_handler.sv" SYSTEM_VERILOG PATH "ip/acl_reset_handler.sv"
add_fileset_file "acl_lfsr.sv" SYSTEM_VERILOG PATH "ip/acl_lfsr.sv"
add_fileset_file "acl_pop.v" SYSTEM_VERILOG PATH "ip/acl_pop.v"
add_fileset_file "acl_push.v" SYSTEM_VERILOG PATH "ip/acl_push.v"
add_fileset_file "acl_token_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_token_fifo_counter.v"
add_fileset_file "acl_pipeline.v" SYSTEM_VERILOG PATH "ip/acl_pipeline.v"
add_fileset_file "acl_dspba_buffer.v" SYSTEM_VERILOG PATH "ip/acl_dspba_buffer.v"
add_fileset_file "st_top.v" SYSTEM_VERILOG PATH "ip/st_top.v"
add_fileset_file "lsu_top.v" SYSTEM_VERILOG PATH "ip/lsu_top.v"
add_fileset_file "lsu_permute_address.v" SYSTEM_VERILOG PATH "ip/lsu_permute_address.v"
add_fileset_file "lsu_pipelined.v" SYSTEM_VERILOG PATH "ip/lsu_pipelined.v"
add_fileset_file "lsu_enabled.v" SYSTEM_VERILOG PATH "ip/lsu_enabled.v"
add_fileset_file "lsu_basic_coalescer.v" SYSTEM_VERILOG PATH "ip/lsu_basic_coalescer.v"
add_fileset_file "lsu_simple.v" SYSTEM_VERILOG PATH "ip/lsu_simple.v"
add_fileset_file "lsu_streaming.v" SYSTEM_VERILOG PATH "ip/lsu_streaming.v"
add_fileset_file "lsu_burst_master.v" SYSTEM_VERILOG PATH "ip/lsu_burst_master.v"
add_fileset_file "lsu_bursting_load_stores.v" SYSTEM_VERILOG PATH "ip/lsu_bursting_load_stores.v"
add_fileset_file "lsu_non_aligned_write.v" SYSTEM_VERILOG PATH "ip/lsu_non_aligned_write.v"
add_fileset_file "lsu_read_cache.v" SYSTEM_VERILOG PATH "ip/lsu_read_cache.v"
add_fileset_file "lsu_atomic.v" SYSTEM_VERILOG PATH "ip/lsu_atomic.v"
add_fileset_file "lsu_prefetch_block.v" SYSTEM_VERILOG PATH "ip/lsu_prefetch_block.v"
add_fileset_file "lsu_wide_wrapper.v" SYSTEM_VERILOG PATH "ip/lsu_wide_wrapper.v"
add_fileset_file "lsu_streaming_prefetch.v" SYSTEM_VERILOG PATH "ip/lsu_streaming_prefetch.v"
add_fileset_file "acl_aligned_burst_coalesced_lsu.v" SYSTEM_VERILOG PATH "ip/acl_aligned_burst_coalesced_lsu.v"
add_fileset_file "acl_toggle_detect.v" SYSTEM_VERILOG PATH "ip/acl_toggle_detect.v"
add_fileset_file "acl_debug_mem.v" SYSTEM_VERILOG PATH "ip/acl_debug_mem.v"
add_fileset_file "lsu_burst_coalesced_pipelined_write.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_write.sv"
add_fileset_file "lsu_burst_coalesced_pipelined_read.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_read.sv"
add_fileset_file "acl_fifo_stall_valid_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_fifo_stall_valid_lookahead.sv"
add_fileset_file "acl_parameter_assert.svh" SYSTEM_VERILOG PATH "ip/acl_parameter_assert.svh"
add_fileset_file "hld_global_load_store.sv" SYSTEM_VERILOG PATH "ip/hld_global_load_store.sv"
add_fileset_file "hld_lsu.sv" SYSTEM_VERILOG PATH "ip/hld_lsu.sv"
add_fileset_file "hld_lsu_burst_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_burst_coalescer.sv"
add_fileset_file "hld_lsu_coalescer_dynamic_timeout.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_coalescer_dynamic_timeout.sv"
add_fileset_file "hld_lsu_data_aligner.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_data_aligner.sv"
add_fileset_file "hld_lsu_read_cache.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_cache.sv"
add_fileset_file "hld_lsu_read_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_data_alignment.sv"
add_fileset_file "hld_lsu_unaligned_controller.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_unaligned_controller.sv"
add_fileset_file "hld_lsu_word_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_word_coalescer.sv"
add_fileset_file "hld_lsu_write_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_data_alignment.sv"
add_fileset_file "hld_lsu_write_kernel_downstream.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_kernel_downstream.sv"
add_fileset_file "acl_shift_register_no_reset.sv" SYSTEM_VERILOG PATH "ip/acl_shift_register_no_reset.sv"
add_fileset_file "acl_reset_wire.v" SYSTEM_VERILOG PATH "ip/acl_reset_wire.v"
add_fileset_file "v4l2_detect_cvt_function_wrapper.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_function_wrapper.sv"
add_fileset_file "v4l2_detect_cvt_function.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_function.sv"
add_fileset_file "v4l2_detect_cvt_bb_B0_runOnce.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_bb_B0_runOnce.sv"
add_fileset_file "v4l2_detect_cvt_bb_B0_runOnce_stall_region.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_bb_B0_runOnce_stall_region.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_token_i1_wt_limpush_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_token_i1_wt_limpush_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv"
add_fileset_file "v4l2_detect_cvt_B0_runOnce_merge_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_B0_runOnce_merge_reg.sv"
add_fileset_file "v4l2_detect_cvt_B0_runOnce_branch.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_B0_runOnce_branch.sv"
add_fileset_file "v4l2_detect_cvt_B0_runOnce_merge.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_B0_runOnce_merge.sv"
add_fileset_file "v4l2_detect_cvt_bb_B1_start.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_bb_B1_start.sv"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_region.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_region.sv"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z761_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z761_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z764_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z764_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z767_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z767_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z770_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z770_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z831_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z831_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z834_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z834_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z837_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z837_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z840_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z840_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z901_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z901_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z904_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z904_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z907_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z907_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z910_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z910_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_i_iowr_bl_return_unnamedA000000Zvt4_v4l2_detect_cvt0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_iowr_bl_return_unnamedA000000Zvt4_v4l2_detect_cvt0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_lm14429_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_lm14429_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_lm14429_10.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_lm14429_10.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_lm15430_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_lm15430_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_lm15430_11.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_lm15430_11.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_lm15631_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_lm15631_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_lm15631_12.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_lm15631_12.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_lm15833_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_lm15833_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_lm15833_14.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_lm15833_14.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_lm16034_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_lm16034_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_lm16034_15.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_lm16034_15.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_lm16235_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_lm16235_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_lm16235_16.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_lm16235_16.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_lm19_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_lm19_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_lm19_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_lm19_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_lm6720_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_lm6720_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_lm6720_1.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_lm6720_1.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_18_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_18_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26317_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26317_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26416_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26416_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26515_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26515_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26614_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26614_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26713_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26713_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26812_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26812_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26911_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26911_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_27010_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_27010_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2719_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2719_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2728_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2728_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2737_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2737_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2746_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2746_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2755_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2755_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2764_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2764_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2773_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2773_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2782_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2782_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2791_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2791_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_ml16727_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_ml16727_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_ml16727_8.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_ml16727_8.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_ml17026_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_ml17026_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_ml17026_7.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_ml17026_7.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_ml17325_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_ml17325_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_ml17325_6.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_ml17325_6.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_ml17624_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_ml17624_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_ml17624_5.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_ml17624_5.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_ml18223_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_ml18223_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_ml18223_4.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_ml18223_4.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_ml18822_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_ml18822_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_ml18822_3.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_ml18822_3.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_ml19421_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_ml19421_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_ml19421_2.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_ml19421_2.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_ml28_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_ml28_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_ml28_9.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_ml28_9.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_sink_lm32_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_sink_lm32_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_sink_lm32_13.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_sink_lm32_13.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pipeline_keep_going_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pipeline_keep_going_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pipeline_keep_going_0_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pipeline_keep_going_0_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi100_pop7_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi100_pop7_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi100_pop7_886_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi100_pop7_886_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi116_pop8_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi116_pop8_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi116_pop8_888_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi116_pop8_888_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi122_pop9_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi122_pop9_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi122_pop9_7_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi122_pop9_7_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi123_pop10_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi123_pop10_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi123_pop10_8_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi123_pop10_8_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi137_pop11_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi137_pop11_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi137_pop11_22_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi137_pop11_22_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi151_pop12_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi151_pop12_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi151_pop12_10_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi151_pop12_10_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi165_pop13_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi165_pop13_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi165_pop13_28_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi165_pop13_28_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi179_pop14_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi179_pop14_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi179_pop14_11_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi179_pop14_11_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi193_pop15_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi193_pop15_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi193_pop15_26_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi193_pop15_26_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi207_pop16_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi207_pop16_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi207_pop16_13_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi207_pop16_13_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi221_pop17_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi221_pop17_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi221_pop17_24_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi221_pop17_24_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi235_pop18_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi235_pop18_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi235_pop18_14_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi235_pop18_14_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi249_pop19_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi249_pop19_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi249_pop19_16_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi249_pop19_16_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi263_pop20_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi263_pop20_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi263_pop20_17_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi263_pop20_17_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi277_pop21_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi277_pop21_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi277_pop21_783_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi277_pop21_783_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi294_pop22_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi294_pop22_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi294_pop22_963_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi294_pop22_963_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi295_pop23_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi295_pop23_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi295_pop23_30_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi295_pop23_30_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi309_pop24_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi309_pop24_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi309_pop24_784_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi309_pop24_784_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi326_pop25_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi326_pop25_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi326_pop25_34_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi326_pop25_34_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi340_pop26_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi340_pop26_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi340_pop26_32_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi340_pop26_32_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi354_pop27_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi354_pop27_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi354_pop27_36_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi354_pop27_36_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi368_pop28_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi368_pop28_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi368_pop28_786_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi368_pop28_786_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi385_pop29_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi385_pop29_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi385_pop29_38_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi385_pop29_38_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi399_pop30_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi399_pop30_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi399_pop30_788_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi399_pop30_788_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi416_pop31_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi416_pop31_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi416_pop31_893_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi416_pop31_893_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi417_pop32_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi417_pop32_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi417_pop32_40_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi417_pop32_40_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi54_pop4_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi54_pop4_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi54_pop4_878_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi54_pop4_878_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi68_pop5_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi68_pop5_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi68_pop5_881_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi68_pop5_881_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi85_pop6_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi85_pop6_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi85_pop6_883_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi85_pop6_883_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi_pop3_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi_pop3_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi_pop3_876_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi_pop3_876_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi100_push7_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi100_push7_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi100_push7_887_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi100_push7_887_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi116_push8_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi116_push8_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi116_push8_889_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi116_push8_889_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi122_push9_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi122_push9_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi122_push9_796_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi122_push9_796_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi123_push10_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi123_push10_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi123_push10_802_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi123_push10_802_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi137_push11_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi137_push11_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi137_push11_805_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi137_push11_805_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi151_push12_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi151_push12_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi151_push12_808_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi151_push12_808_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi165_push13_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi165_push13_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi165_push13_813_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi165_push13_813_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi179_push14_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi179_push14_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi179_push14_816_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi179_push14_816_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi193_push15_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi193_push15_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi193_push15_819_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi193_push15_819_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi207_push16_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi207_push16_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi207_push16_822_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi207_push16_822_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi221_push17_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi221_push17_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi221_push17_829_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi221_push17_829_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi235_push18_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi235_push18_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi235_push18_844_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi235_push18_844_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi249_push19_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi249_push19_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi249_push19_847_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi249_push19_847_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi263_push20_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi263_push20_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi263_push20_850_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi263_push20_850_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi277_push21_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi277_push21_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi277_push21_870_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi277_push21_870_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi294_push22_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi294_push22_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi294_push22_964_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi294_push22_964_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi295_push23_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi295_push23_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi295_push23_900_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi295_push23_900_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi309_push24_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi309_push24_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi309_push24_913_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi309_push24_913_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi326_push25_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi326_push25_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi326_push25_921_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi326_push25_921_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi340_push26_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi340_push26_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi340_push26_924_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi340_push26_924_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi354_push27_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi354_push27_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi354_push27_930_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi354_push27_930_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi368_push28_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi368_push28_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi368_push28_940_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi368_push28_940_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi385_push29_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi385_push29_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi385_push29_946_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi385_push29_946_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi399_push30_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi399_push30_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi399_push30_957_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi399_push30_957_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi416_push31_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi416_push31_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi416_push31_961_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi416_push31_961_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi417_push32_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi417_push32_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi417_push32_971_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi417_push32_971_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi54_push4_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi54_push4_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi54_push4_879_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi54_push4_879_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi68_push5_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi68_push5_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi68_push5_882_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi68_push5_882_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi85_push6_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi85_push6_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi85_push6_884_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi85_push6_884_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi_push3_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi_push3_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi_push3_877_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi_push3_877_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_notexitcond_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_notexitcond_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_notexitcond_1_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_notexitcond_1_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_iord_bl_call_unnamed_vA000000Zvt0_v4l2_detect_cvt0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_iord_bl_call_unnamed_vA000000Zvt0_v4l2_detect_cvt0.sv"
add_fileset_file "v4l2_detect_cvt_B1_start_merge_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_B1_start_merge_reg.sv"
add_fileset_file "v4l2_detect_cvt_B1_start_branch.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_B1_start_branch.sv"
add_fileset_file "v4l2_detect_cvt_B1_start_merge.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_B1_start_merge.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pipeline_keep_going_0_sr.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pipeline_keep_going_0_sr.sv"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_sr_1.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_bb_B1_start_sr_1.sv"
add_fileset_file "acl_avm_to_ic.v" SYSTEM_VERILOG PATH "ip/acl_avm_to_ic.v"
add_fileset_file "acl_ic_master_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_master_endpoint.v"
add_fileset_file "acl_arb_intf.v" SYSTEM_VERILOG PATH "ip/acl_arb_intf.v"
add_fileset_file "acl_ic_intf.v" SYSTEM_VERILOG PATH "ip/acl_ic_intf.v"
add_fileset_file "acl_ic_slave_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_endpoint.v"
add_fileset_file "acl_ic_slave_rrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_rrp.v"
add_fileset_file "acl_ic_slave_wrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_wrp.v"
add_fileset_file "acl_arb2.v" SYSTEM_VERILOG PATH "ip/acl_arb2.v"
add_fileset_file "acl_ic_to_avm.v" SYSTEM_VERILOG PATH "ip/acl_ic_to_avm.v"
add_fileset_file "v4l2_detect_cvt_internal.v" SYSTEM_VERILOG PATH "v4l2_detect_cvt_internal.v"

#### Simulation fileset
add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL v4l2_detect_cvt_internal
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file "dspba_library_ver.sv" SYSTEM_VERILOG PATH "linux64/lib/dspba/Libraries/sv/base/dspba_library_ver.sv"
add_fileset_file "acl_data_fifo.v" SYSTEM_VERILOG PATH "ip/acl_data_fifo.v"
add_fileset_file "acl_fifo.v" SYSTEM_VERILOG PATH "ip/acl_fifo.v"
add_fileset_file "acl_altera_syncram_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_altera_syncram_wrapped.sv"
add_fileset_file "acl_scfifo_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_scfifo_wrapped.sv"
add_fileset_file "acl_ecc_decoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_decoder.sv"
add_fileset_file "acl_ecc_encoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_encoder.sv"
add_fileset_file "acl_ecc.svh" SYSTEM_VERILOG PATH "ip/acl_ecc.svh"
add_fileset_file "acl_ll_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_fifo.v"
add_fileset_file "acl_ll_ram_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_ram_fifo.v"
add_fileset_file "acl_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_valid_fifo_counter.v"
add_fileset_file "acl_dspba_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_dspba_valid_fifo_counter.v"
add_fileset_file "acl_staging_reg.v" SYSTEM_VERILOG PATH "ip/acl_staging_reg.v"
add_fileset_file "hld_fifo.sv" SYSTEM_VERILOG PATH "ip/hld_fifo.sv"
add_fileset_file "acl_mid_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_mid_speed_fifo.sv"
add_fileset_file "acl_latency_one_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_one_ram_fifo.sv"
add_fileset_file "acl_latency_zero_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_zero_ram_fifo.sv"
add_fileset_file "hld_fifo_zero_width.sv" SYSTEM_VERILOG PATH "ip/hld_fifo_zero_width.sv"
add_fileset_file "acl_high_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_high_speed_fifo.sv"
add_fileset_file "acl_low_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_low_latency_fifo.sv"
add_fileset_file "acl_zero_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_zero_latency_fifo.sv"
add_fileset_file "acl_fanout_pipeline.sv" SYSTEM_VERILOG PATH "ip/acl_fanout_pipeline.sv"
add_fileset_file "acl_std_synchronizer_nocut.v" SYSTEM_VERILOG PATH "ip/acl_std_synchronizer_nocut.v"
add_fileset_file "acl_tessellated_incr_decr_threshold.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_threshold.sv"
add_fileset_file "acl_tessellated_incr_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_lookahead.sv"
add_fileset_file "acl_reset_handler.sv" SYSTEM_VERILOG PATH "ip/acl_reset_handler.sv"
add_fileset_file "acl_lfsr.sv" SYSTEM_VERILOG PATH "ip/acl_lfsr.sv"
add_fileset_file "acl_pop.v" SYSTEM_VERILOG PATH "ip/acl_pop.v"
add_fileset_file "acl_push.v" SYSTEM_VERILOG PATH "ip/acl_push.v"
add_fileset_file "acl_token_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_token_fifo_counter.v"
add_fileset_file "acl_pipeline.v" SYSTEM_VERILOG PATH "ip/acl_pipeline.v"
add_fileset_file "acl_dspba_buffer.v" SYSTEM_VERILOG PATH "ip/acl_dspba_buffer.v"
add_fileset_file "st_top.v" SYSTEM_VERILOG PATH "ip/st_top.v"
add_fileset_file "lsu_top.v" SYSTEM_VERILOG PATH "ip/lsu_top.v"
add_fileset_file "lsu_permute_address.v" SYSTEM_VERILOG PATH "ip/lsu_permute_address.v"
add_fileset_file "lsu_pipelined.v" SYSTEM_VERILOG PATH "ip/lsu_pipelined.v"
add_fileset_file "lsu_enabled.v" SYSTEM_VERILOG PATH "ip/lsu_enabled.v"
add_fileset_file "lsu_basic_coalescer.v" SYSTEM_VERILOG PATH "ip/lsu_basic_coalescer.v"
add_fileset_file "lsu_simple.v" SYSTEM_VERILOG PATH "ip/lsu_simple.v"
add_fileset_file "lsu_streaming.v" SYSTEM_VERILOG PATH "ip/lsu_streaming.v"
add_fileset_file "lsu_burst_master.v" SYSTEM_VERILOG PATH "ip/lsu_burst_master.v"
add_fileset_file "lsu_bursting_load_stores.v" SYSTEM_VERILOG PATH "ip/lsu_bursting_load_stores.v"
add_fileset_file "lsu_non_aligned_write.v" SYSTEM_VERILOG PATH "ip/lsu_non_aligned_write.v"
add_fileset_file "lsu_read_cache.v" SYSTEM_VERILOG PATH "ip/lsu_read_cache.v"
add_fileset_file "lsu_atomic.v" SYSTEM_VERILOG PATH "ip/lsu_atomic.v"
add_fileset_file "lsu_prefetch_block.v" SYSTEM_VERILOG PATH "ip/lsu_prefetch_block.v"
add_fileset_file "lsu_wide_wrapper.v" SYSTEM_VERILOG PATH "ip/lsu_wide_wrapper.v"
add_fileset_file "lsu_streaming_prefetch.v" SYSTEM_VERILOG PATH "ip/lsu_streaming_prefetch.v"
add_fileset_file "acl_aligned_burst_coalesced_lsu.v" SYSTEM_VERILOG PATH "ip/acl_aligned_burst_coalesced_lsu.v"
add_fileset_file "acl_toggle_detect.v" SYSTEM_VERILOG PATH "ip/acl_toggle_detect.v"
add_fileset_file "acl_debug_mem.v" SYSTEM_VERILOG PATH "ip/acl_debug_mem.v"
add_fileset_file "lsu_burst_coalesced_pipelined_write.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_write.sv"
add_fileset_file "lsu_burst_coalesced_pipelined_read.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_read.sv"
add_fileset_file "acl_fifo_stall_valid_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_fifo_stall_valid_lookahead.sv"
add_fileset_file "acl_parameter_assert.svh" SYSTEM_VERILOG PATH "ip/acl_parameter_assert.svh"
add_fileset_file "hld_global_load_store.sv" SYSTEM_VERILOG PATH "ip/hld_global_load_store.sv"
add_fileset_file "hld_lsu.sv" SYSTEM_VERILOG PATH "ip/hld_lsu.sv"
add_fileset_file "hld_lsu_burst_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_burst_coalescer.sv"
add_fileset_file "hld_lsu_coalescer_dynamic_timeout.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_coalescer_dynamic_timeout.sv"
add_fileset_file "hld_lsu_data_aligner.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_data_aligner.sv"
add_fileset_file "hld_lsu_read_cache.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_cache.sv"
add_fileset_file "hld_lsu_read_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_data_alignment.sv"
add_fileset_file "hld_lsu_unaligned_controller.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_unaligned_controller.sv"
add_fileset_file "hld_lsu_word_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_word_coalescer.sv"
add_fileset_file "hld_lsu_write_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_data_alignment.sv"
add_fileset_file "hld_lsu_write_kernel_downstream.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_kernel_downstream.sv"
add_fileset_file "acl_shift_register_no_reset.sv" SYSTEM_VERILOG PATH "ip/acl_shift_register_no_reset.sv"
add_fileset_file "acl_reset_wire.v" SYSTEM_VERILOG PATH "ip/acl_reset_wire.v"
add_fileset_file "v4l2_detect_cvt_function_wrapper.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_function_wrapper.sv"
add_fileset_file "v4l2_detect_cvt_function.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_function.sv"
add_fileset_file "v4l2_detect_cvt_bb_B0_runOnce.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_bb_B0_runOnce.sv"
add_fileset_file "v4l2_detect_cvt_bb_B0_runOnce_stall_region.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_bb_B0_runOnce_stall_region.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_token_i1_wt_limpush_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_token_i1_wt_limpush_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv"
add_fileset_file "v4l2_detect_cvt_B0_runOnce_merge_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_B0_runOnce_merge_reg.sv"
add_fileset_file "v4l2_detect_cvt_B0_runOnce_branch.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_B0_runOnce_branch.sv"
add_fileset_file "v4l2_detect_cvt_B0_runOnce_merge.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_B0_runOnce_merge.sv"
add_fileset_file "v4l2_detect_cvt_bb_B1_start.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_bb_B1_start.sv"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_region.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_region.sv"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z761_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z761_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z764_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z764_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z767_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z767_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z770_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z770_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z831_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z831_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z834_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z834_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z837_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z837_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z840_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z840_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z901_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z901_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z904_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z904_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z907_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z907_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z910_invTabGen_lutmem.hex" HEX PATH "ip/v4l2_detect_cvt_bb_B1_start_stall_regionA000000Z910_invTabGen_lutmem.hex"
add_fileset_file "v4l2_detect_cvt_i_iowr_bl_return_unnamedA000000Zvt4_v4l2_detect_cvt0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_iowr_bl_return_unnamedA000000Zvt4_v4l2_detect_cvt0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_lm14429_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_lm14429_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_lm14429_10.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_lm14429_10.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_lm15430_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_lm15430_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_lm15430_11.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_lm15430_11.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_lm15631_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_lm15631_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_lm15631_12.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_lm15631_12.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_lm15833_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_lm15833_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_lm15833_14.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_lm15833_14.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_lm16034_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_lm16034_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_lm16034_15.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_lm16034_15.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_lm16235_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_lm16235_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_lm16235_16.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_lm16235_16.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_lm19_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_lm19_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_lm19_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_lm19_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_lm6720_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_lm6720_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_lm6720_1.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_lm6720_1.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_18_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_18_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26317_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26317_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26416_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26416_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26515_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26515_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26614_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26614_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26713_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26713_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26812_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26812_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26911_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_26911_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_27010_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_27010_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2719_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2719_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2728_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2728_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2737_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2737_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2746_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2746_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2755_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2755_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2764_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2764_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2773_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2773_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2782_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2782_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2791_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_memdep_2791_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_ml16727_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_ml16727_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_ml16727_8.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_ml16727_8.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_ml17026_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_ml17026_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_ml17026_7.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_ml17026_7.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_ml17325_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_ml17325_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_ml17325_6.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_ml17325_6.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_ml17624_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_ml17624_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_ml17624_5.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_ml17624_5.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_ml18223_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_ml18223_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_ml18223_4.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_ml18223_4.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_ml18822_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_ml18822_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_ml18822_3.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_ml18822_3.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_ml19421_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_ml19421_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_ml19421_2.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_ml19421_2.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_ml28_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_ml28_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_ml28_9.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_ml28_9.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_mem_sink_lm32_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_mem_sink_lm32_0.sv"
add_fileset_file "v4l2_detect_cvt_readdata_reg_sink_lm32_13.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_readdata_reg_sink_lm32_13.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pipeline_keep_going_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pipeline_keep_going_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pipeline_keep_going_0_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pipeline_keep_going_0_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi100_pop7_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi100_pop7_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi100_pop7_886_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi100_pop7_886_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi116_pop8_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi116_pop8_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi116_pop8_888_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi116_pop8_888_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi122_pop9_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi122_pop9_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi122_pop9_7_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi122_pop9_7_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi123_pop10_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi123_pop10_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi123_pop10_8_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi123_pop10_8_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi137_pop11_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi137_pop11_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi137_pop11_22_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi137_pop11_22_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi151_pop12_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi151_pop12_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi151_pop12_10_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi151_pop12_10_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi165_pop13_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi165_pop13_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi165_pop13_28_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi165_pop13_28_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi179_pop14_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi179_pop14_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi179_pop14_11_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi179_pop14_11_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi193_pop15_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi193_pop15_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi193_pop15_26_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi193_pop15_26_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi207_pop16_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi207_pop16_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi207_pop16_13_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi207_pop16_13_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi221_pop17_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi221_pop17_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi221_pop17_24_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi221_pop17_24_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi235_pop18_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi235_pop18_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi235_pop18_14_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi235_pop18_14_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi249_pop19_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi249_pop19_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi249_pop19_16_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi249_pop19_16_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi263_pop20_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi263_pop20_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi263_pop20_17_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi263_pop20_17_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi277_pop21_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi277_pop21_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi277_pop21_783_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi277_pop21_783_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi294_pop22_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi294_pop22_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi294_pop22_963_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi294_pop22_963_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi295_pop23_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi295_pop23_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi295_pop23_30_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi295_pop23_30_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi309_pop24_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi309_pop24_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi309_pop24_784_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi309_pop24_784_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi326_pop25_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi326_pop25_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi326_pop25_34_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi326_pop25_34_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi340_pop26_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi340_pop26_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi340_pop26_32_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi340_pop26_32_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi354_pop27_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi354_pop27_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi354_pop27_36_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi354_pop27_36_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi368_pop28_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi368_pop28_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi368_pop28_786_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi368_pop28_786_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi385_pop29_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi385_pop29_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi385_pop29_38_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi385_pop29_38_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi399_pop30_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi399_pop30_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi399_pop30_788_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi399_pop30_788_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi416_pop31_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi416_pop31_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi416_pop31_893_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi416_pop31_893_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi417_pop32_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi417_pop32_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi417_pop32_40_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi417_pop32_40_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi54_pop4_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi54_pop4_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi54_pop4_878_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi54_pop4_878_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi68_pop5_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi68_pop5_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi68_pop5_881_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi68_pop5_881_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi85_pop6_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi85_pop6_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi85_pop6_883_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi85_pop6_883_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi_pop3_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi_pop3_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi_pop3_876_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pop_i1_memdep_phi_pop3_876_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi100_push7_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi100_push7_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi100_push7_887_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi100_push7_887_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi116_push8_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi116_push8_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi116_push8_889_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi116_push8_889_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi122_push9_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi122_push9_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi122_push9_796_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi122_push9_796_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi123_push10_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi123_push10_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi123_push10_802_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi123_push10_802_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi137_push11_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi137_push11_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi137_push11_805_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi137_push11_805_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi151_push12_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi151_push12_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi151_push12_808_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi151_push12_808_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi165_push13_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi165_push13_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi165_push13_813_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi165_push13_813_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi179_push14_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi179_push14_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi179_push14_816_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi179_push14_816_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi193_push15_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi193_push15_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi193_push15_819_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi193_push15_819_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi207_push16_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi207_push16_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi207_push16_822_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi207_push16_822_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi221_push17_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi221_push17_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi221_push17_829_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi221_push17_829_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi235_push18_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi235_push18_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi235_push18_844_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi235_push18_844_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi249_push19_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi249_push19_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi249_push19_847_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi249_push19_847_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi263_push20_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi263_push20_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi263_push20_850_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi263_push20_850_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi277_push21_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi277_push21_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi277_push21_870_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi277_push21_870_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi294_push22_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi294_push22_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi294_push22_964_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi294_push22_964_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi295_push23_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi295_push23_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi295_push23_900_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi295_push23_900_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi309_push24_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi309_push24_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi309_push24_913_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi309_push24_913_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi326_push25_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi326_push25_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi326_push25_921_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi326_push25_921_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi340_push26_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi340_push26_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi340_push26_924_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi340_push26_924_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi354_push27_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi354_push27_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi354_push27_930_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi354_push27_930_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi368_push28_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi368_push28_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi368_push28_940_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi368_push28_940_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi385_push29_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi385_push29_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi385_push29_946_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi385_push29_946_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi399_push30_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi399_push30_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi399_push30_957_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi399_push30_957_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi416_push31_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi416_push31_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi416_push31_961_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi416_push31_961_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi417_push32_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi417_push32_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi417_push32_971_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi417_push32_971_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi54_push4_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi54_push4_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi54_push4_879_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi54_push4_879_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi68_push5_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi68_push5_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi68_push5_882_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi68_push5_882_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi85_push6_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi85_push6_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi85_push6_884_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi85_push6_884_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi_push3_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi_push3_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi_push3_877_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_memdep_phi_push3_877_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_notexitcond_0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_notexitcond_0.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_push_i1_notexitcond_1_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_push_i1_notexitcond_1_reg.sv"
add_fileset_file "v4l2_detect_cvt_i_iord_bl_call_unnamed_vA000000Zvt0_v4l2_detect_cvt0.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_iord_bl_call_unnamed_vA000000Zvt0_v4l2_detect_cvt0.sv"
add_fileset_file "v4l2_detect_cvt_B1_start_merge_reg.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_B1_start_merge_reg.sv"
add_fileset_file "v4l2_detect_cvt_B1_start_branch.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_B1_start_branch.sv"
add_fileset_file "v4l2_detect_cvt_B1_start_merge.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_B1_start_merge.sv"
add_fileset_file "v4l2_detect_cvt_i_llvm_fpga_pipeline_keep_going_0_sr.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_i_llvm_fpga_pipeline_keep_going_0_sr.sv"
add_fileset_file "v4l2_detect_cvt_bb_B1_start_sr_1.sv" SYSTEM_VERILOG PATH "ip/v4l2_detect_cvt_bb_B1_start_sr_1.sv"
add_fileset_file "acl_avm_to_ic.v" SYSTEM_VERILOG PATH "ip/acl_avm_to_ic.v"
add_fileset_file "acl_ic_master_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_master_endpoint.v"
add_fileset_file "acl_arb_intf.v" SYSTEM_VERILOG PATH "ip/acl_arb_intf.v"
add_fileset_file "acl_ic_intf.v" SYSTEM_VERILOG PATH "ip/acl_ic_intf.v"
add_fileset_file "acl_ic_slave_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_endpoint.v"
add_fileset_file "acl_ic_slave_rrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_rrp.v"
add_fileset_file "acl_ic_slave_wrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_wrp.v"
add_fileset_file "acl_arb2.v" SYSTEM_VERILOG PATH "ip/acl_arb2.v"
add_fileset_file "acl_ic_to_avm.v" SYSTEM_VERILOG PATH "ip/acl_ic_to_avm.v"
add_fileset_file "v4l2_detect_cvt_internal.v" SYSTEM_VERILOG PATH "v4l2_detect_cvt_internal.v"

#### Primary clock for the component
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_assignment clock hls.cosim.name {$clock}
add_interface_port clock clock clk input 1

#### Primary reset for the component
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_assignment reset hls.cosim.name {$reset}
add_interface_port reset resetn reset_n input 1

#### The component invocation protocol interface (call)
add_interface call conduit sink
set_interface_property call associatedClock clock
set_interface_property call associatedReset reset
set_interface_assignment call hls.cosim.name {$call}
add_interface_port call start valid input 1
add_interface_port call busy stall output 1

#### The component return protocol interface (return)
add_interface return conduit source
set_interface_property return associatedClock clock
set_interface_property return associatedReset reset
set_interface_assignment return hls.cosim.name {$return}
add_interface_port return done valid output 1
add_interface_port return stall stall input 1

#### The component return data interface (returndata)
add_interface returndata conduit source
set_interface_property returndata associatedClock clock
set_interface_property returndata associatedReset reset
set_interface_assignment returndata hls.cosim.name {$returndata}
add_interface_port returndata returndata data output 1

#### Parameter frame_height interface
add_interface frame_height conduit sink
set_interface_property frame_height associatedClock clock
set_interface_property frame_height associatedReset reset
set_interface_assignment frame_height hls.cosim.name {frame_height}
add_interface_port frame_height frame_height data input 32

#### Parameter hfreq interface
add_interface hfreq conduit sink
set_interface_property hfreq associatedClock clock
set_interface_property hfreq associatedReset reset
set_interface_assignment hfreq hls.cosim.name {hfreq}
add_interface_port hfreq hfreq data input 32

#### Parameter vsync interface
add_interface vsync conduit sink
set_interface_property vsync associatedClock clock
set_interface_property vsync associatedReset reset
set_interface_assignment vsync hls.cosim.name {vsync}
add_interface_port vsync vsync data input 32

#### Parameter active_width interface
add_interface active_width conduit sink
set_interface_property active_width associatedClock clock
set_interface_property active_width associatedReset reset
set_interface_assignment active_width hls.cosim.name {active_width}
add_interface_port active_width active_width data input 32

#### Parameter polarities interface
add_interface polarities conduit sink
set_interface_property polarities associatedClock clock
set_interface_property polarities associatedReset reset
set_interface_assignment polarities hls.cosim.name {polarities}
add_interface_port polarities polarities data input 32

#### Parameter interlaced interface
add_interface interlaced conduit sink
set_interface_property interlaced associatedClock clock
set_interface_property interlaced associatedReset reset
set_interface_assignment interlaced hls.cosim.name {interlaced}
add_interface_port interlaced interlaced data input 1

#### Parameter fmt interface
add_interface fmt conduit sink
set_interface_property fmt associatedClock clock
set_interface_property fmt associatedReset reset
set_interface_assignment fmt hls.cosim.name {fmt}
add_interface_port fmt fmt data input 64

#### Parameter CVT_CELL_GRAN interface
add_interface CVT_CELL_GRAN conduit sink
set_interface_property CVT_CELL_GRAN associatedClock clock
set_interface_property CVT_CELL_GRAN associatedReset reset
set_interface_assignment CVT_CELL_GRAN hls.cosim.name {@CVT_CELL_GRAN}
add_interface_port CVT_CELL_GRAN CVT_CELL_GRAN data input 64

#### Parameter CVT_C_PRIME interface
add_interface CVT_C_PRIME conduit sink
set_interface_property CVT_C_PRIME associatedClock clock
set_interface_property CVT_C_PRIME associatedReset reset
set_interface_assignment CVT_C_PRIME hls.cosim.name {@CVT_C_PRIME}
add_interface_port CVT_C_PRIME CVT_C_PRIME data input 64

#### Parameter CVT_HSYNC_PERCENT interface
add_interface CVT_HSYNC_PERCENT conduit sink
set_interface_property CVT_HSYNC_PERCENT associatedClock clock
set_interface_property CVT_HSYNC_PERCENT associatedReset reset
set_interface_assignment CVT_HSYNC_PERCENT hls.cosim.name {@CVT_HSYNC_PERCENT}
add_interface_port CVT_HSYNC_PERCENT CVT_HSYNC_PERCENT data input 64

#### Parameter CVT_MIN_VSYNC_BP interface
add_interface CVT_MIN_VSYNC_BP conduit sink
set_interface_property CVT_MIN_VSYNC_BP associatedClock clock
set_interface_property CVT_MIN_VSYNC_BP associatedReset reset
set_interface_assignment CVT_MIN_VSYNC_BP hls.cosim.name {@CVT_MIN_VSYNC_BP}
add_interface_port CVT_MIN_VSYNC_BP CVT_MIN_VSYNC_BP data input 64

#### Parameter CVT_MIN_V_BPORCH interface
add_interface CVT_MIN_V_BPORCH conduit sink
set_interface_property CVT_MIN_V_BPORCH associatedClock clock
set_interface_property CVT_MIN_V_BPORCH associatedReset reset
set_interface_assignment CVT_MIN_V_BPORCH hls.cosim.name {@CVT_MIN_V_BPORCH}
add_interface_port CVT_MIN_V_BPORCH CVT_MIN_V_BPORCH data input 64

#### Parameter CVT_MIN_V_PORCH_RND interface
add_interface CVT_MIN_V_PORCH_RND conduit sink
set_interface_property CVT_MIN_V_PORCH_RND associatedClock clock
set_interface_property CVT_MIN_V_PORCH_RND associatedReset reset
set_interface_assignment CVT_MIN_V_PORCH_RND hls.cosim.name {@CVT_MIN_V_PORCH_RND}
add_interface_port CVT_MIN_V_PORCH_RND CVT_MIN_V_PORCH_RND data input 64

#### Parameter CVT_M_PRIME interface
add_interface CVT_M_PRIME conduit sink
set_interface_property CVT_M_PRIME associatedClock clock
set_interface_property CVT_M_PRIME associatedReset reset
set_interface_assignment CVT_M_PRIME hls.cosim.name {@CVT_M_PRIME}
add_interface_port CVT_M_PRIME CVT_M_PRIME data input 64

#### Parameter CVT_PXL_CLK_GRAN interface
add_interface CVT_PXL_CLK_GRAN conduit sink
set_interface_property CVT_PXL_CLK_GRAN associatedClock clock
set_interface_property CVT_PXL_CLK_GRAN associatedReset reset
set_interface_assignment CVT_PXL_CLK_GRAN hls.cosim.name {@CVT_PXL_CLK_GRAN}
add_interface_port CVT_PXL_CLK_GRAN CVT_PXL_CLK_GRAN data input 64

#### Parameter CVT_PXL_CLK_GRAN_RB_V2 interface
add_interface CVT_PXL_CLK_GRAN_RB_V2 conduit sink
set_interface_property CVT_PXL_CLK_GRAN_RB_V2 associatedClock clock
set_interface_property CVT_PXL_CLK_GRAN_RB_V2 associatedReset reset
set_interface_assignment CVT_PXL_CLK_GRAN_RB_V2 hls.cosim.name {@CVT_PXL_CLK_GRAN_RB_V2}
add_interface_port CVT_PXL_CLK_GRAN_RB_V2 CVT_PXL_CLK_GRAN_RB_V2 data input 64

#### Parameter CVT_RB_H_BLANK interface
add_interface CVT_RB_H_BLANK conduit sink
set_interface_property CVT_RB_H_BLANK associatedClock clock
set_interface_property CVT_RB_H_BLANK associatedReset reset
set_interface_assignment CVT_RB_H_BLANK hls.cosim.name {@CVT_RB_H_BLANK}
add_interface_port CVT_RB_H_BLANK CVT_RB_H_BLANK data input 64

#### Parameter CVT_RB_H_SYNC interface
add_interface CVT_RB_H_SYNC conduit sink
set_interface_property CVT_RB_H_SYNC associatedClock clock
set_interface_property CVT_RB_H_SYNC associatedReset reset
set_interface_assignment CVT_RB_H_SYNC hls.cosim.name {@CVT_RB_H_SYNC}
add_interface_port CVT_RB_H_SYNC CVT_RB_H_SYNC data input 64

#### Parameter CVT_RB_MIN_V_BLANK interface
add_interface CVT_RB_MIN_V_BLANK conduit sink
set_interface_property CVT_RB_MIN_V_BLANK associatedClock clock
set_interface_property CVT_RB_MIN_V_BLANK associatedReset reset
set_interface_assignment CVT_RB_MIN_V_BLANK hls.cosim.name {@CVT_RB_MIN_V_BLANK}
add_interface_port CVT_RB_MIN_V_BLANK CVT_RB_MIN_V_BLANK data input 64

#### Parameter CVT_RB_MIN_V_BPORCH interface
add_interface CVT_RB_MIN_V_BPORCH conduit sink
set_interface_property CVT_RB_MIN_V_BPORCH associatedClock clock
set_interface_property CVT_RB_MIN_V_BPORCH associatedReset reset
set_interface_assignment CVT_RB_MIN_V_BPORCH hls.cosim.name {@CVT_RB_MIN_V_BPORCH}
add_interface_port CVT_RB_MIN_V_BPORCH CVT_RB_MIN_V_BPORCH data input 64

#### Parameter CVT_RB_V2_H_BLANK interface
add_interface CVT_RB_V2_H_BLANK conduit sink
set_interface_property CVT_RB_V2_H_BLANK associatedClock clock
set_interface_property CVT_RB_V2_H_BLANK associatedReset reset
set_interface_assignment CVT_RB_V2_H_BLANK hls.cosim.name {@CVT_RB_V2_H_BLANK}
add_interface_port CVT_RB_V2_H_BLANK CVT_RB_V2_H_BLANK data input 64

#### Parameter CVT_RB_V2_MIN_V_FPORCH interface
add_interface CVT_RB_V2_MIN_V_FPORCH conduit sink
set_interface_property CVT_RB_V2_MIN_V_FPORCH associatedClock clock
set_interface_property CVT_RB_V2_MIN_V_FPORCH associatedReset reset
set_interface_assignment CVT_RB_V2_MIN_V_FPORCH hls.cosim.name {@CVT_RB_V2_MIN_V_FPORCH}
add_interface_port CVT_RB_V2_MIN_V_FPORCH CVT_RB_V2_MIN_V_FPORCH data input 64

#### Parameter CVT_RB_V_BPORCH interface
add_interface CVT_RB_V_BPORCH conduit sink
set_interface_property CVT_RB_V_BPORCH associatedClock clock
set_interface_property CVT_RB_V_BPORCH associatedReset reset
set_interface_assignment CVT_RB_V_BPORCH hls.cosim.name {@CVT_RB_V_BPORCH}
add_interface_port CVT_RB_V_BPORCH CVT_RB_V_BPORCH data input 64

#### Parameter CVT_RB_V_FPORCH interface
add_interface CVT_RB_V_FPORCH conduit sink
set_interface_property CVT_RB_V_FPORCH associatedClock clock
set_interface_property CVT_RB_V_FPORCH associatedReset reset
set_interface_assignment CVT_RB_V_FPORCH hls.cosim.name {@CVT_RB_V_FPORCH}
add_interface_port CVT_RB_V_FPORCH CVT_RB_V_FPORCH data input 64

#### Parameter V4L2_DV_BT_656_1120 interface
add_interface V4L2_DV_BT_656_1120 conduit sink
set_interface_property V4L2_DV_BT_656_1120 associatedClock clock
set_interface_property V4L2_DV_BT_656_1120 associatedReset reset
set_interface_assignment V4L2_DV_BT_656_1120 hls.cosim.name {@V4L2_DV_BT_656_1120}
add_interface_port V4L2_DV_BT_656_1120 V4L2_DV_BT_656_1120 data input 64

#### Parameter V4L2_DV_BT_STD_CVT interface
add_interface V4L2_DV_BT_STD_CVT conduit sink
set_interface_property V4L2_DV_BT_STD_CVT associatedClock clock
set_interface_property V4L2_DV_BT_STD_CVT associatedReset reset
set_interface_assignment V4L2_DV_BT_STD_CVT hls.cosim.name {@V4L2_DV_BT_STD_CVT}
add_interface_port V4L2_DV_BT_STD_CVT V4L2_DV_BT_STD_CVT data input 64

#### Parameter V4L2_DV_FL_HALF_LINE interface
add_interface V4L2_DV_FL_HALF_LINE conduit sink
set_interface_property V4L2_DV_FL_HALF_LINE associatedClock clock
set_interface_property V4L2_DV_FL_HALF_LINE associatedReset reset
set_interface_assignment V4L2_DV_FL_HALF_LINE hls.cosim.name {@V4L2_DV_FL_HALF_LINE}
add_interface_port V4L2_DV_FL_HALF_LINE V4L2_DV_FL_HALF_LINE data input 64

#### Parameter V4L2_DV_FL_REDUCED_BLANKING interface
add_interface V4L2_DV_FL_REDUCED_BLANKING conduit sink
set_interface_property V4L2_DV_FL_REDUCED_BLANKING associatedClock clock
set_interface_property V4L2_DV_FL_REDUCED_BLANKING associatedReset reset
set_interface_assignment V4L2_DV_FL_REDUCED_BLANKING hls.cosim.name {@V4L2_DV_FL_REDUCED_BLANKING}
add_interface_port V4L2_DV_FL_REDUCED_BLANKING V4L2_DV_FL_REDUCED_BLANKING data input 64

#### Parameter V4L2_DV_HSYNC_POS_POL interface
add_interface V4L2_DV_HSYNC_POS_POL conduit sink
set_interface_property V4L2_DV_HSYNC_POS_POL associatedClock clock
set_interface_property V4L2_DV_HSYNC_POS_POL associatedReset reset
set_interface_assignment V4L2_DV_HSYNC_POS_POL hls.cosim.name {@V4L2_DV_HSYNC_POS_POL}
add_interface_port V4L2_DV_HSYNC_POS_POL V4L2_DV_HSYNC_POS_POL data input 64

#### Parameter V4L2_DV_INTERLACED interface
add_interface V4L2_DV_INTERLACED conduit sink
set_interface_property V4L2_DV_INTERLACED associatedClock clock
set_interface_property V4L2_DV_INTERLACED associatedReset reset
set_interface_assignment V4L2_DV_INTERLACED hls.cosim.name {@V4L2_DV_INTERLACED}
add_interface_port V4L2_DV_INTERLACED V4L2_DV_INTERLACED data input 64

#### Parameter V4L2_DV_PROGRESSIVE interface
add_interface V4L2_DV_PROGRESSIVE conduit sink
set_interface_property V4L2_DV_PROGRESSIVE associatedClock clock
set_interface_property V4L2_DV_PROGRESSIVE associatedReset reset
set_interface_assignment V4L2_DV_PROGRESSIVE hls.cosim.name {@V4L2_DV_PROGRESSIVE}
add_interface_port V4L2_DV_PROGRESSIVE V4L2_DV_PROGRESSIVE data input 64

#### Parameter V4L2_DV_VSYNC_POS_POL interface
add_interface V4L2_DV_VSYNC_POS_POL conduit sink
set_interface_property V4L2_DV_VSYNC_POS_POL associatedClock clock
set_interface_property V4L2_DV_VSYNC_POS_POL associatedReset reset
set_interface_assignment V4L2_DV_VSYNC_POS_POL hls.cosim.name {@V4L2_DV_VSYNC_POS_POL}
add_interface_port V4L2_DV_VSYNC_POS_POL V4L2_DV_VSYNC_POS_POL data input 64

#### Master interface avmm_0_rw with base address 0
add_interface avmm_0_rw avalon start
set_interface_property avmm_0_rw ENABLED true
set_interface_property avmm_0_rw associatedClock clock
set_interface_property avmm_0_rw burstOnBurstBoundariesOnly false
set_interface_property avmm_0_rw doStreamReads false
set_interface_property avmm_0_rw doStreamWrites false
set_interface_property avmm_0_rw linewrapBursts false
set_interface_property avmm_0_rw readWaitTime 0
set_interface_property avmm_0_rw readLatency 1
add_interface_port avmm_0_rw avmm_0_rw_address address output 64
add_interface_port avmm_0_rw avmm_0_rw_byteenable byteenable output 8
add_interface_port avmm_0_rw avmm_0_rw_read read output 1
add_interface_port avmm_0_rw avmm_0_rw_readdata readdata input 64
add_interface_port avmm_0_rw avmm_0_rw_write write output 1
add_interface_port avmm_0_rw avmm_0_rw_writedata writedata output 64

#### Quartus settings (QIP strings)
set_qip_strings { "set_instance_assignment -entity \"%entityName%\" -library \"%libraryName%\" -name AUTO_SHIFT_REGISTER_RECOGNITION OFF -to *_NO_SHIFT_REG*"  }
