#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("tmpFx_address0", 10, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("tmpFx_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("tmpFx_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("tmpFx_address1", 10, hls_out, 0, "ap_memory", "MemPortADDR2", 1),
	Port_Property("tmpFx_ce1", 1, hls_out, 0, "ap_memory", "MemPortCE2", 1),
	Port_Property("tmpFx_q1", 32, hls_in, 0, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("tmpObjSEndTerm_address0", 10, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("tmpObjSEndTerm_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("tmpObjSEndTerm_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("tmpObjSEndTerm_address1", 10, hls_out, 1, "ap_memory", "MemPortADDR2", 1),
	Port_Property("tmpObjSEndTerm_ce1", 1, hls_out, 1, "ap_memory", "MemPortCE2", 1),
	Port_Property("tmpObjSEndTerm_q1", 32, hls_in, 1, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("tmpQN1_address0", 10, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("tmpQN1_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("tmpQN1_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("tmpQN1_d0", 32, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("tmpQN1_address1", 10, hls_out, 2, "ap_memory", "MemPortADDR2", 1),
	Port_Property("tmpQN1_ce1", 1, hls_out, 2, "ap_memory", "MemPortCE2", 1),
	Port_Property("tmpQN1_we1", 1, hls_out, 2, "ap_memory", "MemPortWE2", 1),
	Port_Property("tmpQN1_d1", 32, hls_out, 2, "ap_memory", "MemPortDIN2", 1),
	Port_Property("tmpQN2_address0", 10, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("tmpQN2_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("tmpQN2_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("tmpQN2_d0", 32, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("tmpQN2_address1", 10, hls_out, 3, "ap_memory", "MemPortADDR2", 1),
	Port_Property("tmpQN2_ce1", 1, hls_out, 3, "ap_memory", "MemPortCE2", 1),
	Port_Property("tmpQN2_we1", 1, hls_out, 3, "ap_memory", "MemPortWE2", 1),
	Port_Property("tmpQN2_d1", 32, hls_out, 3, "ap_memory", "MemPortDIN2", 1),
};
const char* HLS_Design_Meta::dut_name = "acado_setObjQN1QN2";
