
namespace eval chebyshev {
  proc get_design_libraries {} {
    set libraries [dict create]
    dict set libraries chebyshev_internal_10 1
    dict set libraries chebyshev             1
    return $libraries
  }
  
  proc get_memory_files {QSYS_SIMDIR} {
    set memory_files [list]
    return $memory_files
  }
  
  proc get_common_design_files {USER_DEFINED_COMPILE_OPTIONS USER_DEFINED_VERILOG_COMPILE_OPTIONS USER_DEFINED_VHDL_COMPILE_OPTIONS QSYS_SIMDIR} {
    set design_files [dict create]
    return $design_files
  }
  
  proc get_design_files {USER_DEFINED_COMPILE_OPTIONS USER_DEFINED_VERILOG_COMPILE_OPTIONS USER_DEFINED_VHDL_COMPILE_OPTIONS QSYS_SIMDIR} {
    set design_files [list]
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/dspba_library_ver.sv"]\"  -work chebyshev_internal_10"                                                   
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_data_fifo.v"]\"  -work chebyshev_internal_10"                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_fifo.v"]\"  -work chebyshev_internal_10"                                                             
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_altera_syncram_wrapped.sv"]\"  -work chebyshev_internal_10"                                          
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_scfifo_wrapped.sv"]\"  -work chebyshev_internal_10"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_ecc_decoder.sv"]\"  -work chebyshev_internal_10"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_ecc_encoder.sv"]\"  -work chebyshev_internal_10"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_ecc.svh"]\"  -work chebyshev_internal_10"                                                            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_ll_fifo.v"]\"  -work chebyshev_internal_10"                                                          
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_ll_ram_fifo.v"]\"  -work chebyshev_internal_10"                                                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_valid_fifo_counter.v"]\"  -work chebyshev_internal_10"                                               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_dspba_valid_fifo_counter.v"]\"  -work chebyshev_internal_10"                                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_staging_reg.v"]\"  -work chebyshev_internal_10"                                                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/hld_fifo.sv"]\"  -work chebyshev_internal_10"                                                            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_mid_speed_fifo.sv"]\"  -work chebyshev_internal_10"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_latency_one_ram_fifo.sv"]\"  -work chebyshev_internal_10"                                            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_latency_zero_ram_fifo.sv"]\"  -work chebyshev_internal_10"                                           
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/hld_fifo_zero_width.sv"]\"  -work chebyshev_internal_10"                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_high_speed_fifo.sv"]\"  -work chebyshev_internal_10"                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_low_latency_fifo.sv"]\"  -work chebyshev_internal_10"                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_zero_latency_fifo.sv"]\"  -work chebyshev_internal_10"                                               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_fanout_pipeline.sv"]\"  -work chebyshev_internal_10"                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_std_synchronizer_nocut.v"]\"  -work chebyshev_internal_10"                                           
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_tessellated_incr_decr_threshold.sv"]\"  -work chebyshev_internal_10"                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_tessellated_incr_lookahead.sv"]\"  -work chebyshev_internal_10"                                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_reset_handler.sv"]\"  -work chebyshev_internal_10"                                                   
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_lfsr.sv"]\"  -work chebyshev_internal_10"                                                            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_pop.v"]\"  -work chebyshev_internal_10"                                                              
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_push.v"]\"  -work chebyshev_internal_10"                                                             
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_token_fifo_counter.v"]\"  -work chebyshev_internal_10"                                               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_pipeline.v"]\"  -work chebyshev_internal_10"                                                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_dspba_buffer.v"]\"  -work chebyshev_internal_10"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_enable_sink.v"]\"  -work chebyshev_internal_10"                                                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/st_top.v"]\"  -work chebyshev_internal_10"                                                               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_ffwdsrc.v"]\"  -work chebyshev_internal_10"                                                          
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_top.v"]\"  -work chebyshev_internal_10"                                                              
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_permute_address.v"]\"  -work chebyshev_internal_10"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_pipelined.v"]\"  -work chebyshev_internal_10"                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_enabled.v"]\"  -work chebyshev_internal_10"                                                          
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_basic_coalescer.v"]\"  -work chebyshev_internal_10"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_simple.v"]\"  -work chebyshev_internal_10"                                                           
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_streaming.v"]\"  -work chebyshev_internal_10"                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_burst_master.v"]\"  -work chebyshev_internal_10"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_bursting_load_stores.v"]\"  -work chebyshev_internal_10"                                             
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_non_aligned_write.v"]\"  -work chebyshev_internal_10"                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_read_cache.v"]\"  -work chebyshev_internal_10"                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_atomic.v"]\"  -work chebyshev_internal_10"                                                           
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_prefetch_block.v"]\"  -work chebyshev_internal_10"                                                   
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_wide_wrapper.v"]\"  -work chebyshev_internal_10"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_streaming_prefetch.v"]\"  -work chebyshev_internal_10"                                               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_aligned_burst_coalesced_lsu.v"]\"  -work chebyshev_internal_10"                                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_toggle_detect.v"]\"  -work chebyshev_internal_10"                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_debug_mem.v"]\"  -work chebyshev_internal_10"                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_burst_coalesced_pipelined_write.sv"]\"  -work chebyshev_internal_10"                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/lsu_burst_coalesced_pipelined_read.sv"]\"  -work chebyshev_internal_10"                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_fifo_stall_valid_lookahead.sv"]\"  -work chebyshev_internal_10"                                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_parameter_assert.svh"]\"  -work chebyshev_internal_10"                                               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/hld_global_load_store.sv"]\"  -work chebyshev_internal_10"                                               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/hld_lsu.sv"]\"  -work chebyshev_internal_10"                                                             
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/hld_lsu_burst_coalescer.sv"]\"  -work chebyshev_internal_10"                                             
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/hld_lsu_coalescer_dynamic_timeout.sv"]\"  -work chebyshev_internal_10"                                   
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/hld_lsu_data_aligner.sv"]\"  -work chebyshev_internal_10"                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/hld_lsu_read_cache.sv"]\"  -work chebyshev_internal_10"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/hld_lsu_read_data_alignment.sv"]\"  -work chebyshev_internal_10"                                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/hld_lsu_unaligned_controller.sv"]\"  -work chebyshev_internal_10"                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/hld_lsu_word_coalescer.sv"]\"  -work chebyshev_internal_10"                                              
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/hld_lsu_write_data_alignment.sv"]\"  -work chebyshev_internal_10"                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/hld_lsu_write_kernel_downstream.sv"]\"  -work chebyshev_internal_10"                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_shift_register_no_reset.sv"]\"  -work chebyshev_internal_10"                                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_full_detector.v"]\"  -work chebyshev_internal_10"                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_tessellated_incr_decr_decr.sv"]\"  -work chebyshev_internal_10"                                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_ffwddst.sv"]\"  -work chebyshev_internal_10"                                                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_loop_limiter.v"]\"  -work chebyshev_internal_10"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_reset_wire.v"]\"  -work chebyshev_internal_10"                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_function_wrapper.sv"]\"  -work chebyshev_internal_10"                                          
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_function.sv"]\"  -work chebyshev_internal_10"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B0_runOnce.sv"]\"  -work chebyshev_internal_10"                                             
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B0_runOnce_stall_region.sv"]\"  -work chebyshev_internal_10"                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B0_runOnce_merge_reg.sv"]\"  -work chebyshev_internal_10"                                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv"]\"  -work chebyshev_internal_10"                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv"]\"  -work chebyshev_internal_10"                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_token_i1_wt_limpush_0.sv"]\"  -work chebyshev_internal_10"                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv"]\"  -work chebyshev_internal_10"                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B0_runOnce_branch.sv"]\"  -work chebyshev_internal_10"                                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B0_runOnce_merge.sv"]\"  -work chebyshev_internal_10"                                          
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B1_start.sv"]\"  -work chebyshev_internal_10"                                               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B1_start_stall_region.sv"]\"  -work chebyshev_internal_10"                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B1_start_merge_reg.sv"]\"  -work chebyshev_internal_10"                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_ffwd_source_i32_unnamed_3_chebyshev0.sv"]\"  -work chebyshev_internal_10"          
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv"]\"  -work chebyshev_internal_10"                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pop_throttle_i1_throttle_pop_1_reg.sv"]\"  -work chebyshev_internal_10"            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_iord_bl_call_unnamed_chebyshev2_chebyshev0.sv"]\"  -work chebyshev_internal_10"              
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_sfc_s_c0_in_wt_entry_s_c0_enter2_chebyshev0.sv"]\"  -work chebyshev_internal_10"             
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_sfc_exit_s_c0_out_A000000Zs_c0_exit_chebyshev0.sv"]\"  -work chebyshev_internal_10"
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter2_chebyshev0.sv"]\"  -work chebyshev_internal_10"       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pipeline_keep_going34_0.sv"]\"  -work chebyshev_internal_10"                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_i1_notexitcond35_0.sv"]\"  -work chebyshev_internal_10"                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B1_start_branch.sv"]\"  -work chebyshev_internal_10"                                           
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B1_start_merge.sv"]\"  -work chebyshev_internal_10"                                            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B2.sv"]\"  -work chebyshev_internal_10"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B2_stall_region.sv"]\"  -work chebyshev_internal_10"                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B2_branch.sv"]\"  -work chebyshev_internal_10"                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B2_merge.sv"]\"  -work chebyshev_internal_10"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B3.sv"]\"  -work chebyshev_internal_10"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B3_stall_region.sv"]\"  -work chebyshev_internal_10"                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B3_merge_reg.sv"]\"  -work chebyshev_internal_10"                                              
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_sfc_s_c0_in_for_body_s_c0_enter463_chebyshev1.sv"]\"  -work chebyshev_internal_10"           
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_sfc_exit_s_c0_out_A000000Zc0_exit48_chebyshev0.sv"]\"  -work chebyshev_internal_10"
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_sfc_exit_s_c0_out_A000000Zyshev1_full_detector.sv"]\"  -work chebyshev_internal_10"
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_sfc_exit_s_c0_out_A000000Zchebyshev1_data_fifo.sv"]\"  -work chebyshev_internal_10"
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_sfc_logic_s_c0_in_for_body_s_c0_enter463_chebyshev0.sv"]\"  -work chebyshev_internal_10"     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_mem_memdep_1_0.sv"]\"  -work chebyshev_internal_10"                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_mem_memdep_0.sv"]\"  -work chebyshev_internal_10"                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pipeline_keep_going20_0.sv"]\"  -work chebyshev_internal_10"                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pop_i11_fpga_indvars_iv_pop10_0.sv"]\"  -work chebyshev_internal_10"               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pop_i32_k_020_pop11_0.sv"]\"  -work chebyshev_internal_10"                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pop_i4_cleanups23_pop13_0.sv"]\"  -work chebyshev_internal_10"                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pop_i4_initerations18_pop12_0.sv"]\"  -work chebyshev_internal_10"                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_i11_fpga_indvars_iv_push10_0.sv"]\"  -work chebyshev_internal_10"             
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_i1_lastiniteration22_0.sv"]\"  -work chebyshev_internal_10"                   
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_i1_notexitcond30_0.sv"]\"  -work chebyshev_internal_10"                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_i32_k_020_push11_0.sv"]\"  -work chebyshev_internal_10"                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_i4_cleanups23_push13_0.sv"]\"  -work chebyshev_internal_10"                   
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_i4_initerations18_push12_0.sv"]\"  -work chebyshev_internal_10"               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B3_branch.sv"]\"  -work chebyshev_internal_10"                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B3_merge.sv"]\"  -work chebyshev_internal_10"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B4.sv"]\"  -work chebyshev_internal_10"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B4_stall_region.sv"]\"  -work chebyshev_internal_10"                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B4_merge_reg.sv"]\"  -work chebyshev_internal_10"                                              
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_sfc_s_c0_in_for_cond8_preheader_s_c0_enter514_chebyshev1.sv"]\"  -work chebyshev_internal_10"
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_sfc_exit_s_c0_out_A000000Zc0_exit55_chebyshev0.sv"]\"  -work chebyshev_internal_10"
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_sfc_logic_s_c0_in_for_cond8_A000000Z_enter514_chebyshev0.sv"]\"  -work chebyshev_internal_10"
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pipeline_keep_going13_0.sv"]\"  -work chebyshev_internal_10"                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pop_i8_fpga_indvars_iv6_pop14_0.sv"]\"  -work chebyshev_internal_10"               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_i1_notexitcond14_0.sv"]\"  -work chebyshev_internal_10"                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_i8_fpga_indvars_iv6_push14_0.sv"]\"  -work chebyshev_internal_10"             
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B4_branch.sv"]\"  -work chebyshev_internal_10"                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B4_merge.sv"]\"  -work chebyshev_internal_10"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B5.sv"]\"  -work chebyshev_internal_10"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B5_stall_region.sv"]\"  -work chebyshev_internal_10"                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_iowr_bl_return_unnamed_chebyshev6_chebyshev0.sv"]\"  -work chebyshev_internal_10"            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_token_i1_throttle_push_0.sv"]\"  -work chebyshev_internal_10"                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_token_i1_throttle_push_3_reg.sv"]\"  -work chebyshev_internal_10"             
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_sfc_s_c0_in_for_cond_cleanup5_s_c0_enter58_chebyshev0.sv"]\"  -work chebyshev_internal_10"   
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_sfc_exit_s_c0_out_A000000Zc0_exit60_chebyshev0.sv"]\"  -work chebyshev_internal_10"
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_sfc_exit_s_c0_out_A000001Zyshev1_full_detector.sv"]\"  -work chebyshev_internal_10"
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_sfc_exit_s_c0_out_A000001Zchebyshev1_data_fifo.sv"]\"  -work chebyshev_internal_10"
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_sfc_logic_s_c0_in_for_cond_cA000000Z0_enter58_chebyshev0.sv"]\"  -work chebyshev_internal_10"
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_ffwd_dest_i32_idx219_0.sv"]\"  -work chebyshev_internal_10"                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_mem_unnamed_5_chebyshev0.sv"]\"  -work chebyshev_internal_10"                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B5_branch.sv"]\"  -work chebyshev_internal_10"                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B5_merge.sv"]\"  -work chebyshev_internal_10"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B6.sv"]\"  -work chebyshev_internal_10"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B6_stall_region.sv"]\"  -work chebyshev_internal_10"                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B6_branch.sv"]\"  -work chebyshev_internal_10"                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B6_merge.sv"]\"  -work chebyshev_internal_10"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B7.sv"]\"  -work chebyshev_internal_10"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B7_stall_region.sv"]\"  -work chebyshev_internal_10"                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B7_merge_reg.sv"]\"  -work chebyshev_internal_10"                                              
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_sfc_s_c0_in_for_body11_s_c0_enter635_chebyshev1.sv"]\"  -work chebyshev_internal_10"         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_sfc_exit_s_c0_out_A000000Zc0_exit67_chebyshev0.sv"]\"  -work chebyshev_internal_10"
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_sfc_exit_s_c0_out_A000002Zyshev1_full_detector.sv"]\"  -work chebyshev_internal_10"
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_sfc_exit_s_c0_out_A000002Zchebyshev1_data_fifo.sv"]\"  -work chebyshev_internal_10"
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_sfc_logic_s_c0_in_for_body11_s_c0_enter635_chebyshev0.sv"]\"  -work chebyshev_internal_10"   
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_mem_memdep_2_0.sv"]\"  -work chebyshev_internal_10"                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_mem_unnamed_7_chebyshev0.sv"]\"  -work chebyshev_internal_10"                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pipeline_keep_going_0.sv"]\"  -work chebyshev_internal_10"                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pop_i11_fpga_indvars_iv3_pop15_0.sv"]\"  -work chebyshev_internal_10"              
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pop_i1_notcmp1138_pop18_0.sv"]\"  -work chebyshev_internal_10"                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pop_i2_cleanups_pop17_0.sv"]\"  -work chebyshev_internal_10"                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pop_i32_k7_018_pop16_0.sv"]\"  -work chebyshev_internal_10"                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_i11_fpga_indvars_iv3_push15_0.sv"]\"  -work chebyshev_internal_10"            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_i1_lastiniteration_0.sv"]\"  -work chebyshev_internal_10"                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_i1_notcmp1138_push18_0.sv"]\"  -work chebyshev_internal_10"                   
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_i1_notexitcond_0.sv"]\"  -work chebyshev_internal_10"                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_i2_cleanups_push17_0.sv"]\"  -work chebyshev_internal_10"                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_push_i32_k7_018_push16_0.sv"]\"  -work chebyshev_internal_10"                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B7_branch.sv"]\"  -work chebyshev_internal_10"                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_B7_merge.sv"]\"  -work chebyshev_internal_10"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pipeline_keep_going13_2_sr.sv"]\"  -work chebyshev_internal_10"                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pipeline_keep_going13_2_valid_fifo.sv"]\"  -work chebyshev_internal_10"            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pipeline_keep_going20_6_sr.sv"]\"  -work chebyshev_internal_10"                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pipeline_keep_going20_6_valid_fifo.sv"]\"  -work chebyshev_internal_10"            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pipeline_keep_going34_1_sr.sv"]\"  -work chebyshev_internal_10"                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pipeline_keep_going34_1_valid_fifo.sv"]\"  -work chebyshev_internal_10"            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pipeline_keep_going_6_sr.sv"]\"  -work chebyshev_internal_10"                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_i_llvm_fpga_pipeline_keep_going_6_valid_fifo.sv"]\"  -work chebyshev_internal_10"              
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_loop_limiter_0.sv"]\"  -work chebyshev_internal_10"                                            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_loop_limiter_1.sv"]\"  -work chebyshev_internal_10"                                            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_loop_limiter_2.sv"]\"  -work chebyshev_internal_10"                                            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B2_sr_0.sv"]\"  -work chebyshev_internal_10"                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B3_sr_1.sv"]\"  -work chebyshev_internal_10"                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B4_sr_1.sv"]\"  -work chebyshev_internal_10"                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B5_sr_0.sv"]\"  -work chebyshev_internal_10"                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B6_sr_0.sv"]\"  -work chebyshev_internal_10"                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_bb_B7_sr_1.sv"]\"  -work chebyshev_internal_10"                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_avm_to_ic.v"]\"  -work chebyshev_internal_10"                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_mem1x.v"]\"  -work chebyshev_internal_10"                                                            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_mem_staging_reg.v"]\"  -work chebyshev_internal_10"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_ic_local_mem_router.v"]\"  -work chebyshev_internal_10"                                              
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_ic_master_endpoint.v"]\"  -work chebyshev_internal_10"                                               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_arb_intf.v"]\"  -work chebyshev_internal_10"                                                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_ic_intf.v"]\"  -work chebyshev_internal_10"                                                          
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_ic_slave_endpoint.v"]\"  -work chebyshev_internal_10"                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_ic_slave_rrp.v"]\"  -work chebyshev_internal_10"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_ic_slave_wrp.v"]\"  -work chebyshev_internal_10"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/acl_arb2.v"]\"  -work chebyshev_internal_10"                                                             
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../chebyshev_internal_10/sim/chebyshev_internal.v"]\"  -work chebyshev_internal_10"                                                   
    lappend design_files "vlog -v2k5 $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/chebyshev.v"]\"  -work chebyshev"                                                                                                
    return $design_files
  }
  
  proc get_elab_options {SIMULATOR_TOOL_BITNESS} {
    set ELAB_OPTIONS ""
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    return $ELAB_OPTIONS
  }
  
  
  proc get_sim_options {SIMULATOR_TOOL_BITNESS} {
    set SIM_OPTIONS ""
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    return $SIM_OPTIONS
  }
  
  
  proc get_env_variables {SIMULATOR_TOOL_BITNESS} {
    set ENV_VARIABLES [dict create]
    set LD_LIBRARY_PATH [dict create]
    dict set ENV_VARIABLES "LD_LIBRARY_PATH" $LD_LIBRARY_PATH
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    return $ENV_VARIABLES
  }
  
  
  proc normalize_path {FILEPATH} {
      if {[catch { package require fileutil } err]} { 
          return $FILEPATH 
      } 
      set path [fileutil::lexnormalize [file join [pwd] $FILEPATH]]  
      if {[file pathtype $FILEPATH] eq "relative"} { 
          set path [fileutil::relative [pwd] $path] 
      } 
      return $path 
  } 
}
