// ------------------------------------------------------------------------- 
// High Level Design Compiler for Intel(R) FPGAs Version 19.4 (Release Build #64)
// 
// Legal Notice: Copyright 2019 Intel Corporation.  All rights reserved.
// Your use of  Intel Corporation's design tools,  logic functions and other
// software and  tools, and its AMPP partner logic functions, and any output
// files any  of the foregoing (including  device programming  or simulation
// files), and  any associated  documentation  or information  are expressly
// subject  to the terms and  conditions of the  Intel FPGA Software License
// Agreement, Intel MegaCore Function License Agreement, or other applicable
// license agreement,  including,  without limitation,  that your use is for
// the  sole  purpose of  programming  logic devices  manufactured by  Intel
// and  sold by Intel  or its authorized  distributors. Please refer  to the
// applicable agreement for further details.
// ---------------------------------------------------------------------------

// SystemVerilog created from afs_abort_to_error_bb_B1_start_stall_region
// SystemVerilog created on Sun May 24 22:37:02 2020


(* altera_attribute = "-name AUTO_SHIFT_REGISTER_RECOGNITION OFF; -name MESSAGE_DISABLE 10036; -name MESSAGE_DISABLE 10037; -name MESSAGE_DISABLE 14130; -name MESSAGE_DISABLE 14320; -name MESSAGE_DISABLE 15400; -name MESSAGE_DISABLE 14130; -name MESSAGE_DISABLE 10036; -name MESSAGE_DISABLE 12020; -name MESSAGE_DISABLE 12030; -name MESSAGE_DISABLE 12010; -name MESSAGE_DISABLE 12110; -name MESSAGE_DISABLE 14320; -name MESSAGE_DISABLE 13410; -name MESSAGE_DISABLE 113007; -name MESSAGE_DISABLE 10958" *)
module afs_abort_to_error_bb_B1_start_stall_region (
    input wire [2303:0] in_iord_bl_call_afs_abort_to_error_i_fifodata,
    input wire [0:0] in_iord_bl_call_afs_abort_to_error_i_fifovalid,
    output wire [0:0] out_aclp_to_limiter_i_llvm_fpga_pipeline_keep_going_afs_abort_to_error1_exiting_valid_out,
    output wire [0:0] out_aclp_to_limiter_i_llvm_fpga_pipeline_keep_going_afs_abort_to_error1_exiting_stall_out,
    input wire [0:0] in_pipeline_stall_in,
    output wire [0:0] out_pipeline_valid_out,
    input wire [0:0] in_flush,
    input wire [0:0] in_stall_in,
    output wire [0:0] out_stall_out,
    input wire [0:0] in_valid_in,
    input wire [63:0] in_pn1_afs_abort_to_error_avm_readdata,
    input wire [0:0] in_pn1_afs_abort_to_error_avm_writeack,
    input wire [0:0] in_pn1_afs_abort_to_error_avm_waitrequest,
    input wire [0:0] in_pn1_afs_abort_to_error_avm_readdatavalid,
    output wire [0:0] out_iord_bl_call_afs_abort_to_error_o_fifoready,
    output wire [0:0] out_valid_out,
    input wire [0:0] in_iowr_bl_return_afs_abort_to_error_i_fifoready,
    output wire [63:0] out_pn1_afs_abort_to_error_avm_address,
    output wire [0:0] out_pn1_afs_abort_to_error_avm_enable,
    output wire [0:0] out_pn1_afs_abort_to_error_avm_read,
    output wire [0:0] out_pn1_afs_abort_to_error_avm_write,
    output wire [63:0] out_pn1_afs_abort_to_error_avm_writedata,
    output wire [7:0] out_pn1_afs_abort_to_error_avm_byteenable,
    output wire [0:0] out_pn1_afs_abort_to_error_avm_burstcount,
    output wire [31:0] out_iowr_bl_return_afs_abort_to_error_o_fifodata,
    output wire [0:0] out_iowr_bl_return_afs_abort_to_error_o_fifovalid,
    input wire clock,
    input wire resetn
    );

    wire [0:0] GND_q;
    wire [0:0] afs_abort_to_error_B1_start_merge_reg_out_stall_out;
    wire [0:0] afs_abort_to_error_B1_start_merge_reg_out_valid_out;
    wire [31:0] i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_out_iowr_bl_return_afs_abort_to_error_o_fifodata;
    wire [0:0] i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_out_iowr_bl_return_afs_abort_to_error_o_fifovalid;
    wire [0:0] i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_out_o_stall;
    wire [0:0] i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_out_o_valid;
    wire [0:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_iord_bl_call_afs_abort_to_error_o_fifoready;
    wire [0:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_stall;
    wire [0:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_valid;
    wire [31:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_0_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_1_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_2_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_3_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_4_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_5_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_6_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_7_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_8_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_9_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_10_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_11_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_12_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_13_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_14_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_15_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_16_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_17_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_18_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_19_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_20_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_21_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_22_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_23_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_24_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_25_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_26_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_27_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_28_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_29_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_30_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_31_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_32_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_33_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_34_tpl;
    wire [63:0] i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_35_tpl;
    wire [0:0] i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_out_aclp_to_limiter_i_llvm_fpga_pipeline_keep_going_afs_abort_to_error1_exiting_stall_out;
    wire [0:0] i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_out_aclp_to_limiter_i_llvm_fpga_pipeline_keep_going_afs_abort_to_error1_exiting_valid_out;
    wire [0:0] i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_out_o_stall;
    wire [0:0] i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_out_o_valid;
    wire [0:0] i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_out_pipeline_valid_out;
    wire [0:0] i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_o_stall;
    wire [0:0] i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_o_valid;
    wire [63:0] i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_address;
    wire [0:0] i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_burstcount;
    wire [7:0] i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_byteenable;
    wire [0:0] i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_enable;
    wire [0:0] i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_read;
    wire [0:0] i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_write;
    wire [63:0] i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_writedata;
    wire [31:0] i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_c1_exit_1_tpl;
    wire [2271:0] bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q;
    wire [31:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_b;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_c;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_d;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_e;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_f;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_g;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_h;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_i;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_j;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_k;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_l;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_m;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_n;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_o;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_p;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_r;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_s;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_t;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_u;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_v;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_w;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_x;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_y;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_z;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_aa;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_bb;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_cc;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_dd;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_ee;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_ff;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_gg;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_hh;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_ii;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_jj;
    wire [63:0] bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_kk;
    wire [31:0] bubble_join_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_q;
    wire [31:0] bubble_select_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_b;
    wire [0:0] SE_out_afs_abort_to_error_B1_start_merge_reg_wireValid;
    wire [0:0] SE_out_afs_abort_to_error_B1_start_merge_reg_wireStall;
    wire [0:0] SE_out_afs_abort_to_error_B1_start_merge_reg_StallValid;
    wire [0:0] SE_out_afs_abort_to_error_B1_start_merge_reg_toReg0;
    reg [0:0] SE_out_afs_abort_to_error_B1_start_merge_reg_fromReg0;
    wire [0:0] SE_out_afs_abort_to_error_B1_start_merge_reg_consumed0;
    wire [0:0] SE_out_afs_abort_to_error_B1_start_merge_reg_toReg1;
    reg [0:0] SE_out_afs_abort_to_error_B1_start_merge_reg_fromReg1;
    wire [0:0] SE_out_afs_abort_to_error_B1_start_merge_reg_consumed1;
    wire [0:0] SE_out_afs_abort_to_error_B1_start_merge_reg_or0;
    wire [0:0] SE_out_afs_abort_to_error_B1_start_merge_reg_backStall;
    wire [0:0] SE_out_afs_abort_to_error_B1_start_merge_reg_V0;
    wire [0:0] SE_out_afs_abort_to_error_B1_start_merge_reg_V1;
    wire [0:0] SE_out_i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_wireValid;
    wire [0:0] SE_out_i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_backStall;
    wire [0:0] SE_stall_entry_wireValid;
    wire [0:0] SE_stall_entry_backStall;
    wire [0:0] SE_stall_entry_V0;
    wire [0:0] SE_out_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_wireValid;
    wire [0:0] SE_out_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_backStall;
    wire [0:0] SE_out_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_V0;
    wire [0:0] SE_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_wireValid;
    wire [0:0] SE_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_backStall;
    wire [0:0] SE_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_V0;
    wire [0:0] SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_wireValid;
    wire [0:0] SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_wireStall;
    wire [0:0] SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_StallValid;
    wire [0:0] SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_toReg0;
    reg [0:0] SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_fromReg0;
    wire [0:0] SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_consumed0;
    wire [0:0] SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_toReg1;
    reg [0:0] SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_fromReg1;
    wire [0:0] SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_consumed1;
    wire [0:0] SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_or0;
    wire [0:0] SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_backStall;
    wire [0:0] SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_V0;
    wire [0:0] SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_V1;
    wire [0:0] SE_out_bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_wireValid;
    wire [0:0] SE_out_bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_and0;
    wire [0:0] SE_out_bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_backStall;
    wire [0:0] SE_out_bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_V0;
    wire [0:0] bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_valid_in;
    wire bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_valid_in_bitsignaltemp;
    wire [0:0] bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_stall_in;
    wire bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_stall_in_bitsignaltemp;
    wire [0:0] bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_valid_out;
    wire bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_valid_out_bitsignaltemp;
    wire [0:0] bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_stall_out;
    wire bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_stall_out_bitsignaltemp;


    // GND(CONSTANT,0)
    assign GND_q = $unsigned(1'b0);

    // bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x(BITJOIN,41)
    assign bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q = {i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_35_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_34_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_33_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_32_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_31_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_30_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_29_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_28_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_27_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_26_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_25_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_24_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_23_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_22_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_21_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_20_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_19_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_18_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_17_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_16_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_15_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_14_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_13_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_12_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_11_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_10_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_9_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_8_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_7_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_6_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_5_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_4_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_3_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_2_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_1_tpl, i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_0_tpl};

    // bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x(BITSELECT,42)
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_b = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[31:0]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_c = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[95:32]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_d = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[159:96]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_e = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[223:160]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_f = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[287:224]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_g = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[351:288]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_h = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[415:352]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_i = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[479:416]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_j = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[543:480]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_k = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[607:544]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_l = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[671:608]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_m = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[735:672]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_n = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[799:736]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_o = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[863:800]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_p = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[927:864]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[991:928]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_r = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[1055:992]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_s = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[1119:1056]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_t = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[1183:1120]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_u = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[1247:1184]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_v = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[1311:1248]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_w = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[1375:1312]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_x = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[1439:1376]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_y = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[1503:1440]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_z = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[1567:1504]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_aa = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[1631:1568]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_bb = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[1695:1632]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_cc = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[1759:1696]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_dd = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[1823:1760]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_ee = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[1887:1824]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_ff = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[1951:1888]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_gg = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[2015:1952]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_hh = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[2079:2016]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_ii = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[2143:2080]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_jj = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[2207:2144]);
    assign bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_kk = $unsigned(bubble_join_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q[2271:2208]);

    // SE_out_i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5(STALLENABLE,51)
    // Backward Stall generation
    assign SE_out_i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_backStall = $unsigned(1'b0);
    // Computing multiple Valid(s)
    assign SE_out_i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_wireValid = i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_out_o_valid;

    // bubble_join_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x(BITJOIN,45)
    assign bubble_join_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_q = i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_c1_exit_1_tpl;

    // bubble_select_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x(BITSELECT,46)
    assign bubble_select_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_b = $unsigned(bubble_join_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_q[31:0]);

    // i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5(BLACKBOX,9)@17
    // in in_i_stall@20000000
    // out out_iowr_bl_return_afs_abort_to_error_o_fifodata@20000000
    // out out_iowr_bl_return_afs_abort_to_error_o_fifovalid@20000000
    // out out_o_stall@20000000
    afs_abort_to_error_i_iowr_bl_return_unnaA000000Z_afs_abort_to_error0 thei_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5 (
        .in_i_data(bubble_select_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_b),
        .in_i_stall(SE_out_i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_backStall),
        .in_i_valid(SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_V1),
        .in_iowr_bl_return_afs_abort_to_error_i_fifoready(in_iowr_bl_return_afs_abort_to_error_i_fifoready),
        .out_iowr_bl_return_afs_abort_to_error_o_fifodata(i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_out_iowr_bl_return_afs_abort_to_error_o_fifodata),
        .out_iowr_bl_return_afs_abort_to_error_o_fifovalid(i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_out_iowr_bl_return_afs_abort_to_error_o_fifovalid),
        .out_o_ack(),
        .out_o_stall(i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_out_o_stall),
        .out_o_valid(i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_out_o_valid),
        .clock(clock),
        .resetn(resetn)
    );

    // bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg(STALLFIFO,78)
    assign bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_valid_in = SE_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_V0;
    assign bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_stall_in = SE_out_bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_backStall;
    assign bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_valid_in_bitsignaltemp = bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_valid_in[0];
    assign bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_stall_in_bitsignaltemp = bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_stall_in[0];
    assign bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_valid_out[0] = bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_valid_out_bitsignaltemp;
    assign bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_stall_out[0] = bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_stall_out_bitsignaltemp;
    acl_valid_fifo_counter #(
        .DEPTH(17),
        .STRICT_DEPTH(0),
        .ALLOW_FULL_WRITE(0),
        .ASYNC_RESET(1)
    ) thebubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg (
        .valid_in(bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_valid_in_bitsignaltemp),
        .stall_in(bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_stall_in_bitsignaltemp),
        .valid_out(bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_valid_out_bitsignaltemp),
        .stall_out(bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_stall_out_bitsignaltemp),
        .clock(clock),
        .resetn(resetn)
    );

    // SE_out_bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1(STALLENABLE,71)
    // Valid signal propagation
    assign SE_out_bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_V0 = SE_out_bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_wireValid;
    // Backward Stall generation
    assign SE_out_bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_backStall = in_stall_in | ~ (SE_out_bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_wireValid);
    // Computing multiple Valid(s)
    assign SE_out_bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_and0 = bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_valid_out;
    assign SE_out_bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_wireValid = SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_V0 & SE_out_bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_and0;

    // SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x(STALLENABLE,59)
    always @ (posedge clock or negedge resetn)
    begin
        if (!resetn)
        begin
            SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_fromReg0 <= '0;
            SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_fromReg1 <= '0;
        end
        else
        begin
            // Successor 0
            SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_fromReg0 <= SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_toReg0;
            // Successor 1
            SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_fromReg1 <= SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_toReg1;
        end
    end
    // Input Stall processing
    assign SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_consumed0 = (~ (SE_out_bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_backStall) & SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_wireValid) | SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_fromReg0;
    assign SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_consumed1 = (~ (i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_out_o_stall) & SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_wireValid) | SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_fromReg1;
    // Consuming
    assign SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_StallValid = SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_backStall & SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_wireValid;
    assign SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_toReg0 = SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_StallValid & SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_consumed0;
    assign SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_toReg1 = SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_StallValid & SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_consumed1;
    // Backward Stall generation
    assign SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_or0 = SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_consumed0;
    assign SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_wireStall = ~ (SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_consumed1 & SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_or0);
    assign SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_backStall = SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_wireStall;
    // Valid signal propagation
    assign SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_V0 = SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_wireValid & ~ (SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_fromReg0);
    assign SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_V1 = SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_wireValid & ~ (SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_fromReg1);
    // Computing multiple Valid(s)
    assign SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_wireValid = i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_o_valid;

    // i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x(BLACKBOX,36)@1
    // in in_i_stall@20000000
    // out out_o_stall@20000000
    // out out_o_valid@17
    // out out_pn1_afs_abort_to_error_avm_address@20000000
    // out out_pn1_afs_abort_to_error_avm_burstcount@20000000
    // out out_pn1_afs_abort_to_error_avm_byteenable@20000000
    // out out_pn1_afs_abort_to_error_avm_enable@20000000
    // out out_pn1_afs_abort_to_error_avm_read@20000000
    // out out_pn1_afs_abort_to_error_avm_write@20000000
    // out out_pn1_afs_abort_to_error_avm_writedata@20000000
    // out out_c1_exit_0_tpl@17
    // out out_c1_exit_1_tpl@17
    afs_abort_to_error_i_sfc_s_c1_in_wt_entrA000000Z_afs_abort_to_error3 thei_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x (
        .in_flush(in_flush),
        .in_i_stall(SE_out_i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_backStall),
        .in_i_valid(SE_out_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_V0),
        .in_pn1_afs_abort_to_error_avm_readdata(in_pn1_afs_abort_to_error_avm_readdata),
        .in_pn1_afs_abort_to_error_avm_readdatavalid(in_pn1_afs_abort_to_error_avm_readdatavalid),
        .in_pn1_afs_abort_to_error_avm_waitrequest(in_pn1_afs_abort_to_error_avm_waitrequest),
        .in_pn1_afs_abort_to_error_avm_writeack(in_pn1_afs_abort_to_error_avm_writeack),
        .in_c1_eni1_0_tpl(GND_q),
        .in_c1_eni1_1_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_b),
        .in_c1_eni1_2_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_c),
        .in_c1_eni1_3_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_d),
        .in_c1_eni1_4_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_e),
        .in_c1_eni1_5_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_f),
        .in_c1_eni1_6_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_g),
        .in_c1_eni1_7_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_h),
        .in_c1_eni1_8_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_i),
        .in_c1_eni1_9_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_j),
        .in_c1_eni1_10_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_k),
        .in_c1_eni1_11_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_l),
        .in_c1_eni1_12_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_m),
        .in_c1_eni1_13_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_n),
        .in_c1_eni1_14_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_o),
        .in_c1_eni1_15_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_p),
        .in_c1_eni1_16_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_q),
        .in_c1_eni1_17_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_r),
        .in_c1_eni1_18_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_s),
        .in_c1_eni1_19_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_t),
        .in_c1_eni1_20_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_u),
        .in_c1_eni1_21_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_v),
        .in_c1_eni1_22_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_w),
        .in_c1_eni1_23_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_x),
        .in_c1_eni1_24_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_y),
        .in_c1_eni1_25_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_z),
        .in_c1_eni1_26_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_aa),
        .in_c1_eni1_27_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_bb),
        .in_c1_eni1_28_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_cc),
        .in_c1_eni1_29_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_dd),
        .in_c1_eni1_30_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_ee),
        .in_c1_eni1_31_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_ff),
        .in_c1_eni1_32_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_gg),
        .in_c1_eni1_33_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_hh),
        .in_c1_eni1_34_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_ii),
        .in_c1_eni1_35_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_jj),
        .in_c1_eni1_36_tpl(bubble_select_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_kk),
        .out_o_stall(i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_o_stall),
        .out_o_valid(i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_o_valid),
        .out_pn1_afs_abort_to_error_avm_address(i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_address),
        .out_pn1_afs_abort_to_error_avm_burstcount(i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_burstcount),
        .out_pn1_afs_abort_to_error_avm_byteenable(i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_byteenable),
        .out_pn1_afs_abort_to_error_avm_enable(i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_enable),
        .out_pn1_afs_abort_to_error_avm_read(i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_read),
        .out_pn1_afs_abort_to_error_avm_write(i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_write),
        .out_pn1_afs_abort_to_error_avm_writedata(i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_writedata),
        .out_c1_exit_0_tpl(),
        .out_c1_exit_1_tpl(i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_c1_exit_1_tpl),
        .clock(clock),
        .resetn(resetn)
    );

    // SE_out_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x(STALLENABLE,55)
    // Valid signal propagation
    assign SE_out_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_V0 = SE_out_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_wireValid;
    // Backward Stall generation
    assign SE_out_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_backStall = i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_o_stall | ~ (SE_out_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_wireValid);
    // Computing multiple Valid(s)
    assign SE_out_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_wireValid = i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_valid;

    // i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x(BLACKBOX,34)@1
    // in in_i_stall@20000000
    // out out_iord_bl_call_afs_abort_to_error_o_fifoready@20000000
    // out out_o_stall@20000000
    afs_abort_to_error_i_iord_bl_call_unnameA000000Z_afs_abort_to_error0 thei_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x (
        .in_i_stall(SE_out_i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_backStall),
        .in_i_valid(SE_out_afs_abort_to_error_B1_start_merge_reg_V0),
        .in_iord_bl_call_afs_abort_to_error_i_fifodata(in_iord_bl_call_afs_abort_to_error_i_fifodata),
        .in_iord_bl_call_afs_abort_to_error_i_fifovalid(in_iord_bl_call_afs_abort_to_error_i_fifovalid),
        .out_iord_bl_call_afs_abort_to_error_o_fifoready(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_iord_bl_call_afs_abort_to_error_o_fifoready),
        .out_o_stall(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_stall),
        .out_o_valid(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_valid),
        .out_o_data_0_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_0_tpl),
        .out_o_data_1_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_1_tpl),
        .out_o_data_2_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_2_tpl),
        .out_o_data_3_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_3_tpl),
        .out_o_data_4_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_4_tpl),
        .out_o_data_5_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_5_tpl),
        .out_o_data_6_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_6_tpl),
        .out_o_data_7_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_7_tpl),
        .out_o_data_8_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_8_tpl),
        .out_o_data_9_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_9_tpl),
        .out_o_data_10_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_10_tpl),
        .out_o_data_11_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_11_tpl),
        .out_o_data_12_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_12_tpl),
        .out_o_data_13_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_13_tpl),
        .out_o_data_14_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_14_tpl),
        .out_o_data_15_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_15_tpl),
        .out_o_data_16_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_16_tpl),
        .out_o_data_17_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_17_tpl),
        .out_o_data_18_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_18_tpl),
        .out_o_data_19_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_19_tpl),
        .out_o_data_20_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_20_tpl),
        .out_o_data_21_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_21_tpl),
        .out_o_data_22_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_22_tpl),
        .out_o_data_23_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_23_tpl),
        .out_o_data_24_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_24_tpl),
        .out_o_data_25_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_25_tpl),
        .out_o_data_26_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_26_tpl),
        .out_o_data_27_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_27_tpl),
        .out_o_data_28_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_28_tpl),
        .out_o_data_29_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_29_tpl),
        .out_o_data_30_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_30_tpl),
        .out_o_data_31_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_31_tpl),
        .out_o_data_32_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_32_tpl),
        .out_o_data_33_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_33_tpl),
        .out_o_data_34_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_34_tpl),
        .out_o_data_35_tpl(i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_data_35_tpl),
        .clock(clock),
        .resetn(resetn)
    );

    // SE_stall_entry(STALLENABLE,52)
    // Valid signal propagation
    assign SE_stall_entry_V0 = SE_stall_entry_wireValid;
    // Backward Stall generation
    assign SE_stall_entry_backStall = afs_abort_to_error_B1_start_merge_reg_out_stall_out | ~ (SE_stall_entry_wireValid);
    // Computing multiple Valid(s)
    assign SE_stall_entry_wireValid = in_valid_in;

    // afs_abort_to_error_B1_start_merge_reg(BLACKBOX,2)@0
    // in in_stall_in@20000000
    // out out_data_out@1
    // out out_stall_out@20000000
    // out out_valid_out@1
    afs_abort_to_error_B1_start_merge_reg theafs_abort_to_error_B1_start_merge_reg (
        .in_data_in(GND_q),
        .in_stall_in(SE_out_afs_abort_to_error_B1_start_merge_reg_backStall),
        .in_valid_in(SE_stall_entry_V0),
        .out_data_out(),
        .out_stall_out(afs_abort_to_error_B1_start_merge_reg_out_stall_out),
        .out_valid_out(afs_abort_to_error_B1_start_merge_reg_out_valid_out),
        .clock(clock),
        .resetn(resetn)
    );

    // SE_out_afs_abort_to_error_B1_start_merge_reg(STALLENABLE,49)
    always @ (posedge clock or negedge resetn)
    begin
        if (!resetn)
        begin
            SE_out_afs_abort_to_error_B1_start_merge_reg_fromReg0 <= '0;
            SE_out_afs_abort_to_error_B1_start_merge_reg_fromReg1 <= '0;
        end
        else
        begin
            // Successor 0
            SE_out_afs_abort_to_error_B1_start_merge_reg_fromReg0 <= SE_out_afs_abort_to_error_B1_start_merge_reg_toReg0;
            // Successor 1
            SE_out_afs_abort_to_error_B1_start_merge_reg_fromReg1 <= SE_out_afs_abort_to_error_B1_start_merge_reg_toReg1;
        end
    end
    // Input Stall processing
    assign SE_out_afs_abort_to_error_B1_start_merge_reg_consumed0 = (~ (i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_o_stall) & SE_out_afs_abort_to_error_B1_start_merge_reg_wireValid) | SE_out_afs_abort_to_error_B1_start_merge_reg_fromReg0;
    assign SE_out_afs_abort_to_error_B1_start_merge_reg_consumed1 = (~ (i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_out_o_stall) & SE_out_afs_abort_to_error_B1_start_merge_reg_wireValid) | SE_out_afs_abort_to_error_B1_start_merge_reg_fromReg1;
    // Consuming
    assign SE_out_afs_abort_to_error_B1_start_merge_reg_StallValid = SE_out_afs_abort_to_error_B1_start_merge_reg_backStall & SE_out_afs_abort_to_error_B1_start_merge_reg_wireValid;
    assign SE_out_afs_abort_to_error_B1_start_merge_reg_toReg0 = SE_out_afs_abort_to_error_B1_start_merge_reg_StallValid & SE_out_afs_abort_to_error_B1_start_merge_reg_consumed0;
    assign SE_out_afs_abort_to_error_B1_start_merge_reg_toReg1 = SE_out_afs_abort_to_error_B1_start_merge_reg_StallValid & SE_out_afs_abort_to_error_B1_start_merge_reg_consumed1;
    // Backward Stall generation
    assign SE_out_afs_abort_to_error_B1_start_merge_reg_or0 = SE_out_afs_abort_to_error_B1_start_merge_reg_consumed0;
    assign SE_out_afs_abort_to_error_B1_start_merge_reg_wireStall = ~ (SE_out_afs_abort_to_error_B1_start_merge_reg_consumed1 & SE_out_afs_abort_to_error_B1_start_merge_reg_or0);
    assign SE_out_afs_abort_to_error_B1_start_merge_reg_backStall = SE_out_afs_abort_to_error_B1_start_merge_reg_wireStall;
    // Valid signal propagation
    assign SE_out_afs_abort_to_error_B1_start_merge_reg_V0 = SE_out_afs_abort_to_error_B1_start_merge_reg_wireValid & ~ (SE_out_afs_abort_to_error_B1_start_merge_reg_fromReg0);
    assign SE_out_afs_abort_to_error_B1_start_merge_reg_V1 = SE_out_afs_abort_to_error_B1_start_merge_reg_wireValid & ~ (SE_out_afs_abort_to_error_B1_start_merge_reg_fromReg1);
    // Computing multiple Valid(s)
    assign SE_out_afs_abort_to_error_B1_start_merge_reg_wireValid = afs_abort_to_error_B1_start_merge_reg_out_valid_out;

    // SE_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x(STALLENABLE,57)
    // Valid signal propagation
    assign SE_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_V0 = SE_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_wireValid;
    // Backward Stall generation
    assign SE_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_backStall = bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_reg_stall_out | ~ (SE_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_wireValid);
    // Computing multiple Valid(s)
    assign SE_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_wireValid = i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_out_o_valid;

    // i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x(BLACKBOX,35)@1
    // in in_i_stall@20000000
    // out out_aclp_to_limiter_i_llvm_fpga_pipeline_keep_going_afs_abort_to_error1_exiting_stall_out@20000000
    // out out_aclp_to_limiter_i_llvm_fpga_pipeline_keep_going_afs_abort_to_error1_exiting_valid_out@20000000
    // out out_o_stall@20000000
    // out out_pipeline_valid_out@20000000
    afs_abort_to_error_i_sfc_s_c0_in_wt_entrA000000Z_afs_abort_to_error0 thei_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x (
        .in_i_stall(SE_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_backStall),
        .in_i_valid(SE_out_afs_abort_to_error_B1_start_merge_reg_V1),
        .in_pipeline_stall_in(in_pipeline_stall_in),
        .in_unnamed_afs_abort_to_error0_0_tpl(GND_q),
        .out_aclp_to_limiter_i_llvm_fpga_pipeline_keep_going_afs_abort_to_error1_exiting_stall_out(i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_out_aclp_to_limiter_i_llvm_fpga_pipeline_keep_going_afs_abort_to_error1_exiting_stall_out),
        .out_aclp_to_limiter_i_llvm_fpga_pipeline_keep_going_afs_abort_to_error1_exiting_valid_out(i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_out_aclp_to_limiter_i_llvm_fpga_pipeline_keep_going_afs_abort_to_error1_exiting_valid_out),
        .out_o_stall(i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_out_o_stall),
        .out_o_valid(i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_out_o_valid),
        .out_pipeline_valid_out(i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_out_pipeline_valid_out),
        .out_c0_exit_0_tpl(),
        .out_c0_exit_1_tpl(),
        .clock(clock),
        .resetn(resetn)
    );

    // ext_sig_sync_out(GPOUT,8)
    assign out_aclp_to_limiter_i_llvm_fpga_pipeline_keep_going_afs_abort_to_error1_exiting_valid_out = i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_out_aclp_to_limiter_i_llvm_fpga_pipeline_keep_going_afs_abort_to_error1_exiting_valid_out;
    assign out_aclp_to_limiter_i_llvm_fpga_pipeline_keep_going_afs_abort_to_error1_exiting_stall_out = i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_out_aclp_to_limiter_i_llvm_fpga_pipeline_keep_going_afs_abort_to_error1_exiting_stall_out;

    // pipeline_valid_out_sync(GPOUT,21)
    assign out_pipeline_valid_out = i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_out_pipeline_valid_out;

    // sync_out(GPOUT,26)@0
    assign out_stall_out = SE_stall_entry_backStall;

    // dupName_0_ext_sig_sync_out_x(GPOUT,29)
    assign out_iord_bl_call_afs_abort_to_error_o_fifoready = i_iord_bl_call_afs_abort_to_error_unnamed_afs_abort_to_error2_afs_abort_to_error1_aunroll_x_out_iord_bl_call_afs_abort_to_error_o_fifoready;

    // dupName_0_sync_out_x(GPOUT,30)@17
    assign out_valid_out = SE_out_bubble_out_i_sfc_s_c0_in_wt_entry_afs_abort_to_errors_c0_enter1_afs_abort_to_error0_aunroll_x_1_V0;

    // dupName_1_ext_sig_sync_out_x(GPOUT,32)
    assign out_pn1_afs_abort_to_error_avm_address = i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_address;
    assign out_pn1_afs_abort_to_error_avm_enable = i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_enable;
    assign out_pn1_afs_abort_to_error_avm_read = i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_read;
    assign out_pn1_afs_abort_to_error_avm_write = i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_write;
    assign out_pn1_afs_abort_to_error_avm_writedata = i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_writedata;
    assign out_pn1_afs_abort_to_error_avm_byteenable = i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_byteenable;
    assign out_pn1_afs_abort_to_error_avm_burstcount = i_sfc_s_c1_in_wt_entry_afs_abort_to_errors_c1_enter_afs_abort_to_error3_aunroll_x_out_pn1_afs_abort_to_error_avm_burstcount;

    // dupName_2_ext_sig_sync_out_x(GPOUT,33)
    assign out_iowr_bl_return_afs_abort_to_error_o_fifodata = i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_out_iowr_bl_return_afs_abort_to_error_o_fifodata;
    assign out_iowr_bl_return_afs_abort_to_error_o_fifovalid = i_iowr_bl_return_afs_abort_to_error_unnamed_afs_abort_to_error3_afs_abort_to_error5_out_iowr_bl_return_afs_abort_to_error_o_fifovalid;

endmodule
