// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _cp50221_0212_ext_wctomb_HH_
#define _cp50221_0212_ext_wctomb_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct cp50221_0212_ext_wctomb : public sc_module {
    // Port declarations 14
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > conv;
    sc_out< sc_lv<10> > r_address0;
    sc_out< sc_logic > r_ce0;
    sc_out< sc_logic > r_we0;
    sc_out< sc_lv<8> > r_d0;
    sc_in< sc_lv<32> > wc;
    sc_in< sc_lv<64> > n;
    sc_out< sc_lv<32> > ap_return;


    // Module declarations
    cp50221_0212_ext_wctomb(sc_module_name name);
    SC_HAS_PROCESS(cp50221_0212_ext_wctomb);

    ~cp50221_0212_ext_wctomb();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<7> > select_ln114_fu_728_p3;
    sc_signal< sc_lv<1> > and_ln30_fu_410_p2;
    sc_signal< sc_lv<1> > icmp_ln32_fu_416_p2;
    sc_signal< sc_lv<1> > icmp_ln34_fu_422_p2;
    sc_signal< sc_lv<1> > icmp_ln36_fu_428_p2;
    sc_signal< sc_lv<1> > and_ln38_fu_446_p2;
    sc_signal< sc_lv<1> > icmp_ln40_fu_452_p2;
    sc_signal< sc_lv<1> > icmp_ln42_fu_458_p2;
    sc_signal< sc_lv<1> > icmp_ln44_fu_464_p2;
    sc_signal< sc_lv<1> > icmp_ln46_fu_470_p2;
    sc_signal< sc_lv<1> > icmp_ln48_fu_476_p2;
    sc_signal< sc_lv<1> > icmp_ln50_fu_482_p2;
    sc_signal< sc_lv<1> > icmp_ln52_fu_488_p2;
    sc_signal< sc_lv<1> > icmp_ln54_fu_494_p2;
    sc_signal< sc_lv<1> > icmp_ln56_fu_500_p2;
    sc_signal< sc_lv<1> > icmp_ln58_fu_506_p2;
    sc_signal< sc_lv<1> > icmp_ln60_fu_512_p2;
    sc_signal< sc_lv<1> > icmp_ln62_fu_518_p2;
    sc_signal< sc_lv<1> > icmp_ln64_fu_524_p2;
    sc_signal< sc_lv<1> > icmp_ln66_fu_530_p2;
    sc_signal< sc_lv<1> > and_ln68_fu_548_p2;
    sc_signal< sc_lv<1> > icmp_ln70_fu_554_p2;
    sc_signal< sc_lv<1> > icmp_ln72_fu_560_p2;
    sc_signal< sc_lv<1> > icmp_ln74_fu_566_p2;
    sc_signal< sc_lv<1> > and_ln76_fu_584_p2;
    sc_signal< sc_lv<1> > icmp_ln78_fu_590_p2;
    sc_signal< sc_lv<1> > icmp_ln80_fu_596_p2;
    sc_signal< sc_lv<1> > and_ln82_fu_614_p2;
    sc_signal< sc_lv<1> > icmp_ln84_fu_620_p2;
    sc_signal< sc_lv<1> > icmp_ln86_fu_626_p2;
    sc_signal< sc_lv<1> > icmp_ln88_fu_632_p2;
    sc_signal< sc_lv<1> > icmp_ln90_fu_638_p2;
    sc_signal< sc_lv<1> > icmp_ln92_fu_644_p2;
    sc_signal< sc_lv<1> > icmp_ln94_fu_650_p2;
    sc_signal< sc_lv<1> > icmp_ln96_fu_656_p2;
    sc_signal< sc_lv<1> > icmp_ln98_fu_662_p2;
    sc_signal< sc_lv<1> > icmp_ln100_fu_668_p2;
    sc_signal< sc_lv<1> > and_ln102_fu_686_p2;
    sc_signal< sc_lv<1> > icmp_ln104_fu_692_p2;
    sc_signal< sc_lv<1> > icmp_ln106_fu_698_p2;
    sc_signal< sc_lv<1> > icmp_ln108_fu_704_p2;
    sc_signal< sc_lv<1> > icmp_ln110_fu_710_p2;
    sc_signal< sc_lv<1> > icmp_ln112_fu_716_p2;
    sc_signal< sc_lv<7> > c_44_reg_217;
    sc_signal< sc_lv<1> > ap_phi_mux_p_0_phi_fu_390_p4;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln120_fu_741_p2;
    sc_signal< sc_lv<1> > icmp_ln30_fu_398_p2;
    sc_signal< sc_lv<1> > icmp_ln30_1_fu_404_p2;
    sc_signal< sc_lv<1> > icmp_ln38_fu_434_p2;
    sc_signal< sc_lv<1> > icmp_ln38_1_fu_440_p2;
    sc_signal< sc_lv<1> > icmp_ln68_fu_536_p2;
    sc_signal< sc_lv<1> > icmp_ln68_1_fu_542_p2;
    sc_signal< sc_lv<1> > icmp_ln76_fu_572_p2;
    sc_signal< sc_lv<1> > icmp_ln76_1_fu_578_p2;
    sc_signal< sc_lv<1> > icmp_ln82_fu_602_p2;
    sc_signal< sc_lv<1> > icmp_ln82_1_fu_608_p2;
    sc_signal< sc_lv<1> > icmp_ln102_fu_674_p2;
    sc_signal< sc_lv<1> > icmp_ln102_1_fu_680_p2;
    sc_signal< sc_lv<1> > icmp_ln114_fu_722_p2;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<7> ap_const_lv7_1B;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<7> ap_const_lv7_1C;
    static const sc_lv<7> ap_const_lv7_1D;
    static const sc_lv<7> ap_const_lv7_21;
    static const sc_lv<7> ap_const_lv7_22;
    static const sc_lv<7> ap_const_lv7_25;
    static const sc_lv<7> ap_const_lv7_26;
    static const sc_lv<7> ap_const_lv7_27;
    static const sc_lv<7> ap_const_lv7_28;
    static const sc_lv<7> ap_const_lv7_2A;
    static const sc_lv<7> ap_const_lv7_2B;
    static const sc_lv<7> ap_const_lv7_2C;
    static const sc_lv<7> ap_const_lv7_2D;
    static const sc_lv<7> ap_const_lv7_2F;
    static const sc_lv<7> ap_const_lv7_32;
    static const sc_lv<7> ap_const_lv7_35;
    static const sc_lv<7> ap_const_lv7_36;
    static const sc_lv<7> ap_const_lv7_39;
    static const sc_lv<7> ap_const_lv7_1A;
    static const sc_lv<7> ap_const_lv7_3C;
    static const sc_lv<7> ap_const_lv7_40;
    static const sc_lv<7> ap_const_lv7_45;
    static const sc_lv<7> ap_const_lv7_4B;
    static const sc_lv<7> ap_const_lv7_4D;
    static const sc_lv<7> ap_const_lv7_50;
    static const sc_lv<7> ap_const_lv7_52;
    static const sc_lv<7> ap_const_lv7_53;
    static const sc_lv<7> ap_const_lv7_54;
    static const sc_lv<7> ap_const_lv7_58;
    static const sc_lv<7> ap_const_lv7_5A;
    static const sc_lv<7> ap_const_lv7_5D;
    static const sc_lv<7> ap_const_lv7_66;
    static const sc_lv<7> ap_const_lv7_67;
    static const sc_lv<7> ap_const_lv7_68;
    static const sc_lv<7> ap_const_lv7_6A;
    static const sc_lv<7> ap_const_lv7_31;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<32> ap_const_lv32_216F;
    static const sc_lv<32> ap_const_lv32_2180;
    static const sc_lv<32> ap_const_lv32_4EFC;
    static const sc_lv<32> ap_const_lv32_50F4;
    static const sc_lv<32> ap_const_lv32_51EC;
    static const sc_lv<32> ap_const_lv32_52FF;
    static const sc_lv<32> ap_const_lv32_5328;
    static const sc_lv<32> ap_const_lv32_548A;
    static const sc_lv<32> ap_const_lv32_5759;
    static const sc_lv<32> ap_const_lv32_589E;
    static const sc_lv<32> ap_const_lv32_5BEC;
    static const sc_lv<32> ap_const_lv32_5CF5;
    static const sc_lv<32> ap_const_lv32_5D53;
    static const sc_lv<32> ap_const_lv32_5FB7;
    static const sc_lv<32> ap_const_lv32_6085;
    static const sc_lv<32> ap_const_lv32_6120;
    static const sc_lv<32> ap_const_lv32_654E;
    static const sc_lv<32> ap_const_lv32_6665;
    static const sc_lv<32> ap_const_lv32_6801;
    static const sc_lv<32> ap_const_lv32_6A6B;
    static const sc_lv<32> ap_const_lv32_6AE2;
    static const sc_lv<32> ap_const_lv32_6DEF;
    static const sc_lv<32> ap_const_lv32_6E00;
    static const sc_lv<32> ap_const_lv32_7028;
    static const sc_lv<32> ap_const_lv32_70BB;
    static const sc_lv<32> ap_const_lv32_7501;
    static const sc_lv<32> ap_const_lv32_767F;
    static const sc_lv<32> ap_const_lv32_76A0;
    static const sc_lv<32> ap_const_lv32_7930;
    static const sc_lv<32> ap_const_lv32_7AE7;
    static const sc_lv<32> ap_const_lv32_7D9F;
    static const sc_lv<32> ap_const_lv32_7DD8;
    static const sc_lv<32> ap_const_lv32_8362;
    static const sc_lv<32> ap_const_lv32_85B0;
    static const sc_lv<32> ap_const_lv32_8807;
    static const sc_lv<32> ap_const_lv32_8B7F;
    static const sc_lv<32> ap_const_lv32_8CF4;
    static const sc_lv<32> ap_const_lv32_8D76;
    static const sc_lv<32> ap_const_lv32_90DE;
    static const sc_lv<32> ap_const_lv32_9115;
    static const sc_lv<32> ap_const_lv32_9592;
    static const sc_lv<32> ap_const_lv32_9737;
    static const sc_lv<32> ap_const_lv32_9758;
    static const sc_lv<32> ap_const_lv32_999E;
    static const sc_lv<32> ap_const_lv32_9AD9;
    static const sc_lv<32> ap_const_lv32_9B72;
    static const sc_lv<32> ap_const_lv32_9ED1;
    static const sc_lv<32> ap_const_lv32_F929;
    static const sc_lv<32> ap_const_lv32_F9DC;
    static const sc_lv<7> ap_const_lv7_5E;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_and_ln102_fu_686_p2();
    void thread_and_ln30_fu_410_p2();
    void thread_and_ln38_fu_446_p2();
    void thread_and_ln68_fu_548_p2();
    void thread_and_ln76_fu_584_p2();
    void thread_and_ln82_fu_614_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_p_0_phi_fu_390_p4();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_icmp_ln100_fu_668_p2();
    void thread_icmp_ln102_1_fu_680_p2();
    void thread_icmp_ln102_fu_674_p2();
    void thread_icmp_ln104_fu_692_p2();
    void thread_icmp_ln106_fu_698_p2();
    void thread_icmp_ln108_fu_704_p2();
    void thread_icmp_ln110_fu_710_p2();
    void thread_icmp_ln112_fu_716_p2();
    void thread_icmp_ln114_fu_722_p2();
    void thread_icmp_ln120_fu_741_p2();
    void thread_icmp_ln30_1_fu_404_p2();
    void thread_icmp_ln30_fu_398_p2();
    void thread_icmp_ln32_fu_416_p2();
    void thread_icmp_ln34_fu_422_p2();
    void thread_icmp_ln36_fu_428_p2();
    void thread_icmp_ln38_1_fu_440_p2();
    void thread_icmp_ln38_fu_434_p2();
    void thread_icmp_ln40_fu_452_p2();
    void thread_icmp_ln42_fu_458_p2();
    void thread_icmp_ln44_fu_464_p2();
    void thread_icmp_ln46_fu_470_p2();
    void thread_icmp_ln48_fu_476_p2();
    void thread_icmp_ln50_fu_482_p2();
    void thread_icmp_ln52_fu_488_p2();
    void thread_icmp_ln54_fu_494_p2();
    void thread_icmp_ln56_fu_500_p2();
    void thread_icmp_ln58_fu_506_p2();
    void thread_icmp_ln60_fu_512_p2();
    void thread_icmp_ln62_fu_518_p2();
    void thread_icmp_ln64_fu_524_p2();
    void thread_icmp_ln66_fu_530_p2();
    void thread_icmp_ln68_1_fu_542_p2();
    void thread_icmp_ln68_fu_536_p2();
    void thread_icmp_ln70_fu_554_p2();
    void thread_icmp_ln72_fu_560_p2();
    void thread_icmp_ln74_fu_566_p2();
    void thread_icmp_ln76_1_fu_578_p2();
    void thread_icmp_ln76_fu_572_p2();
    void thread_icmp_ln78_fu_590_p2();
    void thread_icmp_ln80_fu_596_p2();
    void thread_icmp_ln82_1_fu_608_p2();
    void thread_icmp_ln82_fu_602_p2();
    void thread_icmp_ln84_fu_620_p2();
    void thread_icmp_ln86_fu_626_p2();
    void thread_icmp_ln88_fu_632_p2();
    void thread_icmp_ln90_fu_638_p2();
    void thread_icmp_ln92_fu_644_p2();
    void thread_icmp_ln94_fu_650_p2();
    void thread_icmp_ln96_fu_656_p2();
    void thread_icmp_ln98_fu_662_p2();
    void thread_r_address0();
    void thread_r_ce0();
    void thread_r_d0();
    void thread_r_we0();
    void thread_select_ln114_fu_728_p3();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
