
namespace eval poly6 {
  proc get_memory_files {QSYS_SIMDIR} {
    set memory_files [list]
    return $memory_files
  }
  
  proc get_common_design_files {QSYS_SIMDIR} {
    set design_files [dict create]
    return $design_files
  }
  
  proc get_design_files {QSYS_SIMDIR} {
    set design_files [dict create]
    dict set design_files "dspba_library_ver.sv"                                                    "$QSYS_SIMDIR/../poly6_internal_10/sim/dspba_library_ver.sv"                                                   
    dict set design_files "acl_data_fifo.v"                                                         "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_data_fifo.v"                                                        
    dict set design_files "acl_fifo.v"                                                              "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_fifo.v"                                                             
    dict set design_files "acl_altera_syncram_wrapped.sv"                                           "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_altera_syncram_wrapped.sv"                                          
    dict set design_files "acl_scfifo_wrapped.sv"                                                   "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_scfifo_wrapped.sv"                                                  
    dict set design_files "acl_ecc_decoder.sv"                                                      "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_ecc_decoder.sv"                                                     
    dict set design_files "acl_ecc_encoder.sv"                                                      "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_ecc_encoder.sv"                                                     
    dict set design_files "acl_ecc.svh"                                                             "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_ecc.svh"                                                            
    dict set design_files "acl_ll_fifo.v"                                                           "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_ll_fifo.v"                                                          
    dict set design_files "acl_ll_ram_fifo.v"                                                       "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_ll_ram_fifo.v"                                                      
    dict set design_files "acl_valid_fifo_counter.v"                                                "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_valid_fifo_counter.v"                                               
    dict set design_files "acl_dspba_valid_fifo_counter.v"                                          "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_dspba_valid_fifo_counter.v"                                         
    dict set design_files "acl_staging_reg.v"                                                       "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_staging_reg.v"                                                      
    dict set design_files "hld_fifo.sv"                                                             "$QSYS_SIMDIR/../poly6_internal_10/sim/hld_fifo.sv"                                                            
    dict set design_files "acl_mid_speed_fifo.sv"                                                   "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_mid_speed_fifo.sv"                                                  
    dict set design_files "acl_latency_one_ram_fifo.sv"                                             "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_latency_one_ram_fifo.sv"                                            
    dict set design_files "acl_latency_zero_ram_fifo.sv"                                            "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_latency_zero_ram_fifo.sv"                                           
    dict set design_files "hld_fifo_zero_width.sv"                                                  "$QSYS_SIMDIR/../poly6_internal_10/sim/hld_fifo_zero_width.sv"                                                 
    dict set design_files "acl_high_speed_fifo.sv"                                                  "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_high_speed_fifo.sv"                                                 
    dict set design_files "acl_low_latency_fifo.sv"                                                 "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_low_latency_fifo.sv"                                                
    dict set design_files "acl_zero_latency_fifo.sv"                                                "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_zero_latency_fifo.sv"                                               
    dict set design_files "acl_fanout_pipeline.sv"                                                  "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_fanout_pipeline.sv"                                                 
    dict set design_files "acl_std_synchronizer_nocut.v"                                            "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_std_synchronizer_nocut.v"                                           
    dict set design_files "acl_tessellated_incr_decr_threshold.sv"                                  "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_tessellated_incr_decr_threshold.sv"                                 
    dict set design_files "acl_tessellated_incr_lookahead.sv"                                       "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_tessellated_incr_lookahead.sv"                                      
    dict set design_files "acl_reset_handler.sv"                                                    "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_reset_handler.sv"                                                   
    dict set design_files "acl_lfsr.sv"                                                             "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_lfsr.sv"                                                            
    dict set design_files "acl_pop.v"                                                               "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_pop.v"                                                              
    dict set design_files "acl_push.v"                                                              "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_push.v"                                                             
    dict set design_files "acl_token_fifo_counter.v"                                                "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_token_fifo_counter.v"                                               
    dict set design_files "acl_pipeline.v"                                                          "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_pipeline.v"                                                         
    dict set design_files "acl_dspba_buffer.v"                                                      "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_dspba_buffer.v"                                                     
    dict set design_files "acl_enable_sink.v"                                                       "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_enable_sink.v"                                                      
    dict set design_files "st_top.v"                                                                "$QSYS_SIMDIR/../poly6_internal_10/sim/st_top.v"                                                               
    dict set design_files "acl_ffwdsrc.v"                                                           "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_ffwdsrc.v"                                                          
    dict set design_files "lsu_top.v"                                                               "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_top.v"                                                              
    dict set design_files "lsu_permute_address.v"                                                   "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_permute_address.v"                                                  
    dict set design_files "lsu_pipelined.v"                                                         "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_pipelined.v"                                                        
    dict set design_files "lsu_enabled.v"                                                           "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_enabled.v"                                                          
    dict set design_files "lsu_basic_coalescer.v"                                                   "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_basic_coalescer.v"                                                  
    dict set design_files "lsu_simple.v"                                                            "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_simple.v"                                                           
    dict set design_files "lsu_streaming.v"                                                         "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_streaming.v"                                                        
    dict set design_files "lsu_burst_master.v"                                                      "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_burst_master.v"                                                     
    dict set design_files "lsu_bursting_load_stores.v"                                              "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_bursting_load_stores.v"                                             
    dict set design_files "lsu_non_aligned_write.v"                                                 "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_non_aligned_write.v"                                                
    dict set design_files "lsu_read_cache.v"                                                        "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_read_cache.v"                                                       
    dict set design_files "lsu_atomic.v"                                                            "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_atomic.v"                                                           
    dict set design_files "lsu_prefetch_block.v"                                                    "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_prefetch_block.v"                                                   
    dict set design_files "lsu_wide_wrapper.v"                                                      "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_wide_wrapper.v"                                                     
    dict set design_files "lsu_streaming_prefetch.v"                                                "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_streaming_prefetch.v"                                               
    dict set design_files "acl_aligned_burst_coalesced_lsu.v"                                       "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_aligned_burst_coalesced_lsu.v"                                      
    dict set design_files "acl_toggle_detect.v"                                                     "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_toggle_detect.v"                                                    
    dict set design_files "acl_debug_mem.v"                                                         "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_debug_mem.v"                                                        
    dict set design_files "lsu_burst_coalesced_pipelined_write.sv"                                  "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_burst_coalesced_pipelined_write.sv"                                 
    dict set design_files "lsu_burst_coalesced_pipelined_read.sv"                                   "$QSYS_SIMDIR/../poly6_internal_10/sim/lsu_burst_coalesced_pipelined_read.sv"                                  
    dict set design_files "acl_fifo_stall_valid_lookahead.sv"                                       "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_fifo_stall_valid_lookahead.sv"                                      
    dict set design_files "acl_parameter_assert.svh"                                                "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_parameter_assert.svh"                                               
    dict set design_files "hld_global_load_store.sv"                                                "$QSYS_SIMDIR/../poly6_internal_10/sim/hld_global_load_store.sv"                                               
    dict set design_files "hld_lsu.sv"                                                              "$QSYS_SIMDIR/../poly6_internal_10/sim/hld_lsu.sv"                                                             
    dict set design_files "hld_lsu_burst_coalescer.sv"                                              "$QSYS_SIMDIR/../poly6_internal_10/sim/hld_lsu_burst_coalescer.sv"                                             
    dict set design_files "hld_lsu_coalescer_dynamic_timeout.sv"                                    "$QSYS_SIMDIR/../poly6_internal_10/sim/hld_lsu_coalescer_dynamic_timeout.sv"                                   
    dict set design_files "hld_lsu_data_aligner.sv"                                                 "$QSYS_SIMDIR/../poly6_internal_10/sim/hld_lsu_data_aligner.sv"                                                
    dict set design_files "hld_lsu_read_cache.sv"                                                   "$QSYS_SIMDIR/../poly6_internal_10/sim/hld_lsu_read_cache.sv"                                                  
    dict set design_files "hld_lsu_read_data_alignment.sv"                                          "$QSYS_SIMDIR/../poly6_internal_10/sim/hld_lsu_read_data_alignment.sv"                                         
    dict set design_files "hld_lsu_unaligned_controller.sv"                                         "$QSYS_SIMDIR/../poly6_internal_10/sim/hld_lsu_unaligned_controller.sv"                                        
    dict set design_files "hld_lsu_word_coalescer.sv"                                               "$QSYS_SIMDIR/../poly6_internal_10/sim/hld_lsu_word_coalescer.sv"                                              
    dict set design_files "hld_lsu_write_data_alignment.sv"                                         "$QSYS_SIMDIR/../poly6_internal_10/sim/hld_lsu_write_data_alignment.sv"                                        
    dict set design_files "hld_lsu_write_kernel_downstream.sv"                                      "$QSYS_SIMDIR/../poly6_internal_10/sim/hld_lsu_write_kernel_downstream.sv"                                     
    dict set design_files "acl_shift_register_no_reset.sv"                                          "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_shift_register_no_reset.sv"                                         
    dict set design_files "acl_full_detector.v"                                                     "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_full_detector.v"                                                    
    dict set design_files "acl_tessellated_incr_decr_decr.sv"                                       "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_tessellated_incr_decr_decr.sv"                                      
    dict set design_files "acl_ffwddst.sv"                                                          "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_ffwddst.sv"                                                         
    dict set design_files "acl_loop_limiter.v"                                                      "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_loop_limiter.v"                                                     
    dict set design_files "acl_reset_wire.v"                                                        "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_reset_wire.v"                                                       
    dict set design_files "poly6_function_wrapper.sv"                                               "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_function_wrapper.sv"                                              
    dict set design_files "poly6_function.sv"                                                       "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_function.sv"                                                      
    dict set design_files "poly6_bb_B0_runOnce.sv"                                                  "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B0_runOnce.sv"                                                 
    dict set design_files "poly6_bb_B0_runOnce_stall_region.sv"                                     "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B0_runOnce_stall_region.sv"                                    
    dict set design_files "poly6_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv"                           "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv"                          
    dict set design_files "poly6_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv"                       "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv"                      
    dict set design_files "poly6_i_llvm_fpga_push_token_i1_wt_limpush_0.sv"                         "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_token_i1_wt_limpush_0.sv"                        
    dict set design_files "poly6_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv"                     "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv"                    
    dict set design_files "poly6_B0_runOnce_merge_reg.sv"                                           "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B0_runOnce_merge_reg.sv"                                          
    dict set design_files "poly6_B0_runOnce_branch.sv"                                              "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B0_runOnce_branch.sv"                                             
    dict set design_files "poly6_B0_runOnce_merge.sv"                                               "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B0_runOnce_merge.sv"                                              
    dict set design_files "poly6_bb_B1_start.sv"                                                    "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B1_start.sv"                                                   
    dict set design_files "poly6_bb_B1_start_stall_region.sv"                                       "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B1_start_stall_region.sv"                                      
    dict set design_files "poly6_i_llvm_fpga_ffwd_source_i32_unnamed_3_poly60.sv"                   "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_ffwd_source_i32_unnamed_3_poly60.sv"                  
    dict set design_files "poly6_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv"                     "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv"                    
    dict set design_files "poly6_i_llvm_fpga_pop_throttle_i1_throttle_pop_1_reg.sv"                 "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pop_throttle_i1_throttle_pop_1_reg.sv"                
    dict set design_files "poly6_B1_start_merge_reg.sv"                                             "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B1_start_merge_reg.sv"                                            
    dict set design_files "poly6_i_iord_bl_call_unnamed_poly62_poly60.sv"                           "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_iord_bl_call_unnamed_poly62_poly60.sv"                          
    dict set design_files "poly6_i_sfc_s_c0_in_wt_entry_s_c0_enter2_poly60.sv"                      "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_sfc_s_c0_in_wt_entry_s_c0_enter2_poly60.sv"                     
    dict set design_files "poly6_i_llvm_fpga_sfc_exit_s_c0_out_wt_entry_s_c0_exit_poly60.sv"        "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_sfc_exit_s_c0_out_wt_entry_s_c0_exit_poly60.sv"       
    dict set design_files "poly6_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter2_poly60.sv"                "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter2_poly60.sv"               
    dict set design_files "poly6_i_llvm_fpga_pipeline_keep_going42_0.sv"                            "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pipeline_keep_going42_0.sv"                           
    dict set design_files "poly6_i_llvm_fpga_push_i1_notexitcond43_0.sv"                            "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_i1_notexitcond43_0.sv"                           
    dict set design_files "poly6_B1_start_branch.sv"                                                "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B1_start_branch.sv"                                               
    dict set design_files "poly6_B1_start_merge.sv"                                                 "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B1_start_merge.sv"                                                
    dict set design_files "poly6_bb_B2.sv"                                                          "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B2.sv"                                                         
    dict set design_files "poly6_bb_B2_stall_region.sv"                                             "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B2_stall_region.sv"                                            
    dict set design_files "poly6_B2_branch.sv"                                                      "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B2_branch.sv"                                                     
    dict set design_files "poly6_B2_merge.sv"                                                       "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B2_merge.sv"                                                      
    dict set design_files "poly6_bb_B3.sv"                                                          "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B3.sv"                                                         
    dict set design_files "poly6_bb_B3_stall_region.sv"                                             "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B3_stall_region.sv"                                            
    dict set design_files "poly6_i_sfc_s_c0_in_for_body_s_c0_enter503_poly61.sv"                    "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_sfc_s_c0_in_for_body_s_c0_enter503_poly61.sv"                   
    dict set design_files "poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_body_s_c0_exit52_poly60.sv"      "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_body_s_c0_exit52_poly60.sv"     
    dict set design_files "poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_A000000Zpoly61_full_detector.sv" "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_A000000Zpoly61_full_detector.sv"
    dict set design_files "poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_A000000Zt52_poly61_data_fifo.sv" "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_A000000Zt52_poly61_data_fifo.sv"
    dict set design_files "poly6_i_sfc_logic_s_c0_in_for_body_s_c0_enter503_poly60.sv"              "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_sfc_logic_s_c0_in_for_body_s_c0_enter503_poly60.sv"             
    dict set design_files "poly6_i_llvm_fpga_mem_memdep_1_0.sv"                                     "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_mem_memdep_1_0.sv"                                    
    dict set design_files "poly6_i_llvm_fpga_mem_memdep_2_0.sv"                                     "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_mem_memdep_2_0.sv"                                    
    dict set design_files "poly6_i_llvm_fpga_mem_memdep_3_0.sv"                                     "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_mem_memdep_3_0.sv"                                    
    dict set design_files "poly6_i_llvm_fpga_mem_memdep_0.sv"                                       "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_mem_memdep_0.sv"                                      
    dict set design_files "poly6_i_llvm_fpga_pipeline_keep_going26_0.sv"                            "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pipeline_keep_going26_0.sv"                           
    dict set design_files "poly6_i_llvm_fpga_pop_i11_fpga_indvars_iv_pop10_0.sv"                    "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pop_i11_fpga_indvars_iv_pop10_0.sv"                   
    dict set design_files "poly6_i_llvm_fpga_pop_i32_k_051_pop11_0.sv"                              "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pop_i32_k_051_pop11_0.sv"                             
    dict set design_files "poly6_i_llvm_fpga_pop_i4_cleanups29_pop13_0.sv"                          "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pop_i4_cleanups29_pop13_0.sv"                         
    dict set design_files "poly6_i_llvm_fpga_pop_i4_initerations24_pop12_0.sv"                      "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pop_i4_initerations24_pop12_0.sv"                     
    dict set design_files "poly6_i_llvm_fpga_push_i11_fpga_indvars_iv_push10_0.sv"                  "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_i11_fpga_indvars_iv_push10_0.sv"                 
    dict set design_files "poly6_i_llvm_fpga_push_i1_lastiniteration28_0.sv"                        "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_i1_lastiniteration28_0.sv"                       
    dict set design_files "poly6_i_llvm_fpga_push_i1_notexitcond36_0.sv"                            "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_i1_notexitcond36_0.sv"                           
    dict set design_files "poly6_i_llvm_fpga_push_i32_k_051_push11_0.sv"                            "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_i32_k_051_push11_0.sv"                           
    dict set design_files "poly6_i_llvm_fpga_push_i4_cleanups29_push13_0.sv"                        "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_i4_cleanups29_push13_0.sv"                       
    dict set design_files "poly6_i_llvm_fpga_push_i4_initerations24_push12_0.sv"                    "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_i4_initerations24_push12_0.sv"                   
    dict set design_files "poly6_B3_merge_reg.sv"                                                   "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B3_merge_reg.sv"                                                  
    dict set design_files "poly6_B3_branch.sv"                                                      "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B3_branch.sv"                                                     
    dict set design_files "poly6_B3_merge.sv"                                                       "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B3_merge.sv"                                                      
    dict set design_files "poly6_bb_B4.sv"                                                          "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B4.sv"                                                         
    dict set design_files "poly6_bb_B4_stall_region.sv"                                             "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B4_stall_region.sv"                                            
    dict set design_files "poly6_i_sfc_s_c0_in_for_cond14_preheader_s_c0_enter554_poly61.sv"        "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_sfc_s_c0_in_for_cond14_preheader_s_c0_enter554_poly61.sv"       
    dict set design_files "poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_A000000Zr_s_c0_exit59_poly60.sv" "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_A000000Zr_s_c0_exit59_poly60.sv"
    dict set design_files "poly6_i_sfc_logic_s_c0_in_for_cond14_preheader_s_c0_enter554_poly60.sv"  "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_sfc_logic_s_c0_in_for_cond14_preheader_s_c0_enter554_poly60.sv" 
    dict set design_files "poly6_i_llvm_fpga_pipeline_keep_going19_0.sv"                            "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pipeline_keep_going19_0.sv"                           
    dict set design_files "poly6_i_llvm_fpga_pop_i8_fpga_indvars_iv8_pop14_0.sv"                    "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pop_i8_fpga_indvars_iv8_pop14_0.sv"                   
    dict set design_files "poly6_i_llvm_fpga_push_i1_notexitcond20_0.sv"                            "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_i1_notexitcond20_0.sv"                           
    dict set design_files "poly6_i_llvm_fpga_push_i8_fpga_indvars_iv8_push14_0.sv"                  "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_i8_fpga_indvars_iv8_push14_0.sv"                 
    dict set design_files "poly6_B4_merge_reg.sv"                                                   "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B4_merge_reg.sv"                                                  
    dict set design_files "poly6_B4_branch.sv"                                                      "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B4_branch.sv"                                                     
    dict set design_files "poly6_B4_merge.sv"                                                       "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B4_merge.sv"                                                      
    dict set design_files "poly6_bb_B5.sv"                                                          "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B5.sv"                                                         
    dict set design_files "poly6_bb_B5_stall_region.sv"                                             "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B5_stall_region.sv"                                            
    dict set design_files "poly6_i_iowr_bl_return_unnamed_poly66_poly60.sv"                         "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_iowr_bl_return_unnamed_poly66_poly60.sv"                        
    dict set design_files "poly6_i_llvm_fpga_push_token_i1_throttle_push_0.sv"                      "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_token_i1_throttle_push_0.sv"                     
    dict set design_files "poly6_i_llvm_fpga_push_token_i1_throttle_push_3_reg.sv"                  "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_token_i1_throttle_push_3_reg.sv"                 
    dict set design_files "poly6_i_sfc_s_c0_in_for_cond_cleanup11_s_c0_enter62_poly60.sv"           "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_sfc_s_c0_in_for_cond_cleanup11_s_c0_enter62_poly60.sv"          
    dict set design_files "poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_A000000Z1_s_c0_exit64_poly60.sv" "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_A000000Z1_s_c0_exit64_poly60.sv"
    dict set design_files "poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_A000001Zpoly61_full_detector.sv" "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_A000001Zpoly61_full_detector.sv"
    dict set design_files "poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_A000000Zt64_poly61_data_fifo.sv" "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_A000000Zt64_poly61_data_fifo.sv"
    dict set design_files "poly6_i_sfc_logic_s_c0_in_for_cond_cleanup11_s_c0_enter62_poly60.sv"     "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_sfc_logic_s_c0_in_for_cond_cleanup11_s_c0_enter62_poly60.sv"    
    dict set design_files "poly6_i_llvm_fpga_ffwd_dest_i32_idx5413_0.sv"                            "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_ffwd_dest_i32_idx5413_0.sv"                           
    dict set design_files "poly6_i_llvm_fpga_mem_unnamed_5_poly60.sv"                               "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_mem_unnamed_5_poly60.sv"                              
    dict set design_files "poly6_B5_branch.sv"                                                      "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B5_branch.sv"                                                     
    dict set design_files "poly6_B5_merge.sv"                                                       "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B5_merge.sv"                                                      
    dict set design_files "poly6_bb_B6.sv"                                                          "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B6.sv"                                                         
    dict set design_files "poly6_bb_B6_stall_region.sv"                                             "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B6_stall_region.sv"                                            
    dict set design_files "poly6_B6_branch.sv"                                                      "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B6_branch.sv"                                                     
    dict set design_files "poly6_B6_merge.sv"                                                       "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B6_merge.sv"                                                      
    dict set design_files "poly6_bb_B7.sv"                                                          "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B7.sv"                                                         
    dict set design_files "poly6_bb_B7_stall_region.sv"                                             "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B7_stall_region.sv"                                            
    dict set design_files "poly6_i_sfc_s_c0_in_for_body17_s_c0_enter675_poly61.sv"                  "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_sfc_s_c0_in_for_body17_s_c0_enter675_poly61.sv"                 
    dict set design_files "poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_body17_s_c0_exit71_poly60.sv"    "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_body17_s_c0_exit71_poly60.sv"   
    dict set design_files "poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_A000002Zpoly61_full_detector.sv" "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_A000002Zpoly61_full_detector.sv"
    dict set design_files "poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_A000000Zt71_poly61_data_fifo.sv" "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_sfc_exit_s_c0_out_for_A000000Zt71_poly61_data_fifo.sv"
    dict set design_files "poly6_i_sfc_logic_s_c0_in_for_body17_s_c0_enter675_poly60.sv"            "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_sfc_logic_s_c0_in_for_body17_s_c0_enter675_poly60.sv"           
    dict set design_files "poly6_i_llvm_fpga_mem_memdep_4_0.sv"                                     "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_mem_memdep_4_0.sv"                                    
    dict set design_files "poly6_i_llvm_fpga_mem_unnamed_7_poly60.sv"                               "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_mem_unnamed_7_poly60.sv"                              
    dict set design_files "poly6_i_llvm_fpga_mem_unnamed_8_poly60.sv"                               "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_mem_unnamed_8_poly60.sv"                              
    dict set design_files "poly6_i_llvm_fpga_mem_unnamed_9_poly60.sv"                               "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_mem_unnamed_9_poly60.sv"                              
    dict set design_files "poly6_i_llvm_fpga_pipeline_keep_going_0.sv"                              "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pipeline_keep_going_0.sv"                             
    dict set design_files "poly6_i_llvm_fpga_pop_i11_fpga_indvars_iv5_pop15_0.sv"                   "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pop_i11_fpga_indvars_iv5_pop15_0.sv"                  
    dict set design_files "poly6_i_llvm_fpga_pop_i1_notcmp1746_pop18_0.sv"                          "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pop_i1_notcmp1746_pop18_0.sv"                         
    dict set design_files "poly6_i_llvm_fpga_pop_i2_cleanups_pop17_0.sv"                            "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pop_i2_cleanups_pop17_0.sv"                           
    dict set design_files "poly6_i_llvm_fpga_pop_i32_k13_049_pop16_0.sv"                            "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pop_i32_k13_049_pop16_0.sv"                           
    dict set design_files "poly6_i_llvm_fpga_push_i11_fpga_indvars_iv5_push15_0.sv"                 "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_i11_fpga_indvars_iv5_push15_0.sv"                
    dict set design_files "poly6_i_llvm_fpga_push_i1_lastiniteration_0.sv"                          "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_i1_lastiniteration_0.sv"                         
    dict set design_files "poly6_i_llvm_fpga_push_i1_notcmp1746_push18_0.sv"                        "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_i1_notcmp1746_push18_0.sv"                       
    dict set design_files "poly6_i_llvm_fpga_push_i1_notexitcond_0.sv"                              "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_i1_notexitcond_0.sv"                             
    dict set design_files "poly6_i_llvm_fpga_push_i2_cleanups_push17_0.sv"                          "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_i2_cleanups_push17_0.sv"                         
    dict set design_files "poly6_i_llvm_fpga_push_i32_k13_049_push16_0.sv"                          "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_push_i32_k13_049_push16_0.sv"                         
    dict set design_files "poly6_B7_merge_reg.sv"                                                   "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B7_merge_reg.sv"                                                  
    dict set design_files "poly6_B7_branch.sv"                                                      "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B7_branch.sv"                                                     
    dict set design_files "poly6_B7_merge.sv"                                                       "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_B7_merge.sv"                                                      
    dict set design_files "poly6_i_llvm_fpga_pipeline_keep_going19_2_sr.sv"                         "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pipeline_keep_going19_2_sr.sv"                        
    dict set design_files "poly6_i_llvm_fpga_pipeline_keep_going19_2_valid_fifo.sv"                 "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pipeline_keep_going19_2_valid_fifo.sv"                
    dict set design_files "poly6_i_llvm_fpga_pipeline_keep_going26_6_sr.sv"                         "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pipeline_keep_going26_6_sr.sv"                        
    dict set design_files "poly6_i_llvm_fpga_pipeline_keep_going26_6_valid_fifo.sv"                 "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pipeline_keep_going26_6_valid_fifo.sv"                
    dict set design_files "poly6_i_llvm_fpga_pipeline_keep_going42_1_sr.sv"                         "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pipeline_keep_going42_1_sr.sv"                        
    dict set design_files "poly6_i_llvm_fpga_pipeline_keep_going42_1_valid_fifo.sv"                 "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pipeline_keep_going42_1_valid_fifo.sv"                
    dict set design_files "poly6_i_llvm_fpga_pipeline_keep_going_6_sr.sv"                           "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pipeline_keep_going_6_sr.sv"                          
    dict set design_files "poly6_i_llvm_fpga_pipeline_keep_going_6_valid_fifo.sv"                   "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_i_llvm_fpga_pipeline_keep_going_6_valid_fifo.sv"                  
    dict set design_files "poly6_loop_limiter_0.sv"                                                 "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_loop_limiter_0.sv"                                                
    dict set design_files "poly6_loop_limiter_1.sv"                                                 "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_loop_limiter_1.sv"                                                
    dict set design_files "poly6_loop_limiter_2.sv"                                                 "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_loop_limiter_2.sv"                                                
    dict set design_files "poly6_bb_B2_sr_0.sv"                                                     "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B2_sr_0.sv"                                                    
    dict set design_files "poly6_bb_B3_sr_1.sv"                                                     "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B3_sr_1.sv"                                                    
    dict set design_files "poly6_bb_B4_sr_1.sv"                                                     "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B4_sr_1.sv"                                                    
    dict set design_files "poly6_bb_B5_sr_0.sv"                                                     "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B5_sr_0.sv"                                                    
    dict set design_files "poly6_bb_B6_sr_0.sv"                                                     "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B6_sr_0.sv"                                                    
    dict set design_files "poly6_bb_B7_sr_1.sv"                                                     "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_bb_B7_sr_1.sv"                                                    
    dict set design_files "acl_avm_to_ic.v"                                                         "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_avm_to_ic.v"                                                        
    dict set design_files "acl_mem1x.v"                                                             "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_mem1x.v"                                                            
    dict set design_files "acl_mem_staging_reg.v"                                                   "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_mem_staging_reg.v"                                                  
    dict set design_files "acl_ic_local_mem_router.v"                                               "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_ic_local_mem_router.v"                                              
    dict set design_files "acl_ic_master_endpoint.v"                                                "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_ic_master_endpoint.v"                                               
    dict set design_files "acl_arb_intf.v"                                                          "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_arb_intf.v"                                                         
    dict set design_files "acl_ic_intf.v"                                                           "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_ic_intf.v"                                                          
    dict set design_files "acl_ic_slave_endpoint.v"                                                 "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_ic_slave_endpoint.v"                                                
    dict set design_files "acl_ic_slave_rrp.v"                                                      "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_ic_slave_rrp.v"                                                     
    dict set design_files "acl_ic_slave_wrp.v"                                                      "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_ic_slave_wrp.v"                                                     
    dict set design_files "acl_arb2.v"                                                              "$QSYS_SIMDIR/../poly6_internal_10/sim/acl_arb2.v"                                                             
    dict set design_files "poly6_internal.v"                                                        "$QSYS_SIMDIR/../poly6_internal_10/sim/poly6_internal.v"                                                       
    dict set design_files "poly6.v"                                                                 "$QSYS_SIMDIR/poly6.v"                                                                                         
    return $design_files
  }
  
  proc get_elab_options {SIMULATOR_TOOL_BITNESS} {
    set ELAB_OPTIONS ""
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    return $ELAB_OPTIONS
  }
  
  
  proc get_sim_options {SIMULATOR_TOOL_BITNESS} {
    set SIM_OPTIONS ""
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    return $SIM_OPTIONS
  }
  
  
  proc get_env_variables {SIMULATOR_TOOL_BITNESS} {
    set ENV_VARIABLES [dict create]
    set LD_LIBRARY_PATH [dict create]
    dict set ENV_VARIABLES "LD_LIBRARY_PATH" $LD_LIBRARY_PATH
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    return $ENV_VARIABLES
  }
  
  
}
