-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ubc_check is
port (
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    W_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    W_ce0 : OUT STD_LOGIC;
    W_we0 : OUT STD_LOGIC;
    W_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    W_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    W_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    W_ce1 : OUT STD_LOGIC;
    W_we1 : OUT STD_LOGIC;
    W_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    W_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    dvmask_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    dvmask_ce0 : OUT STD_LOGIC;
    dvmask_we0 : OUT STD_LOGIC;
    dvmask_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of ubc_check is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ubc_check,hls_ip_2019_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k160t-fbg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.425000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0,HLS_VERSION=2019_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";



begin



    W_address0 <= ap_const_lv7_0;
    W_address1 <= ap_const_lv7_0;
    W_ce0 <= ap_const_logic_0;
    W_ce1 <= ap_const_logic_0;
    W_d0 <= ap_const_lv32_0;
    W_d1 <= ap_const_lv32_0;
    W_we0 <= ap_const_logic_0;
    W_we1 <= ap_const_logic_0;
    ap_done <= ap_start;
    ap_idle <= ap_const_logic_1;
    ap_ready <= ap_start;
    dvmask_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    dvmask_ce0_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_1)) then 
            dvmask_ce0 <= ap_const_logic_1;
        else 
            dvmask_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dvmask_d0 <= ap_const_lv32_FFFFFFFF;

    dvmask_we0_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_1)) then 
            dvmask_we0 <= ap_const_logic_1;
        else 
            dvmask_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
