#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("tpg_src_width", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("tpg_src_height", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("tpg_vid_aspect", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("tpg_pix_aspect", 32, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("tpg_border_left", 32, hls_out, 4, "ap_vld", "out_data", 1),
	Port_Property("tpg_border_left_ap_vld", 1, hls_out, 4, "ap_vld", "out_vld", 1),
	Port_Property("tpg_border_width", 32, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("tpg_border_width_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("tpg_border_top", 32, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("tpg_border_top_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("tpg_border_height", 32, hls_out, 7, "ap_vld", "out_data", 1),
	Port_Property("tpg_border_height_ap_vld", 1, hls_out, 7, "ap_vld", "out_vld", 1),
	Port_Property("tpg_square_width", 32, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("tpg_square_width_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
	Port_Property("tpg_square_left", 32, hls_out, 9, "ap_vld", "out_data", 1),
	Port_Property("tpg_square_left_ap_vld", 1, hls_out, 9, "ap_vld", "out_vld", 1),
	Port_Property("tpg_square_height", 32, hls_out, 10, "ap_vld", "out_data", 1),
	Port_Property("tpg_square_height_ap_vld", 1, hls_out, 10, "ap_vld", "out_vld", 1),
	Port_Property("tpg_square_top", 32, hls_out, 11, "ap_vld", "out_data", 1),
	Port_Property("tpg_square_top_ap_vld", 1, hls_out, 11, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "tpg_calculate_square_border";
