package require -exact qsys 15.0
set_module_property NAME prod_matrix_internal
set_module_property VERSION 1.0
set_module_property INTERNAL true
set_module_property GROUP HLS
set_module_property DISPLAY_NAME prod_matrix_internal
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property SUPPORTED_DEVICE_FAMILIES {"Arria 10"}
set_module_assignment hls.cosim.name {_Z11prod_matrixPA100_iS0_ii}
set_module_assignment hls.compressed.name {prod_matrix}

#### Synthesis fileset
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL prod_matrix_internal
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file "dspba_library_ver.sv" SYSTEM_VERILOG PATH "linux64/lib/dspba/Libraries/sv/base/dspba_library_ver.sv"
add_fileset_file "acl_data_fifo.v" SYSTEM_VERILOG PATH "ip/acl_data_fifo.v"
add_fileset_file "acl_fifo.v" SYSTEM_VERILOG PATH "ip/acl_fifo.v"
add_fileset_file "acl_altera_syncram_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_altera_syncram_wrapped.sv"
add_fileset_file "acl_scfifo_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_scfifo_wrapped.sv"
add_fileset_file "acl_ecc_decoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_decoder.sv"
add_fileset_file "acl_ecc_encoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_encoder.sv"
add_fileset_file "acl_ecc.svh" SYSTEM_VERILOG PATH "ip/acl_ecc.svh"
add_fileset_file "acl_ll_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_fifo.v"
add_fileset_file "acl_ll_ram_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_ram_fifo.v"
add_fileset_file "acl_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_valid_fifo_counter.v"
add_fileset_file "acl_dspba_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_dspba_valid_fifo_counter.v"
add_fileset_file "acl_staging_reg.v" SYSTEM_VERILOG PATH "ip/acl_staging_reg.v"
add_fileset_file "hld_fifo.sv" SYSTEM_VERILOG PATH "ip/hld_fifo.sv"
add_fileset_file "acl_mid_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_mid_speed_fifo.sv"
add_fileset_file "acl_latency_one_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_one_ram_fifo.sv"
add_fileset_file "acl_latency_zero_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_zero_ram_fifo.sv"
add_fileset_file "hld_fifo_zero_width.sv" SYSTEM_VERILOG PATH "ip/hld_fifo_zero_width.sv"
add_fileset_file "acl_high_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_high_speed_fifo.sv"
add_fileset_file "acl_low_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_low_latency_fifo.sv"
add_fileset_file "acl_zero_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_zero_latency_fifo.sv"
add_fileset_file "acl_fanout_pipeline.sv" SYSTEM_VERILOG PATH "ip/acl_fanout_pipeline.sv"
add_fileset_file "acl_std_synchronizer_nocut.v" SYSTEM_VERILOG PATH "ip/acl_std_synchronizer_nocut.v"
add_fileset_file "acl_tessellated_incr_decr_threshold.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_threshold.sv"
add_fileset_file "acl_tessellated_incr_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_lookahead.sv"
add_fileset_file "acl_reset_handler.sv" SYSTEM_VERILOG PATH "ip/acl_reset_handler.sv"
add_fileset_file "acl_lfsr.sv" SYSTEM_VERILOG PATH "ip/acl_lfsr.sv"
add_fileset_file "acl_pop.v" SYSTEM_VERILOG PATH "ip/acl_pop.v"
add_fileset_file "acl_push.v" SYSTEM_VERILOG PATH "ip/acl_push.v"
add_fileset_file "acl_token_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_token_fifo_counter.v"
add_fileset_file "acl_pipeline.v" SYSTEM_VERILOG PATH "ip/acl_pipeline.v"
add_fileset_file "acl_dspba_buffer.v" SYSTEM_VERILOG PATH "ip/acl_dspba_buffer.v"
add_fileset_file "acl_enable_sink.v" SYSTEM_VERILOG PATH "ip/acl_enable_sink.v"
add_fileset_file "st_top.v" SYSTEM_VERILOG PATH "ip/st_top.v"
add_fileset_file "acl_ffwdsrc.v" SYSTEM_VERILOG PATH "ip/acl_ffwdsrc.v"
add_fileset_file "acl_ffwddst.sv" SYSTEM_VERILOG PATH "ip/acl_ffwddst.sv"
add_fileset_file "acl_full_detector.v" SYSTEM_VERILOG PATH "ip/acl_full_detector.v"
add_fileset_file "acl_tessellated_incr_decr_decr.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_decr.sv"
add_fileset_file "lsu_top.v" SYSTEM_VERILOG PATH "ip/lsu_top.v"
add_fileset_file "lsu_permute_address.v" SYSTEM_VERILOG PATH "ip/lsu_permute_address.v"
add_fileset_file "lsu_pipelined.v" SYSTEM_VERILOG PATH "ip/lsu_pipelined.v"
add_fileset_file "lsu_enabled.v" SYSTEM_VERILOG PATH "ip/lsu_enabled.v"
add_fileset_file "lsu_basic_coalescer.v" SYSTEM_VERILOG PATH "ip/lsu_basic_coalescer.v"
add_fileset_file "lsu_simple.v" SYSTEM_VERILOG PATH "ip/lsu_simple.v"
add_fileset_file "lsu_streaming.v" SYSTEM_VERILOG PATH "ip/lsu_streaming.v"
add_fileset_file "lsu_burst_master.v" SYSTEM_VERILOG PATH "ip/lsu_burst_master.v"
add_fileset_file "lsu_bursting_load_stores.v" SYSTEM_VERILOG PATH "ip/lsu_bursting_load_stores.v"
add_fileset_file "lsu_non_aligned_write.v" SYSTEM_VERILOG PATH "ip/lsu_non_aligned_write.v"
add_fileset_file "lsu_read_cache.v" SYSTEM_VERILOG PATH "ip/lsu_read_cache.v"
add_fileset_file "lsu_atomic.v" SYSTEM_VERILOG PATH "ip/lsu_atomic.v"
add_fileset_file "lsu_prefetch_block.v" SYSTEM_VERILOG PATH "ip/lsu_prefetch_block.v"
add_fileset_file "lsu_wide_wrapper.v" SYSTEM_VERILOG PATH "ip/lsu_wide_wrapper.v"
add_fileset_file "lsu_streaming_prefetch.v" SYSTEM_VERILOG PATH "ip/lsu_streaming_prefetch.v"
add_fileset_file "acl_aligned_burst_coalesced_lsu.v" SYSTEM_VERILOG PATH "ip/acl_aligned_burst_coalesced_lsu.v"
add_fileset_file "acl_toggle_detect.v" SYSTEM_VERILOG PATH "ip/acl_toggle_detect.v"
add_fileset_file "acl_debug_mem.v" SYSTEM_VERILOG PATH "ip/acl_debug_mem.v"
add_fileset_file "lsu_burst_coalesced_pipelined_write.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_write.sv"
add_fileset_file "lsu_burst_coalesced_pipelined_read.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_read.sv"
add_fileset_file "acl_fifo_stall_valid_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_fifo_stall_valid_lookahead.sv"
add_fileset_file "acl_parameter_assert.svh" SYSTEM_VERILOG PATH "ip/acl_parameter_assert.svh"
add_fileset_file "hld_global_load_store.sv" SYSTEM_VERILOG PATH "ip/hld_global_load_store.sv"
add_fileset_file "hld_lsu.sv" SYSTEM_VERILOG PATH "ip/hld_lsu.sv"
add_fileset_file "hld_lsu_burst_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_burst_coalescer.sv"
add_fileset_file "hld_lsu_coalescer_dynamic_timeout.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_coalescer_dynamic_timeout.sv"
add_fileset_file "hld_lsu_data_aligner.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_data_aligner.sv"
add_fileset_file "hld_lsu_read_cache.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_cache.sv"
add_fileset_file "hld_lsu_read_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_data_alignment.sv"
add_fileset_file "hld_lsu_unaligned_controller.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_unaligned_controller.sv"
add_fileset_file "hld_lsu_word_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_word_coalescer.sv"
add_fileset_file "hld_lsu_write_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_data_alignment.sv"
add_fileset_file "hld_lsu_write_kernel_downstream.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_kernel_downstream.sv"
add_fileset_file "acl_shift_register_no_reset.sv" SYSTEM_VERILOG PATH "ip/acl_shift_register_no_reset.sv"
add_fileset_file "acl_loop_limiter.v" SYSTEM_VERILOG PATH "ip/acl_loop_limiter.v"
add_fileset_file "acl_reset_wire.v" SYSTEM_VERILOG PATH "ip/acl_reset_wire.v"
add_fileset_file "prod_matrix_function_wrapper.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_function_wrapper.sv"
add_fileset_file "prod_matrix_function.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_function.sv"
add_fileset_file "prod_matrix_bb_B0_runOnce.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B0_runOnce.sv"
add_fileset_file "prod_matrix_bb_B0_runOnce_stall_region.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B0_runOnce_stall_region.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_token_i1_wt_limpush_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_token_i1_wt_limpush_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv"
add_fileset_file "prod_matrix_B0_runOnce_merge_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B0_runOnce_merge_reg.sv"
add_fileset_file "prod_matrix_B0_runOnce_branch.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B0_runOnce_branch.sv"
add_fileset_file "prod_matrix_B0_runOnce_merge.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B0_runOnce_merge.sv"
add_fileset_file "prod_matrix_bb_B1_start.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B1_start.sv"
add_fileset_file "prod_matrix_bb_B1_start_stall_region.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B1_start_stall_region.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_source_i1_unnamed_5_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_source_i1_unnamed_5_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_source_i1_unnamed_6_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_source_i1_unnamed_6_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_source_i33_unnamed_7_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_source_i33_unnamed_7_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_source_i33_unnamed_8_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_source_i33_unnamed_8_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_source_p102A000000Znamed_3_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_source_p102A000000Znamed_3_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_source_p102A000000Znamed_4_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_source_p102A000000Znamed_4_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_throttle_i1_throttle_pop_1_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_throttle_i1_throttle_pop_1_reg.sv"
add_fileset_file "prod_matrix_B1_start_merge_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B1_start_merge_reg.sv"
add_fileset_file "prod_matrix_i_iord_bl_call_unnamed_prod_matrix2_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_iord_bl_call_unnamed_prod_matrix2_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_sfc_s_c0_in_wt_entry_s_c0_enter9_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_sfc_s_c0_in_wt_entry_s_c0_enter9_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Zc0_exit_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Zc0_exit_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter9_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter9_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going31_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going31_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notexitcond32_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notexitcond32_0.sv"
add_fileset_file "prod_matrix_B1_start_branch.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B1_start_branch.sv"
add_fileset_file "prod_matrix_B1_start_merge.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B1_start_merge.sv"
add_fileset_file "prod_matrix_bb_B2.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B2.sv"
add_fileset_file "prod_matrix_bb_B2_stall_region.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B2_stall_region.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop12_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop12_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop12_3_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop12_3_reg.sv"
add_fileset_file "prod_matrix_i_sfc_s_c0_in_for_cond1_prehA000000Zter6710_prod_matrix1.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_sfc_s_c0_in_for_cond1_prehA000000Zter6710_prod_matrix1.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Z_exit69_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Z_exit69_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Zatrix1_full_detector.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Zatrix1_full_detector.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Zod_matrix1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Zod_matrix1_data_fifo.sv"
add_fileset_file "prod_matrix_i_sfc_logic_s_c0_in_for_condA000000Zter6710_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_sfc_logic_s_c0_in_for_condA000000Zter6710_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_i1_cmp2017_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_i1_cmp2017_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_i33_unnamed_9_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_i33_unnamed_9_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going27_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going27_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_i_021_pop11_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_i_021_pop11_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i33_fpga_indvars_iv11_pop10_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i33_fpga_indvars_iv11_pop10_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notexitcond28_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notexitcond28_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_i_021_push11_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_i_021_push11_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i33_fpga_indvars_iv11_push10_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i33_fpga_indvars_iv11_push10_0.sv"
add_fileset_file "prod_matrix_B2_merge_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B2_merge_reg.sv"
add_fileset_file "prod_matrix_B2_branch.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B2_branch.sv"
add_fileset_file "prod_matrix_B2_merge.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B2_merge.sv"
add_fileset_file "prod_matrix_bb_B3.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B3.sv"
add_fileset_file "prod_matrix_bb_B3_stall_region.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B3_stall_region.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi3_pop15_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi3_pop15_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi3_pop15_3_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi3_pop15_3_reg.sv"
add_fileset_file "prod_matrix_i_sfc_s_c0_in_for_body6_lr_pA000000Zter7211_prod_matrix1.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_sfc_s_c0_in_for_body6_lr_pA000000Zter7211_prod_matrix1.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Z_exit78_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Z_exit78_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000001Zatrix1_full_detector.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000001Zatrix1_full_detector.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000001Zod_matrix1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000001Zod_matrix1_data_fifo.sv"
add_fileset_file "prod_matrix_i_sfc_logic_s_c0_in_for_bodyA000000Zter7211_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_sfc_logic_s_c0_in_for_bodyA000000Zter7211_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_i1_unnamed_12_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_i1_unnamed_12_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_i33_unnamed_11_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_i33_unnamed_11_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going23_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going23_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop1238_pop19_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop1238_pop19_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_notcmp2634_pop17_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_notcmp2634_pop17_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_pop16_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_pop16_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_i_021_pop1136_pop18_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_i_021_pop1136_pop18_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_j_018_pop14_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_j_018_pop14_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i33_fpga_indvars_iv8_pop13_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i33_fpga_indvars_iv8_pop13_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_pop1238_push19_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_pop1238_push19_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notcmp2634_push17_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notcmp2634_push17_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notexitcond24_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notexitcond24_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_push16_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_push16_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_i_021_pop1136_push18_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_i_021_pop1136_push18_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_j_018_push14_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_j_018_push14_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i33_fpga_indvars_iv8_push13_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i33_fpga_indvars_iv8_push13_0.sv"
add_fileset_file "prod_matrix_B3_merge_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B3_merge_reg.sv"
add_fileset_file "prod_matrix_B3_branch.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B3_branch.sv"
add_fileset_file "prod_matrix_B3_merge.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B3_merge.sv"
add_fileset_file "prod_matrix_bb_B4.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B4.sv"
add_fileset_file "prod_matrix_bb_B4_stall_region.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B4_stall_region.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_i1_unnamed_15_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_i1_unnamed_15_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_i1_unnamed_16_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_i1_unnamed_16_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_i33_unnamed_14_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_i33_unnamed_14_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_p1024a100i32_r2416_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_p1024a100i32_r2416_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_p1024a100i32_v2314_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_p1024a100i32_v2314_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_p1024a100i32_v2315_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_p1024a100i32_v2315_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_mem_lm1_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_mem_lm1_0.sv"
add_fileset_file "prod_matrix_readdata_reg_lm1_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_readdata_reg_lm1_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_mem_lm82_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_mem_lm82_0.sv"
add_fileset_file "prod_matrix_readdata_reg_lm82_1.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_readdata_reg_lm82_1.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_mem_memdep_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_mem_memdep_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going_4_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going_4_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi3_pop1542_pop31_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi3_pop1542_pop31_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi3_pop1542_pop31_25_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi3_pop1542_pop31_25_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop1239_pop27_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop1239_pop27_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop1239_pop27_23_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop1239_pop27_23_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi_pop22_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi_pop22_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi_pop22_28_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi_pop22_28_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_notcmp2240_pop29_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_notcmp2240_pop29_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_notcmp2240_pop29_58_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_notcmp2240_pop29_58_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_notcmp2635_pop25_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_notcmp2635_pop25_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_notcmp2635_pop25_54_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_notcmp2635_pop25_54_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_pop24_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_pop24_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_pop24_52_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_pop24_52_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_pop28_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_pop28_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_pop28_56_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_pop28_56_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i2_cleanups_pop23_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i2_cleanups_pop23_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i2_cleanups_pop23_0_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i2_cleanups_pop23_0_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_i_021_pop1137_pop26_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_i_021_pop1137_pop26_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_i_021_pop1137_pop26_12_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_i_021_pop1137_pop26_12_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_j_018_pop1441_pop30_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_j_018_pop1441_pop30_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_j_018_pop1441_pop30_9_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_j_018_pop1441_pop30_9_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_k_016_pop21_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_k_016_pop21_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_k_016_pop21_19_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_k_016_pop21_19_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i33_fpga_indvars_iv_pop20_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i33_fpga_indvars_iv_pop20_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i33_fpga_indvars_iv_pop20_7_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i33_fpga_indvars_iv_pop20_7_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_lastiniteration_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_lastiniteration_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_lastiniteration_5_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_lastiniteration_5_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi3_pop1542_push31_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi3_pop1542_push31_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi3_pop1542_push31_26_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi3_pop1542_push31_26_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_pop1239_push27_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_pop1239_push27_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_pop1239_push27_24_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_pop1239_push27_24_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi_push22_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi_push22_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi_push22_37_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi_push22_37_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notcmp2240_push29_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notcmp2240_push29_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notcmp2240_push29_59_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notcmp2240_push29_59_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notcmp2635_push25_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notcmp2635_push25_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notcmp2635_push25_55_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notcmp2635_push25_55_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notexitcond_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notexitcond_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notexitcond_47_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notexitcond_47_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_push24_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_push24_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_push24_53_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_push24_53_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_push28_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_push28_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_push28_57_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_push28_57_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i2_cleanups_push23_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i2_cleanups_push23_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i2_cleanups_push23_50_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i2_cleanups_push23_50_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_i_021_pop1137_push26_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_i_021_pop1137_push26_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_i_021_pop1137_push26_13_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_i_021_pop1137_push26_13_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_j_018_pop1441_push30_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_j_018_pop1441_push30_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_j_018_pop1441_push30_10_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_j_018_pop1441_push30_10_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_k_016_push21_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_k_016_push21_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_k_016_push21_39_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_k_016_push21_39_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i33_fpga_indvars_iv_push20_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i33_fpga_indvars_iv_push20_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i33_fpga_indvars_iv_push20_43_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i33_fpga_indvars_iv_push20_43_reg.sv"
add_fileset_file "prod_matrix_B4_merge_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B4_merge_reg.sv"
add_fileset_file "prod_matrix_B4_branch.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B4_branch.sv"
add_fileset_file "prod_matrix_B4_merge.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B4_merge.sv"
add_fileset_file "prod_matrix_bb_B5.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B5.sv"
add_fileset_file "prod_matrix_bb_B5_stall_region.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B5_stall_region.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi3_push15_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi3_push15_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi3_push15_0_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi3_push15_0_reg.sv"
add_fileset_file "prod_matrix_B5_branch.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B5_branch.sv"
add_fileset_file "prod_matrix_B5_merge.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B5_merge.sv"
add_fileset_file "prod_matrix_bb_B6.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B6.sv"
add_fileset_file "prod_matrix_bb_B6_stall_region.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B6_stall_region.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_push12_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_push12_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_push12_0_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_push12_0_reg.sv"
add_fileset_file "prod_matrix_B6_branch.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B6_branch.sv"
add_fileset_file "prod_matrix_B6_merge.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B6_merge.sv"
add_fileset_file "prod_matrix_bb_B7.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B7.sv"
add_fileset_file "prod_matrix_bb_B7_stall_region.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B7_stall_region.sv"
add_fileset_file "prod_matrix_i_iowr_bl_return_unnamed_prod_matrix17_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_iowr_bl_return_unnamed_prod_matrix17_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_token_i1_throttle_push_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_token_i1_throttle_push_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_token_i1_throttle_push_1_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_token_i1_throttle_push_1_reg.sv"
add_fileset_file "prod_matrix_B7_branch.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B7_branch.sv"
add_fileset_file "prod_matrix_B7_merge.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B7_merge.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going23_2_sr.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going23_2_sr.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going23_2_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going23_2_valid_fifo.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going27_2_sr.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going27_2_sr.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going27_2_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going27_2_valid_fifo.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going31_1_sr.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going31_1_sr.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going31_1_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going31_1_valid_fifo.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going_4_sr.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going_4_sr.sv"
add_fileset_file "prod_matrix_loop_limiter_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_loop_limiter_0.sv"
add_fileset_file "prod_matrix_loop_limiter_1.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_loop_limiter_1.sv"
add_fileset_file "prod_matrix_loop_limiter_2.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_loop_limiter_2.sv"
add_fileset_file "prod_matrix_bb_B2_sr_1.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B2_sr_1.sv"
add_fileset_file "prod_matrix_bb_B3_sr_1.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B3_sr_1.sv"
add_fileset_file "prod_matrix_bb_B4_sr_1.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B4_sr_1.sv"
add_fileset_file "prod_matrix_bb_B5_sr_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B5_sr_0.sv"
add_fileset_file "prod_matrix_bb_B6_sr_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B6_sr_0.sv"
add_fileset_file "prod_matrix_bb_B7_sr_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B7_sr_0.sv"
add_fileset_file "acl_avm_to_ic.v" SYSTEM_VERILOG PATH "ip/acl_avm_to_ic.v"
add_fileset_file "acl_ic_master_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_master_endpoint.v"
add_fileset_file "acl_arb_intf.v" SYSTEM_VERILOG PATH "ip/acl_arb_intf.v"
add_fileset_file "acl_ic_intf.v" SYSTEM_VERILOG PATH "ip/acl_ic_intf.v"
add_fileset_file "acl_ic_slave_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_endpoint.v"
add_fileset_file "acl_ic_slave_rrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_rrp.v"
add_fileset_file "acl_ic_slave_wrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_wrp.v"
add_fileset_file "acl_arb2.v" SYSTEM_VERILOG PATH "ip/acl_arb2.v"
add_fileset_file "acl_ic_to_avm.v" SYSTEM_VERILOG PATH "ip/acl_ic_to_avm.v"
add_fileset_file "prod_matrix_internal.v" SYSTEM_VERILOG PATH "prod_matrix_internal.v"

#### Simulation fileset
add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL prod_matrix_internal
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file "dspba_library_ver.sv" SYSTEM_VERILOG PATH "linux64/lib/dspba/Libraries/sv/base/dspba_library_ver.sv"
add_fileset_file "acl_data_fifo.v" SYSTEM_VERILOG PATH "ip/acl_data_fifo.v"
add_fileset_file "acl_fifo.v" SYSTEM_VERILOG PATH "ip/acl_fifo.v"
add_fileset_file "acl_altera_syncram_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_altera_syncram_wrapped.sv"
add_fileset_file "acl_scfifo_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_scfifo_wrapped.sv"
add_fileset_file "acl_ecc_decoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_decoder.sv"
add_fileset_file "acl_ecc_encoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_encoder.sv"
add_fileset_file "acl_ecc.svh" SYSTEM_VERILOG PATH "ip/acl_ecc.svh"
add_fileset_file "acl_ll_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_fifo.v"
add_fileset_file "acl_ll_ram_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_ram_fifo.v"
add_fileset_file "acl_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_valid_fifo_counter.v"
add_fileset_file "acl_dspba_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_dspba_valid_fifo_counter.v"
add_fileset_file "acl_staging_reg.v" SYSTEM_VERILOG PATH "ip/acl_staging_reg.v"
add_fileset_file "hld_fifo.sv" SYSTEM_VERILOG PATH "ip/hld_fifo.sv"
add_fileset_file "acl_mid_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_mid_speed_fifo.sv"
add_fileset_file "acl_latency_one_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_one_ram_fifo.sv"
add_fileset_file "acl_latency_zero_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_zero_ram_fifo.sv"
add_fileset_file "hld_fifo_zero_width.sv" SYSTEM_VERILOG PATH "ip/hld_fifo_zero_width.sv"
add_fileset_file "acl_high_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_high_speed_fifo.sv"
add_fileset_file "acl_low_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_low_latency_fifo.sv"
add_fileset_file "acl_zero_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_zero_latency_fifo.sv"
add_fileset_file "acl_fanout_pipeline.sv" SYSTEM_VERILOG PATH "ip/acl_fanout_pipeline.sv"
add_fileset_file "acl_std_synchronizer_nocut.v" SYSTEM_VERILOG PATH "ip/acl_std_synchronizer_nocut.v"
add_fileset_file "acl_tessellated_incr_decr_threshold.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_threshold.sv"
add_fileset_file "acl_tessellated_incr_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_lookahead.sv"
add_fileset_file "acl_reset_handler.sv" SYSTEM_VERILOG PATH "ip/acl_reset_handler.sv"
add_fileset_file "acl_lfsr.sv" SYSTEM_VERILOG PATH "ip/acl_lfsr.sv"
add_fileset_file "acl_pop.v" SYSTEM_VERILOG PATH "ip/acl_pop.v"
add_fileset_file "acl_push.v" SYSTEM_VERILOG PATH "ip/acl_push.v"
add_fileset_file "acl_token_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_token_fifo_counter.v"
add_fileset_file "acl_pipeline.v" SYSTEM_VERILOG PATH "ip/acl_pipeline.v"
add_fileset_file "acl_dspba_buffer.v" SYSTEM_VERILOG PATH "ip/acl_dspba_buffer.v"
add_fileset_file "acl_enable_sink.v" SYSTEM_VERILOG PATH "ip/acl_enable_sink.v"
add_fileset_file "st_top.v" SYSTEM_VERILOG PATH "ip/st_top.v"
add_fileset_file "acl_ffwdsrc.v" SYSTEM_VERILOG PATH "ip/acl_ffwdsrc.v"
add_fileset_file "acl_ffwddst.sv" SYSTEM_VERILOG PATH "ip/acl_ffwddst.sv"
add_fileset_file "acl_full_detector.v" SYSTEM_VERILOG PATH "ip/acl_full_detector.v"
add_fileset_file "acl_tessellated_incr_decr_decr.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_decr.sv"
add_fileset_file "lsu_top.v" SYSTEM_VERILOG PATH "ip/lsu_top.v"
add_fileset_file "lsu_permute_address.v" SYSTEM_VERILOG PATH "ip/lsu_permute_address.v"
add_fileset_file "lsu_pipelined.v" SYSTEM_VERILOG PATH "ip/lsu_pipelined.v"
add_fileset_file "lsu_enabled.v" SYSTEM_VERILOG PATH "ip/lsu_enabled.v"
add_fileset_file "lsu_basic_coalescer.v" SYSTEM_VERILOG PATH "ip/lsu_basic_coalescer.v"
add_fileset_file "lsu_simple.v" SYSTEM_VERILOG PATH "ip/lsu_simple.v"
add_fileset_file "lsu_streaming.v" SYSTEM_VERILOG PATH "ip/lsu_streaming.v"
add_fileset_file "lsu_burst_master.v" SYSTEM_VERILOG PATH "ip/lsu_burst_master.v"
add_fileset_file "lsu_bursting_load_stores.v" SYSTEM_VERILOG PATH "ip/lsu_bursting_load_stores.v"
add_fileset_file "lsu_non_aligned_write.v" SYSTEM_VERILOG PATH "ip/lsu_non_aligned_write.v"
add_fileset_file "lsu_read_cache.v" SYSTEM_VERILOG PATH "ip/lsu_read_cache.v"
add_fileset_file "lsu_atomic.v" SYSTEM_VERILOG PATH "ip/lsu_atomic.v"
add_fileset_file "lsu_prefetch_block.v" SYSTEM_VERILOG PATH "ip/lsu_prefetch_block.v"
add_fileset_file "lsu_wide_wrapper.v" SYSTEM_VERILOG PATH "ip/lsu_wide_wrapper.v"
add_fileset_file "lsu_streaming_prefetch.v" SYSTEM_VERILOG PATH "ip/lsu_streaming_prefetch.v"
add_fileset_file "acl_aligned_burst_coalesced_lsu.v" SYSTEM_VERILOG PATH "ip/acl_aligned_burst_coalesced_lsu.v"
add_fileset_file "acl_toggle_detect.v" SYSTEM_VERILOG PATH "ip/acl_toggle_detect.v"
add_fileset_file "acl_debug_mem.v" SYSTEM_VERILOG PATH "ip/acl_debug_mem.v"
add_fileset_file "lsu_burst_coalesced_pipelined_write.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_write.sv"
add_fileset_file "lsu_burst_coalesced_pipelined_read.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_read.sv"
add_fileset_file "acl_fifo_stall_valid_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_fifo_stall_valid_lookahead.sv"
add_fileset_file "acl_parameter_assert.svh" SYSTEM_VERILOG PATH "ip/acl_parameter_assert.svh"
add_fileset_file "hld_global_load_store.sv" SYSTEM_VERILOG PATH "ip/hld_global_load_store.sv"
add_fileset_file "hld_lsu.sv" SYSTEM_VERILOG PATH "ip/hld_lsu.sv"
add_fileset_file "hld_lsu_burst_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_burst_coalescer.sv"
add_fileset_file "hld_lsu_coalescer_dynamic_timeout.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_coalescer_dynamic_timeout.sv"
add_fileset_file "hld_lsu_data_aligner.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_data_aligner.sv"
add_fileset_file "hld_lsu_read_cache.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_cache.sv"
add_fileset_file "hld_lsu_read_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_data_alignment.sv"
add_fileset_file "hld_lsu_unaligned_controller.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_unaligned_controller.sv"
add_fileset_file "hld_lsu_word_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_word_coalescer.sv"
add_fileset_file "hld_lsu_write_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_data_alignment.sv"
add_fileset_file "hld_lsu_write_kernel_downstream.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_kernel_downstream.sv"
add_fileset_file "acl_shift_register_no_reset.sv" SYSTEM_VERILOG PATH "ip/acl_shift_register_no_reset.sv"
add_fileset_file "acl_loop_limiter.v" SYSTEM_VERILOG PATH "ip/acl_loop_limiter.v"
add_fileset_file "acl_reset_wire.v" SYSTEM_VERILOG PATH "ip/acl_reset_wire.v"
add_fileset_file "prod_matrix_function_wrapper.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_function_wrapper.sv"
add_fileset_file "prod_matrix_function.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_function.sv"
add_fileset_file "prod_matrix_bb_B0_runOnce.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B0_runOnce.sv"
add_fileset_file "prod_matrix_bb_B0_runOnce_stall_region.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B0_runOnce_stall_region.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_token_i1_wt_limpush_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_token_i1_wt_limpush_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv"
add_fileset_file "prod_matrix_B0_runOnce_merge_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B0_runOnce_merge_reg.sv"
add_fileset_file "prod_matrix_B0_runOnce_branch.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B0_runOnce_branch.sv"
add_fileset_file "prod_matrix_B0_runOnce_merge.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B0_runOnce_merge.sv"
add_fileset_file "prod_matrix_bb_B1_start.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B1_start.sv"
add_fileset_file "prod_matrix_bb_B1_start_stall_region.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B1_start_stall_region.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_source_i1_unnamed_5_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_source_i1_unnamed_5_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_source_i1_unnamed_6_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_source_i1_unnamed_6_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_source_i33_unnamed_7_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_source_i33_unnamed_7_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_source_i33_unnamed_8_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_source_i33_unnamed_8_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_source_p102A000000Znamed_3_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_source_p102A000000Znamed_3_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_source_p102A000000Znamed_4_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_source_p102A000000Znamed_4_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_throttle_i1_throttle_pop_1_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_throttle_i1_throttle_pop_1_reg.sv"
add_fileset_file "prod_matrix_B1_start_merge_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B1_start_merge_reg.sv"
add_fileset_file "prod_matrix_i_iord_bl_call_unnamed_prod_matrix2_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_iord_bl_call_unnamed_prod_matrix2_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_sfc_s_c0_in_wt_entry_s_c0_enter9_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_sfc_s_c0_in_wt_entry_s_c0_enter9_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Zc0_exit_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Zc0_exit_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter9_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter9_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going31_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going31_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notexitcond32_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notexitcond32_0.sv"
add_fileset_file "prod_matrix_B1_start_branch.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B1_start_branch.sv"
add_fileset_file "prod_matrix_B1_start_merge.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B1_start_merge.sv"
add_fileset_file "prod_matrix_bb_B2.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B2.sv"
add_fileset_file "prod_matrix_bb_B2_stall_region.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B2_stall_region.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop12_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop12_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop12_3_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop12_3_reg.sv"
add_fileset_file "prod_matrix_i_sfc_s_c0_in_for_cond1_prehA000000Zter6710_prod_matrix1.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_sfc_s_c0_in_for_cond1_prehA000000Zter6710_prod_matrix1.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Z_exit69_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Z_exit69_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Zatrix1_full_detector.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Zatrix1_full_detector.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Zod_matrix1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Zod_matrix1_data_fifo.sv"
add_fileset_file "prod_matrix_i_sfc_logic_s_c0_in_for_condA000000Zter6710_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_sfc_logic_s_c0_in_for_condA000000Zter6710_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_i1_cmp2017_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_i1_cmp2017_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_i33_unnamed_9_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_i33_unnamed_9_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going27_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going27_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_i_021_pop11_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_i_021_pop11_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i33_fpga_indvars_iv11_pop10_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i33_fpga_indvars_iv11_pop10_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notexitcond28_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notexitcond28_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_i_021_push11_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_i_021_push11_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i33_fpga_indvars_iv11_push10_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i33_fpga_indvars_iv11_push10_0.sv"
add_fileset_file "prod_matrix_B2_merge_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B2_merge_reg.sv"
add_fileset_file "prod_matrix_B2_branch.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B2_branch.sv"
add_fileset_file "prod_matrix_B2_merge.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B2_merge.sv"
add_fileset_file "prod_matrix_bb_B3.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B3.sv"
add_fileset_file "prod_matrix_bb_B3_stall_region.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B3_stall_region.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi3_pop15_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi3_pop15_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi3_pop15_3_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi3_pop15_3_reg.sv"
add_fileset_file "prod_matrix_i_sfc_s_c0_in_for_body6_lr_pA000000Zter7211_prod_matrix1.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_sfc_s_c0_in_for_body6_lr_pA000000Zter7211_prod_matrix1.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Z_exit78_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000000Z_exit78_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000001Zatrix1_full_detector.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000001Zatrix1_full_detector.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000001Zod_matrix1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_sfc_exit_s_c0_ouA000001Zod_matrix1_data_fifo.sv"
add_fileset_file "prod_matrix_i_sfc_logic_s_c0_in_for_bodyA000000Zter7211_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_sfc_logic_s_c0_in_for_bodyA000000Zter7211_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_i1_unnamed_12_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_i1_unnamed_12_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_i33_unnamed_11_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_i33_unnamed_11_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going23_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going23_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop1238_pop19_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop1238_pop19_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_notcmp2634_pop17_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_notcmp2634_pop17_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_pop16_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_pop16_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_i_021_pop1136_pop18_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_i_021_pop1136_pop18_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_j_018_pop14_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_j_018_pop14_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i33_fpga_indvars_iv8_pop13_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i33_fpga_indvars_iv8_pop13_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_pop1238_push19_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_pop1238_push19_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notcmp2634_push17_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notcmp2634_push17_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notexitcond24_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notexitcond24_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_push16_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_push16_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_i_021_pop1136_push18_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_i_021_pop1136_push18_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_j_018_push14_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_j_018_push14_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i33_fpga_indvars_iv8_push13_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i33_fpga_indvars_iv8_push13_0.sv"
add_fileset_file "prod_matrix_B3_merge_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B3_merge_reg.sv"
add_fileset_file "prod_matrix_B3_branch.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B3_branch.sv"
add_fileset_file "prod_matrix_B3_merge.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B3_merge.sv"
add_fileset_file "prod_matrix_bb_B4.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B4.sv"
add_fileset_file "prod_matrix_bb_B4_stall_region.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B4_stall_region.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_i1_unnamed_15_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_i1_unnamed_15_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_i1_unnamed_16_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_i1_unnamed_16_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_i33_unnamed_14_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_i33_unnamed_14_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_p1024a100i32_r2416_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_p1024a100i32_r2416_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_p1024a100i32_v2314_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_p1024a100i32_v2314_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_ffwd_dest_p1024a100i32_v2315_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_ffwd_dest_p1024a100i32_v2315_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_mem_lm1_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_mem_lm1_0.sv"
add_fileset_file "prod_matrix_readdata_reg_lm1_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_readdata_reg_lm1_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_mem_lm82_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_mem_lm82_0.sv"
add_fileset_file "prod_matrix_readdata_reg_lm82_1.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_readdata_reg_lm82_1.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_mem_memdep_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_mem_memdep_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going_4_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going_4_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi3_pop1542_pop31_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi3_pop1542_pop31_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi3_pop1542_pop31_25_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi3_pop1542_pop31_25_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop1239_pop27_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop1239_pop27_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop1239_pop27_23_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi4_pop1239_pop27_23_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi_pop22_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi_pop22_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_memdep_phi_pop22_28_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_memdep_phi_pop22_28_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_notcmp2240_pop29_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_notcmp2240_pop29_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_notcmp2240_pop29_58_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_notcmp2240_pop29_58_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_notcmp2635_pop25_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_notcmp2635_pop25_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_notcmp2635_pop25_54_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_notcmp2635_pop25_54_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_pop24_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_pop24_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_pop24_52_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_pop24_52_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_pop28_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_pop28_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i1_pop28_56_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i1_pop28_56_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i2_cleanups_pop23_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i2_cleanups_pop23_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i2_cleanups_pop23_0_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i2_cleanups_pop23_0_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_i_021_pop1137_pop26_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_i_021_pop1137_pop26_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_i_021_pop1137_pop26_12_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_i_021_pop1137_pop26_12_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_j_018_pop1441_pop30_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_j_018_pop1441_pop30_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_j_018_pop1441_pop30_9_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_j_018_pop1441_pop30_9_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_k_016_pop21_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_k_016_pop21_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i32_k_016_pop21_19_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i32_k_016_pop21_19_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i33_fpga_indvars_iv_pop20_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i33_fpga_indvars_iv_pop20_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pop_i33_fpga_indvars_iv_pop20_7_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pop_i33_fpga_indvars_iv_pop20_7_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_lastiniteration_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_lastiniteration_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_lastiniteration_5_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_lastiniteration_5_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi3_pop1542_push31_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi3_pop1542_push31_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi3_pop1542_push31_26_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi3_pop1542_push31_26_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_pop1239_push27_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_pop1239_push27_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_pop1239_push27_24_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_pop1239_push27_24_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi_push22_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi_push22_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi_push22_37_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi_push22_37_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notcmp2240_push29_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notcmp2240_push29_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notcmp2240_push29_59_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notcmp2240_push29_59_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notcmp2635_push25_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notcmp2635_push25_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notcmp2635_push25_55_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notcmp2635_push25_55_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notexitcond_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notexitcond_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_notexitcond_47_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_notexitcond_47_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_push24_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_push24_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_push24_53_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_push24_53_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_push28_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_push28_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_push28_57_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_push28_57_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i2_cleanups_push23_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i2_cleanups_push23_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i2_cleanups_push23_50_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i2_cleanups_push23_50_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_i_021_pop1137_push26_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_i_021_pop1137_push26_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_i_021_pop1137_push26_13_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_i_021_pop1137_push26_13_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_j_018_pop1441_push30_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_j_018_pop1441_push30_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_j_018_pop1441_push30_10_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_j_018_pop1441_push30_10_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_k_016_push21_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_k_016_push21_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i32_k_016_push21_39_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i32_k_016_push21_39_reg.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i33_fpga_indvars_iv_push20_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i33_fpga_indvars_iv_push20_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i33_fpga_indvars_iv_push20_43_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i33_fpga_indvars_iv_push20_43_reg.sv"
add_fileset_file "prod_matrix_B4_merge_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B4_merge_reg.sv"
add_fileset_file "prod_matrix_B4_branch.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B4_branch.sv"
add_fileset_file "prod_matrix_B4_merge.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B4_merge.sv"
add_fileset_file "prod_matrix_bb_B5.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B5.sv"
add_fileset_file "prod_matrix_bb_B5_stall_region.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B5_stall_region.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi3_push15_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi3_push15_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi3_push15_0_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi3_push15_0_reg.sv"
add_fileset_file "prod_matrix_B5_branch.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B5_branch.sv"
add_fileset_file "prod_matrix_B5_merge.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B5_merge.sv"
add_fileset_file "prod_matrix_bb_B6.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B6.sv"
add_fileset_file "prod_matrix_bb_B6_stall_region.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B6_stall_region.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_push12_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_push12_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_push12_0_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_i1_memdep_phi4_push12_0_reg.sv"
add_fileset_file "prod_matrix_B6_branch.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B6_branch.sv"
add_fileset_file "prod_matrix_B6_merge.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B6_merge.sv"
add_fileset_file "prod_matrix_bb_B7.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B7.sv"
add_fileset_file "prod_matrix_bb_B7_stall_region.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B7_stall_region.sv"
add_fileset_file "prod_matrix_i_iowr_bl_return_unnamed_prod_matrix17_prod_matrix0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_iowr_bl_return_unnamed_prod_matrix17_prod_matrix0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_token_i1_throttle_push_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_token_i1_throttle_push_0.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_push_token_i1_throttle_push_1_reg.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_push_token_i1_throttle_push_1_reg.sv"
add_fileset_file "prod_matrix_B7_branch.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B7_branch.sv"
add_fileset_file "prod_matrix_B7_merge.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_B7_merge.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going23_2_sr.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going23_2_sr.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going23_2_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going23_2_valid_fifo.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going27_2_sr.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going27_2_sr.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going27_2_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going27_2_valid_fifo.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going31_1_sr.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going31_1_sr.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going31_1_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going31_1_valid_fifo.sv"
add_fileset_file "prod_matrix_i_llvm_fpga_pipeline_keep_going_4_sr.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_i_llvm_fpga_pipeline_keep_going_4_sr.sv"
add_fileset_file "prod_matrix_loop_limiter_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_loop_limiter_0.sv"
add_fileset_file "prod_matrix_loop_limiter_1.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_loop_limiter_1.sv"
add_fileset_file "prod_matrix_loop_limiter_2.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_loop_limiter_2.sv"
add_fileset_file "prod_matrix_bb_B2_sr_1.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B2_sr_1.sv"
add_fileset_file "prod_matrix_bb_B3_sr_1.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B3_sr_1.sv"
add_fileset_file "prod_matrix_bb_B4_sr_1.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B4_sr_1.sv"
add_fileset_file "prod_matrix_bb_B5_sr_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B5_sr_0.sv"
add_fileset_file "prod_matrix_bb_B6_sr_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B6_sr_0.sv"
add_fileset_file "prod_matrix_bb_B7_sr_0.sv" SYSTEM_VERILOG PATH "ip/prod_matrix_bb_B7_sr_0.sv"
add_fileset_file "acl_avm_to_ic.v" SYSTEM_VERILOG PATH "ip/acl_avm_to_ic.v"
add_fileset_file "acl_ic_master_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_master_endpoint.v"
add_fileset_file "acl_arb_intf.v" SYSTEM_VERILOG PATH "ip/acl_arb_intf.v"
add_fileset_file "acl_ic_intf.v" SYSTEM_VERILOG PATH "ip/acl_ic_intf.v"
add_fileset_file "acl_ic_slave_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_endpoint.v"
add_fileset_file "acl_ic_slave_rrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_rrp.v"
add_fileset_file "acl_ic_slave_wrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_wrp.v"
add_fileset_file "acl_arb2.v" SYSTEM_VERILOG PATH "ip/acl_arb2.v"
add_fileset_file "acl_ic_to_avm.v" SYSTEM_VERILOG PATH "ip/acl_ic_to_avm.v"
add_fileset_file "prod_matrix_internal.v" SYSTEM_VERILOG PATH "prod_matrix_internal.v"

#### Primary clock for the component
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_assignment clock hls.cosim.name {$clock}
add_interface_port clock clock clk input 1

#### Primary reset for the component
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_assignment reset hls.cosim.name {$reset}
add_interface_port reset resetn reset_n input 1

#### The component invocation protocol interface (call)
add_interface call conduit sink
set_interface_property call associatedClock clock
set_interface_property call associatedReset reset
set_interface_assignment call hls.cosim.name {$call}
add_interface_port call start valid input 1
add_interface_port call busy stall output 1

#### The component return protocol interface (return)
add_interface return conduit source
set_interface_property return associatedClock clock
set_interface_property return associatedReset reset
set_interface_assignment return hls.cosim.name {$return}
add_interface_port return done valid output 1
add_interface_port return stall stall input 1

#### Parameter v interface
add_interface v conduit sink
set_interface_property v associatedClock clock
set_interface_property v associatedReset reset
set_interface_assignment v hls.cosim.name {v}
add_interface_port v v data input 64

#### Parameter r interface
add_interface r conduit sink
set_interface_property r associatedClock clock
set_interface_property r associatedReset reset
set_interface_assignment r hls.cosim.name {r}
add_interface_port r r data input 64

#### Parameter row interface
add_interface row conduit sink
set_interface_property row associatedClock clock
set_interface_property row associatedReset reset
set_interface_assignment row hls.cosim.name {row}
add_interface_port row row data input 32

#### Parameter col interface
add_interface col conduit sink
set_interface_property col associatedClock clock
set_interface_property col associatedReset reset
set_interface_assignment col hls.cosim.name {col}
add_interface_port col col data input 32

#### Master interface avmm_0_rw with base address 0
add_interface avmm_0_rw avalon start
set_interface_property avmm_0_rw ENABLED true
set_interface_property avmm_0_rw associatedClock clock
set_interface_property avmm_0_rw burstOnBurstBoundariesOnly false
set_interface_property avmm_0_rw doStreamReads false
set_interface_property avmm_0_rw doStreamWrites false
set_interface_property avmm_0_rw linewrapBursts false
set_interface_property avmm_0_rw readWaitTime 0
set_interface_property avmm_0_rw readLatency 1
add_interface_port avmm_0_rw avmm_0_rw_address address output 64
add_interface_port avmm_0_rw avmm_0_rw_byteenable byteenable output 8
add_interface_port avmm_0_rw avmm_0_rw_read read output 1
add_interface_port avmm_0_rw avmm_0_rw_readdata readdata input 64
add_interface_port avmm_0_rw avmm_0_rw_write write output 1
add_interface_port avmm_0_rw avmm_0_rw_writedata writedata output 64

#### Quartus settings (QIP strings)
set_qip_strings { "set_instance_assignment -entity \"%entityName%\" -library \"%libraryName%\" -name AUTO_SHIFT_REGISTER_RECOGNITION OFF -to *_NO_SHIFT_REG*"  }
