// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _ubc_check_HH_
#define _ubc_check_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct ubc_check : public sc_module {
    // Port declarations 18
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<7> > W_address0;
    sc_out< sc_logic > W_ce0;
    sc_out< sc_logic > W_we0;
    sc_out< sc_lv<32> > W_d0;
    sc_in< sc_lv<32> > W_q0;
    sc_out< sc_lv<7> > W_address1;
    sc_out< sc_logic > W_ce1;
    sc_out< sc_logic > W_we1;
    sc_out< sc_lv<32> > W_d1;
    sc_in< sc_lv<32> > W_q1;
    sc_out< sc_lv<1> > dvmask_address0;
    sc_out< sc_logic > dvmask_ce0;
    sc_out< sc_logic > dvmask_we0;
    sc_out< sc_lv<32> > dvmask_d0;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    ubc_check(sc_module_name name);
    SC_HAS_PROCESS(ubc_check);

    ~ubc_check();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<64> ap_const_lv64_0;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<32> ap_const_lv32_0;
    // Thread declarations
    void thread_W_address0();
    void thread_W_address1();
    void thread_W_ce0();
    void thread_W_ce1();
    void thread_W_d0();
    void thread_W_d1();
    void thread_W_we0();
    void thread_W_we1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_dvmask_address0();
    void thread_dvmask_ce0();
    void thread_dvmask_d0();
    void thread_dvmask_we0();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
