// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="nfs_open_file_remove_open_find,hls_ip_2019_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k160t-fbg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.546000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=93,HLS_VERSION=2019_1}" *)

module nfs_open_file_remove_open_find (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        nofp_nof_access,
        nofp_nof_deny,
        nofp_nof_r,
        nofp_nof_d_r,
        nofp_nof_rw,
        nofp_nof_d_rw,
        nofp_nof_r_dw,
        nofp_nof_d_r_dw,
        nofp_nof_rw_dw,
        nofp_nof_d_rw_dw,
        nofp_nof_r_drw,
        nofp_nof_d_r_drw,
        nofp_nof_w,
        nofp_nof_d_w,
        nofp_nof_w_dw,
        nofp_nof_d_w_dw,
        nofp_nof_w_drw,
        nofp_nof_d_w_drw,
        nofp_nof_rw_drw,
        nofp_nof_d_rw_drw,
        accessMode,
        denyMode,
        newAccessMode,
        newAccessMode_ap_vld,
        newDenyMode,
        newDenyMode_ap_vld,
        delegated,
        delegated_ap_vld
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] nofp_nof_access;
input  [31:0] nofp_nof_deny;
input  [31:0] nofp_nof_r;
input  [31:0] nofp_nof_d_r;
input  [31:0] nofp_nof_rw;
input  [31:0] nofp_nof_d_rw;
input  [31:0] nofp_nof_r_dw;
input  [31:0] nofp_nof_d_r_dw;
input  [31:0] nofp_nof_rw_dw;
input  [31:0] nofp_nof_d_rw_dw;
input  [31:0] nofp_nof_r_drw;
input  [31:0] nofp_nof_d_r_drw;
input  [31:0] nofp_nof_w;
input  [31:0] nofp_nof_d_w;
input  [31:0] nofp_nof_w_dw;
input  [31:0] nofp_nof_d_w_dw;
input  [31:0] nofp_nof_w_drw;
input  [31:0] nofp_nof_d_w_drw;
input  [31:0] nofp_nof_rw_drw;
input  [31:0] nofp_nof_d_rw_drw;
input  [31:0] accessMode;
input  [31:0] denyMode;
output  [31:0] newAccessMode;
output   newAccessMode_ap_vld;
output  [31:0] newDenyMode;
output   newDenyMode_ap_vld;
output  [31:0] delegated;
output   delegated_ap_vld;

reg newAccessMode_ap_vld;
reg newDenyMode_ap_vld;
reg[31:0] delegated;
reg delegated_ap_vld;

wire   [0:0] icmp_ln75_fu_124_p2;
wire   [0:0] icmp_ln76_fu_130_p2;
wire   [31:0] zext_ln95_fu_142_p1;
wire   [31:0] zext_ln77_fu_153_p1;
wire   [0:0] icmp_ln95_fu_136_p2;
wire   [0:0] icmp_ln77_fu_147_p2;

always @ (*) begin
    if (((icmp_ln76_fu_130_p2 == 1'd1) & (icmp_ln75_fu_124_p2 == 1'd1) & (ap_start == 1'b1))) begin
        delegated = zext_ln77_fu_153_p1;
    end else if (((icmp_ln76_fu_130_p2 == 1'd1) & (icmp_ln75_fu_124_p2 == 1'd0) & (ap_start == 1'b1))) begin
        delegated = zext_ln95_fu_142_p1;
    end else if ((((icmp_ln76_fu_130_p2 == 1'd0) & (icmp_ln75_fu_124_p2 == 1'd1) & (ap_start == 1'b1)) | ((icmp_ln76_fu_130_p2 == 1'd0) & (icmp_ln75_fu_124_p2 == 1'd0) & (ap_start == 1'b1)))) begin
        delegated = 32'd0;
    end else begin
        delegated = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln76_fu_130_p2 == 1'd1) & (icmp_ln75_fu_124_p2 == 1'd1) & (ap_start == 1'b1)) | ((icmp_ln76_fu_130_p2 == 1'd0) & (icmp_ln75_fu_124_p2 == 1'd1) & (ap_start == 1'b1)) | ((icmp_ln76_fu_130_p2 == 1'd1) & (icmp_ln75_fu_124_p2 == 1'd0) & (ap_start == 1'b1)) | ((icmp_ln76_fu_130_p2 == 1'd0) & (icmp_ln75_fu_124_p2 == 1'd0) & (ap_start == 1'b1)))) begin
        delegated_ap_vld = 1'b1;
    end else begin
        delegated_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        newAccessMode_ap_vld = 1'b1;
    end else begin
        newAccessMode_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        newDenyMode_ap_vld = 1'b1;
    end else begin
        newDenyMode_ap_vld = 1'b0;
    end
end

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign icmp_ln75_fu_124_p2 = ((denyMode == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_130_p2 = ((accessMode == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln77_fu_147_p2 = ((nofp_nof_d_r != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_136_p2 = ((nofp_nof_d_r_drw != 32'd0) ? 1'b1 : 1'b0);

assign newAccessMode = nofp_nof_access;

assign newDenyMode = nofp_nof_deny;

assign zext_ln77_fu_153_p1 = icmp_ln77_fu_147_p2;

assign zext_ln95_fu_142_p1 = icmp_ln95_fu_136_p2;

endmodule //nfs_open_file_remove_open_find
